In [1]:
import pandas as pd
corp_info = pd.read_csv('corp.csv', header=0)
corp_info

,순위,종목코드,종목명,현재가,대비,등락률,거래량,거래대금,시가,고가,저가,시가총액,시가총액비중(%),상장주식수,외국인 보유주식수,외국인 지분율(%),총카운트
0,1,005930,삼성전자,"46,100","-1,050",-2.2,"6,854,965","317,650,411,250","46,800","47,050","46,000","275,206,975,555,000",17.49,"5,969,782,550",NaN,NaN,2405.0
1,2,000660,SK하이닉스,"77,000","-2,800",-3.5,"2,616,455","203,392,849,900","79,000","79,400","76,500","56,056,182,105,000",3.56,"728,002,365",NaN,NaN,NaN
2,3,005935,삼성전자우,"38,100",-500,-1.3,"823,913","31,399,459,992","38,600","38,600","37,900","31,351,983,270,000",1.99,"822,886,700",NaN,NaN,NaN
3,4,005380,현대차,"128,000","-2,500",-1.9,"464,277","59,477,099,500","130,000","131,000","126,500","27,349,527,936,000",1.74,"213,668,187",NaN,NaN,NaN
4,5,051910,LG화학,"333,000",0,0.0,"168,074","55,303,005,500","333,500","333,500","325,000","23,507,250,219,000",1.49,"70,592,343",NaN,NaN,NaN
5,6,012330,현대모비스,"242,500","-3,000",-1.2,"169,686","40,865,947,500","245,500","245,500","237,500","23,111,873,295,000",1.47,"95,306,694",NaN,NaN,NaN
6,7,068270,셀트리온,"179,000","-6,000",-3.2,"433,127","78,396,577,000","183,500","184,500","179,000","22,970,903,530,000",1.46,"128,329,070",NaN,NaN,NaN
7,8,035420,NAVER,"138,500","-2,500",-1.8,"583,604","80,883,355,500","139,500","141,000","137,000","22,826,655,207,500",1.45,"164,813,395",NaN,NaN,NaN
8,9,055550,신한지주,"43,900",250,0.6,"871,054","38,233,388,300","43,800","44,150","43,600","20,817,361,869,300",1.32,"474,199,587",NaN,NaN,NaN
9,10,005490,POSCO,"228,500","-4,000",-1.7,"194,010","44,631,084,000","233,000","233,000","228,500","19,922,191,797,500",1.27,"87,186,835",NaN,NaN,NaN
10,11,017670,SK텔레콤,"246,000",500,0.2,"121,033","29,804,367,500","247,500","249,000","244,000","19,863,444,906,000",1.26,"80,745,711",NaN,NaN,NaN
11,12,051900,LG생활건강,"1,240,000","16,000",1.3,"31,789","39,285,922,000","1,230,000","1,248,000","1,226,000","19,366,564,280,000",1.23,"15,618,197",NaN,NaN,NaN
12,13,105560,KB금융,"43,600",-200,-0.5,"630,292","27,480,484,000","43,950","44,100","43,400","18,229,663,013,200",1.16,"418,111,537",NaN,NaN,NaN
13,14,207940,삼성바이오로직스,"273,000","-2,500",-0.9,"83,126","22,733,567,000","273,000","278,000","271,000","18,063,045,000,000",1.15,"66,165,000",NaN,NaN,NaN
14,15,015760,한국전력,"27,950",350,1.3,"1,840,989","51,060,219,550","27,600","27,950","27,300","17,942,895,952,150",1.14,"641,964,077",NaN,NaN,NaN
15,16,028260,삼성물산,"92,300","-2,200",-2.3,"213,772","19,794,618,700","94,000","94,100","91,800","17,508,390,968,900",1.11,"189,690,043",NaN,NaN,NaN
16,17,000270,기아차,"42,850",-750,-1.7,"782,422","33,611,610,600","43,800","43,900","42,500","17,369,819,418,950",1.10,"405,363,347",NaN,NaN,NaN
17,18,018260,삼성에스디에스,"212,000","-3,500",-1.6,"66,628","14,254,540,000","215,500","219,000","212,000","16,404,093,600,000",1.04,"77,377,800",NaN,NaN,NaN
18,19,006400,삼성SDI,"229,000","-3,000",-1.3,"180,305","41,102,882,000","231,500","232,500","225,500","15,747,077,370,000",1.00,"68,764,530",NaN,NaN,NaN
19,20,096770,SK이노베이션,"169,000","-4,000",-2.3,"282,740","47,497,441,561","174,000","174,000","164,500","15,626,680,316,000",0.99,"92,465,564",NaN,NaN,NaN
20,21,034730,SK,"221,500","-3,000",-1.3,"71,878","15,921,621,000","224,500","224,500","219,500","15,584,805,785,500",0.99,"70,360,297",NaN,NaN,NaN
21,22,032830,삼성생명,"77,000",-800,-1.0,"221,890","17,015,807,000","77,700","78,200","76,000","15,400,000,000,000",0.98,"200,000,000",NaN,NaN,NaN
22,23,033780,KT&G,"96,800",0,0.0,"205,333","19,950,938,000","97,100","97,900","96,800","13,289,913,709,600",0.84,"137,292,497",NaN,NaN,NaN
23,24,003550,LG,"73,300",-800,-1.1,"138,814","10,159,491,100","73,700","74,300","72,200","12,648,437,702,300",0.80,"172,557,131",NaN,NaN,NaN
24,25,000810,삼성화재,"262,500",-500,-0.2,"64,363","16,805,742,750","262,500","263,500","258,000","12,435,894,712,500",0.79,"47,374,837",NaN,NaN,NaN
25,26,066570,LG전자,"68,600",0,0.0,"377,472","25,967,194,700","68,300","69,700","68,000","11,226,240,040,400",0.71,"163,647,814",NaN,NaN,NaN
26,27,035720,카카오,"129,000","-2,000",-1.5,"368,365","47,659,535,500","130,000","132,000","128,000","10,768,353,690,000",0.68,"83,475,610",NaN,NaN,NaN
27,28,036570,엔씨소프트,"485,000","-7,000",-1.4,"53,965","26,253,350,000","490,000","495,000","481,000","10,644,063,170,000",0.68,"21,946,522",NaN,NaN,NaN
28,29,086790,하나금융지주,"35,100",-250,-0.7,"926,666","32,582,323,800","35,350","35,500","34,900","10,538,496,376,200",0.67,"300,242,062",NaN,NaN,NaN
29,30,010950,S-Oil,"91,700","-1,300",-1.4,"276,318","25,198,697,800","92,900","92,900","90,300","10,323,842,026,400",0.66,"112,582,792",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2375,2376,002785,진흥기업우B,"5,190",-240,-4.4,"23,393","121,733,250","5,400","5,470","5,020","4,448,961,420",0.00,"857,218",NaN,NaN,NaN
2376,2377,005965,동부건설우,"19,250",350,1.8,"2,337","43,569,150","18,900","19,500","18,200","4,345,341,000",0.00,"225,732",NaN,NaN,NaN
2377,2378,099350,하나니켈2호,"1,305",-135,-9.4,"68,876","93,513,190","1,415","1,450","1,300","4,285,620,000",0.00,"3,284,000",NaN,NaN,NaN
2378,2379,001755,한양증권우,"8,090",-260,-3.1,"3,313","26,739,700","8,360","8,360","7,910","4,247,250,000",0.00,"525,000",NaN,NaN,NaN
2379,2380,245450,씨앤에스링크,"2,640",-460,-14.8,472,"1,252,540","3,100","3,100","2,640","4,171,094,400",0.00,"1,579,960",NaN,NaN,NaN
2380,2381,001065,JW중외제약우,"24,800",-950,-3.7,"1,199","29,888,500","25,300","26,000","24,650","4,150,900,000",0.00,"167,375",NaN,NaN,NaN
2381,2382,271850,다이오진,"1,375",-80,-5.5,"4,621","5,795,605","1,515","1,515","1,250","4,125,000,000",0.00,"3,000,000",NaN,NaN,NaN
2382,2383,000995,DB하이텍1우,"36,050","-1,250",-3.4,979,"34,877,750","37,000","37,000","34,600","4,048,991,800",0.00,"112,316",NaN,NaN,NaN
2383,2384,002787,진흥기업2우B,"13,500",-400,-2.9,"5,760","77,446,750","13,900","13,900","13,250","3,979,908,000",0.00,"294,808",NaN,NaN,NaN
2384,2385,084440,유비온,"1,300",0,0.0,10,"13,000","1,300","1,300","1,300","3,896,239,100",0.00,"2,997,107",NaN,NaN,NaN
2385,2386,000545,흥국화재우,"4,975",-95,-1.9,"2,249","11,100,205","5,230","5,230","4,800","3,820,800,000",0.00,"768,000",NaN,NaN,NaN
2386,2387,092590,럭스피아,517,-61,-10.6,15,"9,653",664,664,517,"3,769,497,666",0.00,"7,291,098",NaN,NaN,NaN
2387,2388,001067,JW중외제약2우B,"39,350",-600,-1.5,590,"23,487,150","39,950","41,400","39,250","3,454,536,500",0.00,"87,790",NaN,NaN,NaN
2388,2389,189350,코셋,835,-80,-8.7,"1,026","1,073,961","1,050","1,050",788,"3,340,000,000",0.00,"4,000,000",NaN,NaN,NaN
2389,2390,149940,모다,155,0,0.0,0,0,0,0,0,"3,279,863,395",0.00,"21,160,409",NaN,NaN,NaN
2390,2391,00781K,코리아써키트2우B,"4,100",-210,-4.9,439,"1,785,855","4,065","4,140","4,065","3,213,165,900",0.00,"783,699",NaN,NaN,NaN
2391,2392,000325,노루홀딩스우,"17,200",-800,-4.4,300,"5,202,350","18,400","18,400","17,200","3,186,300,000",0.00,"185,250",NaN,NaN,NaN
2392,2393,032685,소프트센우,"22,000",-150,-0.7,"1,417","31,284,200","22,150","23,500","21,650","3,142,854,000",0.00,"142,857",NaN,NaN,NaN
2393,2394,227420,포레스팅블록체인,399,-31,-7.2,2,798,399,399,399,"3,027,586,464",0.00,"7,587,936",NaN,NaN,NaN
2394,2395,001527,동양2우B,"9,810",-290,-2.9,683,"6,778,610","10,500","10,500","9,700","3,027,061,890",0.00,"308,569",NaN,NaN,NaN
2395,2396,000547,흥국화재2우B,"19,200","-1,650",-7.9,"1,082","21,402,850","20,850","20,850","19,200","2,949,120,000",0.00,"153,600",NaN,NaN,NaN
2396,2397,000227,유유제약2우B,"17,900",-400,-2.2,350,"6,340,400","18,000","19,050","17,900","2,937,032,000",0.00,"164,080",NaN,NaN,NaN
2397,2398,001799,대한제당3우B,"21,500","-1,600",-6.9,"1,415","31,142,150","23,200","23,200","21,500","2,787,604,000",0.00,"129,656",NaN,NaN,NaN
2398,2399,223220,아이피몬스터,256,0,0.0,0,0,0,0,0,"2,761,538,816",0.00,"10,787,261",NaN,NaN,NaN
2399,2400,208890,에듀파트너,"1,310",-220,-14.4,11,"15,310","1,400","1,400","1,310","2,607,974,200",0.00,"1,990,820",NaN,NaN,NaN
2400,2401,276240,엘리비젼,997,1,0.1,"1,123","1,120,472",854,"1,140",854,"2,579,438,400",0.00,"2,587,200",NaN,NaN,NaN
2401,2402,001529,동양3우B,"27,600",-950,-3.3,"1,889","52,265,350","28,150","29,000","27,200","2,476,327,200",0.00,"89,722",NaN,NaN,NaN
2402,2403,247300,인프라웨어테크놀러지,370,-36,-8.9,"2,860","1,058,200",370,370,370,"2,263,733,260",0.00,"6,118,198",NaN,NaN,NaN
2403,2404,224020,에스케이씨에스,830,-140,-14.4,"1,151","1,004,780",873,873,830,"2,241,000,000",0.00,"2,700,000",NaN,NaN,NaN
2404,2405,135270,세종머티리얼즈,104,0,0.0,0,0,0,0,0,"743,189,304",0.00,"7,146,051",NaN,NaN,NaN

In [2]:
corp_info = corp_info[['종목코드','종목명','현재가','상장주식수']]
corp_info["종목명"][:5]

0      삼성전자
1    SK하이닉스
2     삼성전자우
3       현대차
4      LG화학
Name: 종목명, dtype: object

In [11]:
corp_info.loc[:, '종목코드'] = 'A'
corp_info

c:\users\hyunn\envs\stocklab\lib\site-packages\pandas\core\indexing.py:635: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item_labels[indexer[info_axis]]] = value

     종목코드         종목명        현재가          상장주식수    종목코드A
0       A        삼성전자     46,100  5,969,782,550  A005930
1       A      SK하이닉스     77,000    728,002,365  A000660
2       A       삼성전자우     38,100    822,886,700  A005935
3       A         현대차    128,000    213,668,187  A005380
4       A        LG화학    333,000     70,592,343  A051910
5       A       현대모비스    242,500     95,306,694  A012330
6       A        셀트리온    179,000    128,329,070  A068270
7       A       NAVER    138,500    164,813,395  A035420
8       A        신한지주     43,900    474,199,587  A055550
9       A       POSCO    228,500     87,186,835  A005490
10      A       SK텔레콤    246,000     80,745,711  A017670
11      A      LG생활건강  1,240,000     15,618,197  A051900
12      A        KB금융     43,600    418,111,537  A105560
13      A    삼성바이오로직스    273,000     66,165,000  A207940
14      A        한국전력     27,950    641,964,077  A015760
15      A        삼성물산     92,300    189,690,043  A028260
16      A         기아차     42,850    405,363,347  A000270
17      A     삼성에스디에스    212,000     77,377,800  A018260
18      A       삼성SDI    229,000     68,764,530  A006400
19      A     SK이노베이션    169,000     92,465,564  A096770
20      A          SK    221,500     70,360,297  A034730
21      A        삼성생명     77,000    200,000,000  A032830
22      A        KT&G     96,800    137,292,497  A033780
23      A          LG     73,300    172,557,131  A003550
24      A        삼성화재    262,500     47,374,837  A000810
25      A        LG전자     68,600    163,647,814  A066570
26      A         카카오    129,000     83,475,610  A035720
27      A       엔씨소프트    485,000     21,946,522  A036570
28      A      하나금융지주     35,100    300,242,062  A086790
29      A       S-Oil     91,700    112,582,792  A010950
...   ...         ...        ...            ...      ...
2375    A      진흥기업우B      5,190        857,218  A002785
2376    A       동부건설우     19,250        225,732  A005965
2377    A      하나니켈2호      1,305      3,284,000  A099350
2378    A       한양증권우      8,090        525,000  A001755
2379    A      씨앤에스링크      2,640      1,579,960  A245450
2380    A     JW중외제약우     24,800        167,375  A001065
2381    A        다이오진      1,375      3,000,000  A271850
2382    A     DB하이텍1우     36,050        112,316  A000995
2383    A     진흥기업2우B     13,500        294,808  A002787
2384    A         유비온      1,300      2,997,107  A084440
2385    A       흥국화재우      4,975        768,000  A000545
2386    A        럭스피아        517      7,291,098  A092590
2387    A   JW중외제약2우B     39,350         87,790  A001067
2388    A          코셋        835      4,000,000  A189350
2389    A          모다        155     21,160,409  A149940
2390    A   코리아써키트2우B      4,100        783,699  A00781K
2391    A      노루홀딩스우     17,200        185,250  A000325
2392    A       소프트센우     22,000        142,857  A032685
2393    A    포레스팅블록체인        399      7,587,936  A227420
2394    A       동양2우B      9,810        308,569  A001527
2395    A     흥국화재2우B     19,200        153,600  A000547
2396    A     유유제약2우B     17,900        164,080  A000227
2397    A     대한제당3우B     21,500        129,656  A001799
2398    A      아이피몬스터        256     10,787,261  A223220
2399    A       에듀파트너      1,310      1,990,820  A208890
2400    A        엘리비젼        997      2,587,200  A276240
2401    A       동양3우B     27,600         89,722  A001529
2402    A  인프라웨어테크놀러지        370      6,118,198  A247300
2403    A     에스케이씨에스        830      2,700,000  A224020
2404    A     세종머티리얼즈        104      7,146,051  A135270

[2405 rows x 5 columns]

In [4]:
def double_data(value):
    return value*2
modified_data = corp_info.apply(double_data)
modified_data

,종목코드,종목명,현재가,상장주식수
0,A005930A005930,삼성전자삼성전자,"46,10046,100","5,969,782,5505,969,782,550"
1,A000660A000660,SK하이닉스SK하이닉스,"77,00077,000","728,002,365728,002,365"
2,A005935A005935,삼성전자우삼성전자우,"38,10038,100","822,886,700822,886,700"
3,A005380A005380,현대차현대차,"128,000128,000","213,668,187213,668,187"
4,A051910A051910,LG화학LG화학,"333,000333,000","70,592,34370,592,343"
5,A012330A012330,현대모비스현대모비스,"242,500242,500","95,306,69495,306,694"
6,A068270A068270,셀트리온셀트리온,"179,000179,000","128,329,070128,329,070"
7,A035420A035420,NAVERNAVER,"138,500138,500","164,813,395164,813,395"
8,A055550A055550,신한지주신한지주,"43,90043,900","474,199,587474,199,587"
9,A005490A005490,POSCOPOSCO,"228,500228,500","87,186,83587,186,835"
10,A017670A017670,SK텔레콤SK텔레콤,"246,000246,000","80,745,71180,745,711"
11,A051900A051900,LG생활건강LG생활건강,"1,240,0001,240,000","15,618,19715,618,197"
12,A105560A105560,KB금융KB금융,"43,60043,600","418,111,537418,111,537"
13,A207940A207940,삼성바이오로직스삼성바이오로직스,"273,000273,000","66,165,00066,165,000"
14,A015760A015760,한국전력한국전력,"27,95027,950","641,964,077641,964,077"
15,A028260A028260,삼성물산삼성물산,"92,30092,300","189,690,043189,690,043"
16,A000270A000270,기아차기아차,"42,85042,850","405,363,347405,363,347"
17,A018260A018260,삼성에스디에스삼성에스디에스,"212,000212,000","77,377,80077,377,800"
18,A006400A006400,삼성SDI삼성SDI,"229,000229,000","68,764,53068,764,530"
19,A096770A096770,SK이노베이션SK이노베이션,"169,000169,000","92,465,56492,465,564"
20,A034730A034730,SKSK,"221,500221,500","70,360,29770,360,297"
21,A032830A032830,삼성생명삼성생명,"77,00077,000","200,000,000200,000,000"
22,A033780A033780,KT&GKT&G,"96,80096,800","137,292,497137,292,497"
23,A003550A003550,LGLG,"73,30073,300","172,557,131172,557,131"
24,A000810A000810,삼성화재삼성화재,"262,500262,500","47,374,83747,374,837"
25,A066570A066570,LG전자LG전자,"68,60068,600","163,647,814163,647,814"
26,A035720A035720,카카오카카오,"129,000129,000","83,475,61083,475,610"
27,A036570A036570,엔씨소프트엔씨소프트,"485,000485,000","21,946,52221,946,522"
28,A086790A086790,하나금융지주하나금융지주,"35,10035,100","300,242,062300,242,062"
29,A010950A010950,S-OilS-Oil,"91,70091,700","112,582,792112,582,792"
...,...,...,...,...
2375,A002785A002785,진흥기업우B진흥기업우B,"5,1905,190","857,218857,218"
2376,A005965A005965,동부건설우동부건설우,"19,25019,250","225,732225,732"
2377,A099350A099350,하나니켈2호하나니켈2호,"1,3051,305","3,284,0003,284,000"
2378,A001755A001755,한양증권우한양증권우,"8,0908,090","525,000525,000"
2379,A245450A245450,씨앤에스링크씨앤에스링크,"2,6402,640","1,579,9601,579,960"
2380,A001065A001065,JW중외제약우JW중외제약우,"24,80024,800","167,375167,375"
2381,A271850A271850,다이오진다이오진,"1,3751,375","3,000,0003,000,000"
2382,A000995A000995,DB하이텍1우DB하이텍1우,"36,05036,050","112,316112,316"
2383,A002787A002787,진흥기업2우B진흥기업2우B,"13,50013,500","294,808294,808"
2384,A084440A084440,유비온유비온,"1,3001,300","2,997,1072,997,107"
2385,A000545A000545,흥국화재우흥국화재우,"4,9754,975","768,000768,000"
2386,A092590A092590,럭스피아럭스피아,517517,"7,291,0987,291,098"
2387,A001067A001067,JW중외제약2우BJW중외제약2우B,"39,35039,350","87,79087,790"
2388,A189350A189350,코셋코셋,835835,"4,000,0004,000,000"
2389,A149940A149940,모다모다,155155,"21,160,40921,160,409"
2390,A00781KA00781K,코리아써키트2우B코리아써키트2우B,"4,1004,100","783,699783,699"
2391,A000325A000325,노루홀딩스우노루홀딩스우,"17,20017,200","185,250185,250"
2392,A032685A032685,소프트센우소프트센우,"22,00022,000","142,857142,857"
2393,A227420A227420,포레스팅블록체인포레스팅블록체인,399399,"7,587,9367,587,936"
2394,A001527A001527,동양2우B동양2우B,"9,8109,810","308,569308,569"
2395,A000547A000547,흥국화재2우B흥국화재2우B,"19,20019,200","153,600153,600"
2396,A000227A000227,유유제약2우B유유제약2우B,"17,90017,900","164,080164,080"
2397,A001799A001799,대한제당3우B대한제당3우B,"21,50021,500","129,656129,656"
2398,A223220A223220,아이피몬스터아이피몬스터,256256,"10,787,26110,787,261"
2399,A208890A208890,에듀파트너에듀파트너,"1,3101,310","1,990,8201,990,820"
2400,A276240A276240,엘리비젼엘리비젼,997997,"2,587,2002,587,200"
2401,A001529A001529,동양3우B동양3우B,"27,60027,600","89,72289,722"
2402,A247300A247300,인프라웨어테크놀러지인프라웨어테크놀러지,370370,"6,118,1986,118,198"
2403,A224020A224020,에스케이씨에스에스케이씨에스,830830,"2,700,0002,700,000"
2404,A135270A135270,세종머티리얼즈세종머티리얼즈,104104,"7,146,0517,146,051"

In [5]:
corp_result = pd.read_excel('SAMPLE_2018.xlsx')
corp_result

,종목코드,회사명,당기순이익,유동자산,부채총계,매출총이익,자본총계,자산총계
0,A000020,동화약품,10068113000,227887463000,73198591000,115903237000,297400652000,370599243000
1,A000040,KR모터스,-24442080000,86949763000,85006462000,-631020000,69894605000,154901067000
2,A000050,경방,20189241000,120711492000,593023494000,107395818000,708769347000,1301792841000
3,A000060,메리츠화재,234721346000,0,18195561629000,0,2283200522000,20478762151000
4,A000070,삼양홀딩스,102512252000,1057235344000,1311855275000,482105988000,2001941981000,3313797255000
5,A000080,하이트진로,22272353000,1064966843000,2265764980000,761860402000,1162378535000,3428143515000
6,A000100,유한양행,58334962000,1110961783000,522077130000,413792024000,1651735504000,2173812633000
7,A000120,CJ대한통운,51800069000,2180844615000,4737828935000,828072934000,3138903155000,7876732089000
8,A000140,하이트진로홀딩스,8640980000,1083713642000,2893499586000,767141228000,1095786557000,3989286143000
9,A000150,두산,-340510995000,11585894166000,21735235429000,3323508790000,7145046191000,28880281620000
10,A000180,성창기업지주,-7933704000,85694716000,159282203000,17312092000,489378544000,648660747000
11,A000210,대림산업,678088774000,6366648561000,6783472630000,1420161607000,6050244102000,12833716732000
12,A000220,유유제약,4312110000,68869662000,48354059000,40636937000,86872256000,135226315000
13,A000230,일동홀딩스,-3831883000,54890858000,100522263000,20013961000,164946011000,265468274000
14,A000240,한국타이어월드와이드,218355604000,590386119000,262718282000,284108210000,3235872326000,3498590608000
15,A000250,삼천당제약,14592937000,142271889000,55394974000,83197927000,205763466000,261158440000
16,A000270,기아차,1155943000000,19711791000000,24543141000000,7992530000000,27243464000000,51786605000000
17,A000300,대유플러스,19120849000,250712765000,863495206000,73675381000,140608976000,1004104182000
18,A000320,노루홀딩스,2664076000,449147290000,425647066000,183192460000,561495276000,987142342000
19,A000370,한화손해보험,81759590000,0,15318315284000,0,1415552026000,16733867311000
20,A000390,삼화페인트,800759000,275185176000,276200374000,87345386000,281779106000,557979480000
21,A000400,롯데손해보험,91314265000,0,13651651397000,0,563337402000,14214988799000
22,A000430,대원강업,23857286000,352164240000,515047305000,114161257000,570720025000,1085767330000
23,A000440,중앙에너비스,889990000,4174206000,13480020000,12696157000,45263718000,58743738000
24,A000480,조선내화,57955243000,369512835000,336922588000,116768660000,693699617000,1030622205000
25,A000490,대동공업,1464262000,447800610000,555212961000,125048867000,217503766000,772716728000
26,A000500,가온전선,98902000,277829165000,266088415000,35493547000,260405860000,526494275000
27,A000520,삼일제약,-8562748000,59184330000,91865621000,34791021000,56082999000,147948619000
28,A000540,흥국화재,50441000000,0,11256838000000,0,682034000000,11938872000000
29,A000590,CS홀딩스,12641149000,188480772000,29665433000,28531036000,274752760000,304418193000
...,...,...,...,...,...,...,...,...
1979,A297570,IBKS제9호스팩,-756000,0,939793000,0,5267905000,6207699000
1980,A298000,효성화학,20394861000,438322896000,1286001139000,114602893000,367248241000,1653249379000
1981,A298020,효성티앤씨,31498303000,1428058179000,2651942914000,255765643000,486901345000,3138844259000
1982,A298040,효성중공업,1908746000,1492635018000,2527800474000,239206367000,904711079000,3432511553000
1983,A298050,효성첨단소재,-23744728000,1030997728000,2068681942000,182774224000,466015869000,2534697811000
1984,A298380,에이비엘바이오,-117234140000,161091085000,11906880000,1257884000,156962235000,168869115000
1985,A298690,에어부산,20294184000,105633987000,150402815000,65447298000,152296942000,302699757000
1986,A299170,IBKS제10호스팩,-25108000,0,1499562000,0,8332973000,9832536000
1987,A299660,셀리드,-11286321000,8239136000,720628000,0,13495505000,14216133000
1988,A300720,한일시멘트,53726823000,565218272000,499783148000,119349714000,868218023000,1368001171000
1989,A302430,이노메트리,5247720000,52774757000,11292993000,11012834000,48364402000,59657395000
1990,A303030,대신밸런스제5호스팩,-4049000,0,651846000,0,7758537000,8410382000
1991,A306200,세아제강,7030156000,479655614000,500666740000,32708406000,553451801000,1054118541000
1992,A306620,DB금융스팩6호,33000,0,1056050000,0,8797198000,9853248000
1993,A307070,SK4호스팩,-24500000,0,738660000,0,9116796000,9855456000
1994,A307160,하나머스트제6호스팩,-9884000,0,716747000,0,8216413000,8933159000
1995,A307180,신영스팩4호,-131025000,0,1230484000,0,8611395000,9841878000
1996,A307280,교보8호스팩,-28370000,0,1062020000,0,6774388000,7836408000
1997,A307750,대신밸런스제6호스팩,-26859000,0,710480000,0,9613697000,10324178000
1998,A307870,골든브릿지이안5호,-2987000,0,898008000,0,8839206000,9737214000
1999,A307950,현대오토에버,55228435000,689503604000,377482748000,145535428000,451588443000,829071191000
2000,A309930,삼성머스트스팩3호,-7758000,0,696723000,0,8272471000,8969194000
2001,A310200,미래에셋대우스팩2호,-11654000,0,1163795000,0,5804306000,6968101000
2002,A310840,엔에이치스팩13호,-10869000,0,1407776000,0,6475928000,7883704000
2003,A310870,한국제8호스팩,-7076000,0,529500000,0,6350131000,6879631000
2004,A311270,키움제5호스팩,-130749000,0,769275000,0,7103863000,7873138000
2005,A313750,유안타제4호스팩,-13122000,0,1103143000,0,685353000,1788497000
2006,A316140,우리금융지주,0,0,0,0,0,0
2007,A317030,케이비17호스팩,0,0,0,0,0,0
2008,A317320,한화에스비아이스팩,0,0,0,0,0,0

In [6]:
corp_result.columns

Index(['종목코드', '회사명', '당기순이익', '유동자산', '부채총계', '매출총이익', '자본총계', '자산총계'], dtype='object')

In [7]:
corp_data = corp_result[['종목코드', '당기순이익']]
corp_data

         종목코드          당기순이익
0     A000020    10068113000
1     A000040   -24442080000
2     A000050    20189241000
3     A000060   234721346000
4     A000070   102512252000
5     A000080    22272353000
6     A000100    58334962000
7     A000120    51800069000
8     A000140     8640980000
9     A000150  -340510995000
10    A000180    -7933704000
11    A000210   678088774000
12    A000220     4312110000
13    A000230    -3831883000
14    A000240   218355604000
15    A000250    14592937000
16    A000270  1155943000000
17    A000300    19120849000
18    A000320     2664076000
19    A000370    81759590000
20    A000390      800759000
21    A000400    91314265000
22    A000430    23857286000
23    A000440      889990000
24    A000480    57955243000
25    A000490     1464262000
26    A000500       98902000
27    A000520    -8562748000
28    A000540    50441000000
29    A000590    12641149000
...       ...            ...
1979  A297570        -756000
1980  A298000    20394861000
1981  A298020    31498303000
1982  A298040     1908746000
1983  A298050   -23744728000
1984  A298380  -117234140000
1985  A298690    20294184000
1986  A299170      -25108000
1987  A299660   -11286321000
1988  A300720    53726823000
1989  A302430     5247720000
1990  A303030       -4049000
1991  A306200     7030156000
1992  A306620          33000
1993  A307070      -24500000
1994  A307160       -9884000
1995  A307180     -131025000
1996  A307280      -28370000
1997  A307750      -26859000
1998  A307870       -2987000
1999  A307950    55228435000
2000  A309930       -7758000
2001  A310200      -11654000
2002  A310840      -10869000
2003  A310870       -7076000
2004  A311270     -130749000
2005  A313750      -13122000
2006  A316140              0
2007  A317030              0
2008  A317320              0

[2009 rows x 2 columns]

In [8]:
corp_total = pd.merge(corp_info, corp_data, how='left', on='종목코드')
corp_total

         종목코드         종목명        현재가          상장주식수         당기순이익
0     A005930        삼성전자     46,100  5,969,782,550  4.434486e+13
1     A000660      SK하이닉스     77,000    728,002,365  1.553998e+13
2     A005935       삼성전자우     38,100    822,886,700           NaN
3     A005380         현대차    128,000    213,668,187  1.645019e+12
4     A051910        LG화학    333,000     70,592,343  1.519312e+12
5     A012330       현대모비스    242,500     95,306,694  1.888206e+12
6     A068270        셀트리온    179,000    128,329,070  2.535631e+11
7     A035420       NAVER    138,500    164,813,395  6.279019e+11
8     A055550        신한지주     43,900    474,199,587  3.198265e+12
9     A005490       POSCO    228,500     87,186,835  1.892064e+12
10    A017670       SK텔레콤    246,000     80,745,711  3.131988e+12
11    A051900      LG생활건강  1,240,000     15,618,197  6.922787e+11
12    A105560        KB금융     43,600    418,111,537  3.061946e+12
13    A207940    삼성바이오로직스    273,000     66,165,000  2.241092e+11
14    A015760        한국전력     27,950    641,964,077 -1.174498e+12
15    A028260        삼성물산     92,300    189,690,043  1.748244e+12
16    A000270         기아차     42,850    405,363,347  1.155943e+12
17    A018260     삼성에스디에스    212,000     77,377,800  6.387923e+11
18    A006400       삼성SDI    229,000     68,764,530  7.450492e+11
19    A096770     SK이노베이션    169,000     92,465,564  1.709984e+12
20    A034730          SK    221,500     70,360,297  6.151141e+12
21    A032830        삼성생명     77,000    200,000,000  1.733710e+12
22    A033780        KT&G     96,800    137,292,497  8.986593e+11
23    A003550          LG     73,300    172,557,131  1.882897e+12
24    A000810        삼성화재    262,500     47,374,837  1.073301e+12
25    A066570        LG전자     68,600    163,647,814  1.472814e+12
26    A035720         카카오    129,000     83,475,610  1.588886e+10
27    A036570       엔씨소프트    485,000     21,946,522  4.214677e+11
28    A086790      하나금융지주     35,100    300,242,062  2.275152e+12
29    A010950       S-Oil     91,700    112,582,792  2.580350e+11
...       ...         ...        ...            ...           ...
2375  A002785      진흥기업우B      5,190        857,218           NaN
2376  A005965       동부건설우     19,250        225,732           NaN
2377  A099350      하나니켈2호      1,305      3,284,000           NaN
2378  A001755       한양증권우      8,090        525,000           NaN
2379  A245450      씨앤에스링크      2,640      1,579,960           NaN
2380  A001065     JW중외제약우     24,800        167,375           NaN
2381  A271850        다이오진      1,375      3,000,000           NaN
2382  A000995     DB하이텍1우     36,050        112,316           NaN
2383  A002787     진흥기업2우B     13,500        294,808           NaN
2384  A084440         유비온      1,300      2,997,107           NaN
2385  A000545       흥국화재우      4,975        768,000           NaN
2386  A092590        럭스피아        517      7,291,098           NaN
2387  A001067   JW중외제약2우B     39,350         87,790           NaN
2388  A189350          코셋        835      4,000,000           NaN
2389  A149940          모다        155     21,160,409 -5.819454e+09
2390  A00781K   코리아써키트2우B      4,100        783,699           NaN
2391  A000325      노루홀딩스우     17,200        185,250           NaN
2392  A032685       소프트센우     22,000        142,857           NaN
2393  A227420    포레스팅블록체인        399      7,587,936           NaN
2394  A001527       동양2우B      9,810        308,569           NaN
2395  A000547     흥국화재2우B     19,200        153,600           NaN
2396  A000227     유유제약2우B     17,900        164,080           NaN
2397  A001799     대한제당3우B     21,500        129,656           NaN
2398  A223220      아이피몬스터        256     10,787,261           NaN
2399  A208890       에듀파트너      1,310      1,990,820           NaN
2400  A276240        엘리비젼        997      2,587,200           NaN
2401  A001529       동양3우B     27,600         89,722           NaN
2402  A247300  인프라웨어테크놀러지        370      6,118,198           NaN
2403  A224020     에스케이씨에스        830      2,700,000           NaN
2404  A135270     세종머티리얼즈        104      7,146,051           NaN

[2405 rows x 5 columns]

In [9]:
corp_total = corp_info.join(corp_data.set_index('종목코드'), how='outer', on='종목코드')
corp_total

         종목코드         종목명        현재가          상장주식수         당기순이익
0     A005930        삼성전자     46,100  5,969,782,550  4.434486e+13
1     A000660      SK하이닉스     77,000    728,002,365  1.553998e+13
2     A005935       삼성전자우     38,100    822,886,700           NaN
3     A005380         현대차    128,000    213,668,187  1.645019e+12
4     A051910        LG화학    333,000     70,592,343  1.519312e+12
5     A012330       현대모비스    242,500     95,306,694  1.888206e+12
6     A068270        셀트리온    179,000    128,329,070  2.535631e+11
7     A035420       NAVER    138,500    164,813,395  6.279019e+11
8     A055550        신한지주     43,900    474,199,587  3.198265e+12
9     A005490       POSCO    228,500     87,186,835  1.892064e+12
10    A017670       SK텔레콤    246,000     80,745,711  3.131988e+12
11    A051900      LG생활건강  1,240,000     15,618,197  6.922787e+11
12    A105560        KB금융     43,600    418,111,537  3.061946e+12
13    A207940    삼성바이오로직스    273,000     66,165,000  2.241092e+11
14    A015760        한국전력     27,950    641,964,077 -1.174498e+12
15    A028260        삼성물산     92,300    189,690,043  1.748244e+12
16    A000270         기아차     42,850    405,363,347  1.155943e+12
17    A018260     삼성에스디에스    212,000     77,377,800  6.387923e+11
18    A006400       삼성SDI    229,000     68,764,530  7.450492e+11
19    A096770     SK이노베이션    169,000     92,465,564  1.709984e+12
20    A034730          SK    221,500     70,360,297  6.151141e+12
21    A032830        삼성생명     77,000    200,000,000  1.733710e+12
22    A033780        KT&G     96,800    137,292,497  8.986593e+11
23    A003550          LG     73,300    172,557,131  1.882897e+12
24    A000810        삼성화재    262,500     47,374,837  1.073301e+12
25    A066570        LG전자     68,600    163,647,814  1.472814e+12
26    A035720         카카오    129,000     83,475,610  1.588886e+10
27    A036570       엔씨소프트    485,000     21,946,522  4.214677e+11
28    A086790      하나금융지주     35,100    300,242,062  2.275152e+12
29    A010950       S-Oil     91,700    112,582,792  2.580350e+11
...       ...         ...        ...            ...           ...
2378  A001755       한양증권우      8,090        525,000           NaN
2379  A245450      씨앤에스링크      2,640      1,579,960           NaN
2380  A001065     JW중외제약우     24,800        167,375           NaN
2381  A271850        다이오진      1,375      3,000,000           NaN
2382  A000995     DB하이텍1우     36,050        112,316           NaN
2383  A002787     진흥기업2우B     13,500        294,808           NaN
2384  A084440         유비온      1,300      2,997,107           NaN
2385  A000545       흥국화재우      4,975        768,000           NaN
2386  A092590        럭스피아        517      7,291,098           NaN
2387  A001067   JW중외제약2우B     39,350         87,790           NaN
2388  A189350          코셋        835      4,000,000           NaN
2389  A149940          모다        155     21,160,409 -5.819454e+09
2390  A00781K   코리아써키트2우B      4,100        783,699           NaN
2391  A000325      노루홀딩스우     17,200        185,250           NaN
2392  A032685       소프트센우     22,000        142,857           NaN
2393  A227420    포레스팅블록체인        399      7,587,936           NaN
2394  A001527       동양2우B      9,810        308,569           NaN
2395  A000547     흥국화재2우B     19,200        153,600           NaN
2396  A000227     유유제약2우B     17,900        164,080           NaN
2397  A001799     대한제당3우B     21,500        129,656           NaN
2398  A223220      아이피몬스터        256     10,787,261           NaN
2399  A208890       에듀파트너      1,310      1,990,820           NaN
2400  A276240        엘리비젼        997      2,587,200           NaN
2401  A001529       동양3우B     27,600         89,722           NaN
2402  A247300  인프라웨어테크놀러지        370      6,118,198           NaN
2403  A224020     에스케이씨에스        830      2,700,000           NaN
2404  A135270     세종머티리얼즈        104      7,146,051           NaN
2404  A002250         NaN        NaN            NaN  1.061487e+10
2404  A026180         NaN        NaN            NaN -6.188688e+09
2404  A079660         NaN        NaN            NaN  7.882205e+09

[2408 rows x 5 columns]

In [10]:
corp_total["EPS"] = corp_total['당기순이익']/corp_total['상장주식수'].str.replace(',','').astype('float')
corp_total

,종목코드,종목명,현재가,상장주식수,당기순이익,EPS
0,A005930,삼성전자,"46,100","5,969,782,550",4.434486e+13,7428.219810
1,A000660,SK하이닉스,"77,000","728,002,365",1.553998e+13,21346.062523
2,A005935,삼성전자우,"38,100","822,886,700",NaN,NaN
3,A005380,현대차,"128,000","213,668,187",1.645019e+12,7698.942098
4,A051910,LG화학,"333,000","70,592,343",1.519312e+12,21522.334228
5,A012330,현대모비스,"242,500","95,306,694",1.888206e+12,19811.892751
6,A068270,셀트리온,"179,000","128,329,070",2.535631e+11,1975.882090
7,A035420,NAVER,"138,500","164,813,395",6.279019e+11,3809.774521
8,A055550,신한지주,"43,900","474,199,587",3.198265e+12,6744.554588
9,A005490,POSCO,"228,500","87,186,835",1.892064e+12,21701.262650
10,A017670,SK텔레콤,"246,000","80,745,711",3.131988e+12,38788.289325
11,A051900,LG생활건강,"1,240,000","15,618,197",6.922787e+11,44325.135994
12,A105560,KB금융,"43,600","418,111,537",3.061946e+12,7323.275559
13,A207940,삼성바이오로직스,"273,000","66,165,000",2.241092e+11,3387.126049
14,A015760,한국전력,"27,950","641,964,077",-1.174498e+12,-1829.538509
15,A028260,삼성물산,"92,300","189,690,043",1.748244e+12,9216.316868
16,A000270,기아차,"42,850","405,363,347",1.155943e+12,2851.621906
17,A018260,삼성에스디에스,"212,000","77,377,800",6.387923e+11,8255.497804
18,A006400,삼성SDI,"229,000","68,764,530",7.450492e+11,10834.789171
19,A096770,SK이노베이션,"169,000","92,465,564",1.709984e+12,18493.198625
20,A034730,SK,"221,500","70,360,297",6.151141e+12,87423.465538
21,A032830,삼성생명,"77,000","200,000,000",1.733710e+12,8668.550000
22,A033780,KT&G,"96,800","137,292,497",8.986593e+11,6545.582312
23,A003550,LG,"73,300","172,557,131",1.882897e+12,10911.731025
24,A000810,삼성화재,"262,500","47,374,837",1.073301e+12,22655.512419
25,A066570,LG전자,"68,600","163,647,814",1.472814e+12,8999.900237
26,A035720,카카오,"129,000","83,475,610",1.588886e+10,190.341334
27,A036570,엔씨소프트,"485,000","21,946,522",4.214677e+11,19204.302668
28,A086790,하나금융지주,"35,100","300,242,062",2.275152e+12,7577.725735
29,A010950,S-Oil,"91,700","112,582,792",2.580350e+11,2291.957727
...,...,...,...,...,...,...
2378,A001755,한양증권우,"8,090","525,000",NaN,NaN
2379,A245450,씨앤에스링크,"2,640","1,579,960",NaN,NaN
2380,A001065,JW중외제약우,"24,800","167,375",NaN,NaN
2381,A271850,다이오진,"1,375","3,000,000",NaN,NaN
2382,A000995,DB하이텍1우,"36,050","112,316",NaN,NaN
2383,A002787,진흥기업2우B,"13,500","294,808",NaN,NaN
2384,A084440,유비온,"1,300","2,997,107",NaN,NaN
2385,A000545,흥국화재우,"4,975","768,000",NaN,NaN
2386,A092590,럭스피아,517,"7,291,098",NaN,NaN
2387,A001067,JW중외제약2우B,"39,350","87,790",NaN,NaN
2388,A189350,코셋,835,"4,000,000",NaN,NaN
2389,A149940,모다,155,"21,160,409",-5.819454e+09,-275.016140
2390,A00781K,코리아써키트2우B,"4,100","783,699",NaN,NaN
2391,A000325,노루홀딩스우,"17,200","185,250",NaN,NaN
2392,A032685,소프트센우,"22,000","142,857",NaN,NaN
2393,A227420,포레스팅블록체인,399,"7,587,936",NaN,NaN
2394,A001527,동양2우B,"9,810","308,569",NaN,NaN
2395,A000547,흥국화재2우B,"19,200","153,600",NaN,NaN
2396,A000227,유유제약2우B,"17,900","164,080",NaN,NaN
2397,A001799,대한제당3우B,"21,500","129,656",NaN,NaN
2398,A223220,아이피몬스터,256,"10,787,261",NaN,NaN
2399,A208890,에듀파트너,"1,310","1,990,820",NaN,NaN
2400,A276240,엘리비젼,997,"2,587,200",NaN,NaN
2401,A001529,동양3우B,"27,600","89,722",NaN,NaN
2402,A247300,인프라웨어테크놀러지,370,"6,118,198",NaN,NaN
2403,A224020,에스케이씨에스,830,"2,700,000",NaN,NaN
2404,A135270,세종머티리얼즈,104,"7,146,051",NaN,NaN
2404,A002250,NaN,NaN,NaN,1.061487e+10,NaN
2404,A026180,NaN,NaN,NaN,-6.188688e+09,NaN
2404,A079660,NaN,NaN,NaN,7.882205e+09,NaN

In [11]:
corp_total = corp_total[pd.notnull(corp_total['EPS'])]
corp_total = corp_total[pd.notnull(corp_total['현재가'])]
corp_total

,종목코드,종목명,현재가,상장주식수,당기순이익,EPS
0,A005930,삼성전자,"46,100","5,969,782,550",4.434486e+13,7428.219810
1,A000660,SK하이닉스,"77,000","728,002,365",1.553998e+13,21346.062523
3,A005380,현대차,"128,000","213,668,187",1.645019e+12,7698.942098
4,A051910,LG화학,"333,000","70,592,343",1.519312e+12,21522.334228
5,A012330,현대모비스,"242,500","95,306,694",1.888206e+12,19811.892751
6,A068270,셀트리온,"179,000","128,329,070",2.535631e+11,1975.882090
7,A035420,NAVER,"138,500","164,813,395",6.279019e+11,3809.774521
8,A055550,신한지주,"43,900","474,199,587",3.198265e+12,6744.554588
9,A005490,POSCO,"228,500","87,186,835",1.892064e+12,21701.262650
10,A017670,SK텔레콤,"246,000","80,745,711",3.131988e+12,38788.289325
11,A051900,LG생활건강,"1,240,000","15,618,197",6.922787e+11,44325.135994
12,A105560,KB금융,"43,600","418,111,537",3.061946e+12,7323.275559
13,A207940,삼성바이오로직스,"273,000","66,165,000",2.241092e+11,3387.126049
14,A015760,한국전력,"27,950","641,964,077",-1.174498e+12,-1829.538509
15,A028260,삼성물산,"92,300","189,690,043",1.748244e+12,9216.316868
16,A000270,기아차,"42,850","405,363,347",1.155943e+12,2851.621906
17,A018260,삼성에스디에스,"212,000","77,377,800",6.387923e+11,8255.497804
18,A006400,삼성SDI,"229,000","68,764,530",7.450492e+11,10834.789171
19,A096770,SK이노베이션,"169,000","92,465,564",1.709984e+12,18493.198625
20,A034730,SK,"221,500","70,360,297",6.151141e+12,87423.465538
21,A032830,삼성생명,"77,000","200,000,000",1.733710e+12,8668.550000
22,A033780,KT&G,"96,800","137,292,497",8.986593e+11,6545.582312
23,A003550,LG,"73,300","172,557,131",1.882897e+12,10911.731025
24,A000810,삼성화재,"262,500","47,374,837",1.073301e+12,22655.512419
25,A066570,LG전자,"68,600","163,647,814",1.472814e+12,8999.900237
26,A035720,카카오,"129,000","83,475,610",1.588886e+10,190.341334
27,A036570,엔씨소프트,"485,000","21,946,522",4.214677e+11,19204.302668
28,A086790,하나금융지주,"35,100","300,242,062",2.275152e+12,7577.725735
29,A010950,S-Oil,"91,700","112,582,792",2.580350e+11,2291.957727
30,A316140,우리금융지주,"13,150","680,164,306",0.000000e+00,0.000000
...,...,...,...,...,...,...
2277,A297570,IBKS제9호스팩,"3,755","2,760,000",-7.560000e+05,-0.273913
2278,A306620,DB금융스팩6호,"2,130","4,840,000",3.300000e+04,0.006818
2279,A307160,하나머스트제6호스팩,"2,220","4,590,000",-9.884000e+06,-2.153377
2282,A192410,감마누,408,"24,435,800",-4.702885e+09,-192.458810
2283,A307870,상상인이안1호스팩,"2,090","4,750,000",-2.987000e+06,-0.628842
2285,A270520,하나금융10호스팩,"2,150","4,602,000",4.712000e+07,10.239027
2286,A299170,IBKS제10호스팩,"2,285","4,330,000",-2.510800e+07,-5.798614
2288,A309930,삼성머스트스팩3호,"2,150","4,590,000",-7.758000e+06,-1.690196
2289,A281410,한국제6호스팩,"2,175","4,510,000",7.963100e+07,17.656541
2290,A313750,유안타제4호스팩,"2,095","4,650,000",-1.312200e+07,-2.821935
2291,A267320,교보7호스팩,"2,420","4,020,000",1.833500e+07,4.560945
2292,A083470,KJ프리텍,387,"24,704,729",-3.470981e+10,-1404.986592
2296,A265920,한화수성스팩,"2,120","4,440,000",8.441600e+07,19.012613
2297,A307180,신영스팩4호,"2,150","4,355,000",-1.310250e+08,-30.086108
2299,A261200,하나금융9호스팩,"2,160","4,260,000",7.599000e+07,17.838028
2302,A287410,유안타제3호스팩,"2,145","4,235,000",-3.864000e+06,-0.912397
2306,A271740,한국제5호스팩,"2,200","4,000,000",3.317000e+07,8.292500
2310,A276920,IBKS제7호스팩,"2,285","3,650,000",5.246200e+07,14.373151
2314,A307280,교보8호스팩,"2,180","3,720,000",-2.837000e+07,-7.626344
2320,A257730,신한제3호스팩,"2,260","3,505,000",4.247500e+07,12.118402
2322,A311270,키움제5호스팩,"2,175","3,600,000",-1.307490e+08,-36.319167
2326,A030270,에스마크,998,"7,562,701",-3.449569e+10,-4561.292718
2330,A310200,미래에셋대우스팩2호,"2,465","3,050,000",-1.165400e+07,-3.820984
2331,A279410,한화에이스스팩4호,"2,135","3,495,000",2.237200e+07,6.401144
2332,A258790,케이비제11호스팩,"2,315","3,210,000",1.981400e+07,6.172586
2333,A232330,SK3호스팩,"2,060","3,600,000",6.439600e+07,17.887778
2336,A310840,엔에이치스팩13호,"2,150","3,420,000",-1.086900e+07,-3.178070
2338,A310870,한국제8호스팩,"2,135","3,420,000",-7.076000e+06,-2.069006
2342,A264290,한화에이스스팩3호,"2,295","3,080,000",1.645700e+07,5.343182
2389,A149940,모다,155,"21,160,409",-5.819454e+09,-275.016140

In [12]:
corp_total["PER"] = corp_total["현재가"].str.replace(",","").astype('int')/corp_total["EPS"]
corp_total

,종목코드,종목명,현재가,상장주식수,당기순이익,EPS,PER
0,A005930,삼성전자,"46,100","5,969,782,550",4.434486e+13,7428.219810,6.206063e+00
1,A000660,SK하이닉스,"77,000","728,002,365",1.553998e+13,21346.062523,3.607223e+00
3,A005380,현대차,"128,000","213,668,187",1.645019e+12,7698.942098,1.662566e+01
4,A051910,LG화학,"333,000","70,592,343",1.519312e+12,21522.334228,1.547230e+01
5,A012330,현대모비스,"242,500","95,306,694",1.888206e+12,19811.892751,1.224012e+01
6,A068270,셀트리온,"179,000","128,329,070",2.535631e+11,1975.882090,9.059245e+01
7,A035420,NAVER,"138,500","164,813,395",6.279019e+11,3809.774521,3.635386e+01
8,A055550,신한지주,"43,900","474,199,587",3.198265e+12,6744.554588,6.508955e+00
9,A005490,POSCO,"228,500","87,186,835",1.892064e+12,21701.262650,1.052934e+01
10,A017670,SK텔레콤,"246,000","80,745,711",3.131988e+12,38788.289325,6.342120e+00
11,A051900,LG생활건강,"1,240,000","15,618,197",6.922787e+11,44325.135994,2.797510e+01
12,A105560,KB금융,"43,600","418,111,537",3.061946e+12,7323.275559,5.953620e+00
13,A207940,삼성바이오로직스,"273,000","66,165,000",2.241092e+11,3387.126049,8.059930e+01
14,A015760,한국전력,"27,950","641,964,077",-1.174498e+12,-1829.538509,-1.527708e+01
15,A028260,삼성물산,"92,300","189,690,043",1.748244e+12,9216.316868,1.001485e+01
16,A000270,기아차,"42,850","405,363,347",1.155943e+12,2851.621906,1.502654e+01
17,A018260,삼성에스디에스,"212,000","77,377,800",6.387923e+11,8255.497804,2.567986e+01
18,A006400,삼성SDI,"229,000","68,764,530",7.450492e+11,10834.789171,2.113562e+01
19,A096770,SK이노베이션,"169,000","92,465,564",1.709984e+12,18493.198625,9.138495e+00
20,A034730,SK,"221,500","70,360,297",6.151141e+12,87423.465538,2.533645e+00
21,A032830,삼성생명,"77,000","200,000,000",1.733710e+12,8668.550000,8.882685e+00
22,A033780,KT&G,"96,800","137,292,497",8.986593e+11,6545.582312,1.478860e+01
23,A003550,LG,"73,300","172,557,131",1.882897e+12,10911.731025,6.717541e+00
24,A000810,삼성화재,"262,500","47,374,837",1.073301e+12,22655.512419,1.158658e+01
25,A066570,LG전자,"68,600","163,647,814",1.472814e+12,8999.900237,7.622307e+00
26,A035720,카카오,"129,000","83,475,610",1.588886e+10,190.341334,6.777298e+02
27,A036570,엔씨소프트,"485,000","21,946,522",4.214677e+11,19204.302668,2.525476e+01
28,A086790,하나금융지주,"35,100","300,242,062",2.275152e+12,7577.725735,4.631997e+00
29,A010950,S-Oil,"91,700","112,582,792",2.580350e+11,2291.957727,4.000946e+01
30,A316140,우리금융지주,"13,150","680,164,306",0.000000e+00,0.000000,inf
...,...,...,...,...,...,...,...
2277,A297570,IBKS제9호스팩,"3,755","2,760,000",-7.560000e+05,-0.273913,-1.370873e+04
2278,A306620,DB금융스팩6호,"2,130","4,840,000",3.300000e+04,0.006818,3.124000e+05
2279,A307160,하나머스트제6호스팩,"2,220","4,590,000",-9.884000e+06,-2.153377,-1.030939e+03
2282,A192410,감마누,408,"24,435,800",-4.702885e+09,-192.458810,-2.119934e+00
2283,A307870,상상인이안1호스팩,"2,090","4,750,000",-2.987000e+06,-0.628842,-3.323569e+03
2285,A270520,하나금융10호스팩,"2,150","4,602,000",4.712000e+07,10.239027,2.099809e+02
2286,A299170,IBKS제10호스팩,"2,285","4,330,000",-2.510800e+07,-5.798614,-3.940597e+02
2288,A309930,삼성머스트스팩3호,"2,150","4,590,000",-7.758000e+06,-1.690196,-1.272042e+03
2289,A281410,한국제6호스팩,"2,175","4,510,000",7.963100e+07,17.656541,1.231838e+02
2290,A313750,유안타제4호스팩,"2,095","4,650,000",-1.312200e+07,-2.821935,-7.423983e+02
2291,A267320,교보7호스팩,"2,420","4,020,000",1.833500e+07,4.560945,5.305918e+02
2292,A083470,KJ프리텍,387,"24,704,729",-3.470981e+10,-1404.986592,-2.754475e-01
2296,A265920,한화수성스팩,"2,120","4,440,000",8.441600e+07,19.012613,1.115049e+02
2297,A307180,신영스팩4호,"2,150","4,355,000",-1.310250e+08,-30.086108,-7.146155e+01
2299,A261200,하나금융9호스팩,"2,160","4,260,000",7.599000e+07,17.838028,1.210896e+02
2302,A287410,유안타제3호스팩,"2,145","4,235,000",-3.864000e+06,-0.912397,-2.350951e+03
2306,A271740,한국제5호스팩,"2,200","4,000,000",3.317000e+07,8.292500,2.653000e+02
2310,A276920,IBKS제7호스팩,"2,285","3,650,000",5.246200e+07,14.373151,1.589770e+02
2314,A307280,교보8호스팩,"2,180","3,720,000",-2.837000e+07,-7.626344,-2.858513e+02
2320,A257730,신한제3호스팩,"2,260","3,505,000",4.247500e+07,12.118402,1.864932e+02
2322,A311270,키움제5호스팩,"2,175","3,600,000",-1.307490e+08,-36.319167,-5.988574e+01
2326,A030270,에스마크,998,"7,562,701",-3.449569e+10,-4561.292718,-2.187976e-01
2330,A310200,미래에셋대우스팩2호,"2,465","3,050,000",-1.165400e+07,-3.820984,-6.451218e+02
2331,A279410,한화에이스스팩4호,"2,135","3,495,000",2.237200e+07,6.401144,3.335341e+02
2332,A258790,케이비제11호스팩,"2,315","3,210,000",1.981400e+07,6.172586,3.750454e+02
2333,A232330,SK3호스팩,"2,060","3,600,000",6.439600e+07,17.887778,1.151624e+02
2336,A310840,엔에이치스팩13호,"2,150","3,420,000",-1.086900e+07,-3.178070,-6.765112e+02
2338,A310870,한국제8호스팩,"2,135","3,420,000",-7.076000e+06,-2.069006,-1.031897e+03
2342,A264290,한화에이스스팩3호,"2,295","3,080,000",1.645700e+07,5.343182,4.295194e+02
2389,A149940,모다,155,"21,160,409",-5.819454e+09,-275.016140,-5.636033e-01

In [13]:
corp_filter = corp_total[(corp_total["PER"]>=12) & (corp_total["PER"]<=15)]
corp_filter

,종목코드,종목명,현재가,상장주식수,당기순이익,EPS,PER
5,A012330,현대모비스,"242,500","95,306,694",1.888206e+12,19811.892751,12.240123
22,A033780,KT&G,"96,800","137,292,497",8.986593e+11,6545.582312,14.788600
43,A086280,현대글로비스,"154,000","37,500,000",4.373734e+11,11663.289973,13.203822
47,A004020,현대제철,"38,900","133,445,785",4.079594e+11,3057.117428,12.724405
49,A002790,아모레G,"58,300","82,458,180",3.762712e+11,4563.176291,12.776188
66,A241560,두산밥캣,"35,900","100,249,166",2.644972e+11,2638.397700,13.606743
100,A007310,오뚜기,"649,000","3,605,237",1.608291e+11,44609.865315,14.548351
105,A263750,펄어비스,"165,400","13,021,400",1.464462e+11,11246.576943,14.706697
115,A026960,동서,"17,600","99,700,000",1.203970e+11,1207.592347,14.574455
119,A010620,현대미포조선,"42,600","39,942,149",1.206554e+11,3020.754692,14.102436
128,A204320,만도,"33,400","46,957,120",1.129276e+11,2404.909692,13.888255
132,A111770,영원무역,"33,850","44,311,468",1.112852e+11,2511.430359,13.478375
142,A009240,한샘,"57,000","23,533,928",8.995704e+10,3822.440393,14.911940
147,A214320,이노션,"65,300","20,000,000",9.238177e+10,4619.088400,14.136989
164,A240810,원익IPS,"23,200","49,083,901",8.686039e+10,1769.630922,13.110078
169,A114090,GKL,"18,050","61,855,670",7.774063e+10,1256.806854,14.361793
195,A046890,서울반도체,"15,800","58,305,400",6.260134e+10,1073.679951,14.715745
199,A014680,한솔케미칼,"80,000","11,295,195",6.775574e+10,5998.633490,13.336371
206,A018250,애경산업,"32,400","26,346,535",6.078920e+10,2307.293767,14.042425
216,A001680,대상,"23,500","34,648,025",6.539847e+10,1887.509375,12.450269
238,A200130,콜마비앤에이치,"24,100","29,543,558",4.932240e+10,1669.480602,14.435627
245,A064960,S&T모티브,"47,400","14,623,136",5.722514e+10,3913.329193,12.112449
248,A018670,SK가스,"75,300","9,141,781",5.543844e+10,6064.293489,12.416945
256,A064760,티씨케이,"56,400","11,675,000",4.685695e+10,4013.443426,14.052771
263,A108320,실리콘웍스,"38,650","16,264,300",4.896045e+10,3010.301888,12.839244
271,A027410,BGF,"6,310","95,716,791",4.720482e+10,493.171788,12.794730
272,A086450,동국제약,"67,800","8,892,000",4.943317e+10,5559.285538,12.195812
287,A002270,롯데푸드,"497,500","1,131,870",4.254009e+10,37583.897444,13.237052
320,A003230,삼양식품,"63,500","7,533,015",3.530453e+10,4686.640210,13.549152
322,A010050,우리종금,703,"674,203,406",3.336401e+10,49.486564,14.205876
...,...,...,...,...,...,...,...
1516,A019180,티에이치엔,"3,720","18,000,000",4.772684e+09,265.149111,14.029841
1528,A114810,아이원스,"4,925","13,415,919",5.339651e+09,398.008590,12.374105
1538,A083550,케이엠,"6,460","10,142,170",4.578031e+09,451.385749,14.311484
1546,A033310,디케이디앤아이,"2,965","21,972,411",4.406555e+09,200.549453,14.784383
1564,A123570,이엠넷,"2,870","22,276,078",4.500362e+09,202.026676,14.206045
1569,A000220,유유제약,"9,970","6,368,587",4.312110e+09,677.090538,14.724766
1595,A101240,씨큐브,"7,680","8,050,441",4.504161e+09,559.492455,13.726727
1611,A048430,유라테크,"5,260","11,520,000",4.479801e+09,388.871615,13.526315
1660,A037440,희림,"4,040","13,922,475",3.957145e+09,284.227122,14.213985
1681,A024840,KBI메탈,"1,675","32,950,848",4.400083e+09,133.534742,12.543552
1705,A048770,TPC,"4,150","12,900,000",4.147039e+09,321.475891,12.909211
1707,A065770,CS,"2,840","18,835,150",4.097741e+09,217.558182,13.053979
1731,A051490,나라엠앤디,"3,670","14,200,000",3.744173e+09,263.674155,13.918694
1753,A064820,케이프,"1,975","25,528,573",4.176501e+09,163.601036,12.072051
1759,A092870,엑시콘,"5,650","8,883,500",3.711680e+09,417.817302,13.522657
1772,A123700,SJM,"3,155","15,604,898",3.726141e+09,238.780221,13.212987
1790,A265560,영화테크,"9,020","5,345,090",3.898865e+09,729.429252,12.365833
1846,A008470,부스타,"5,310","8,404,800",2.987173e+09,355.412740,14.940376
1866,A050960,수산아이앤티,"6,410","6,751,000",3.120145e+09,462.175233,13.869198
1868,A085910,네오티스,"3,910","11,013,678",3.178419e+09,288.588335,13.548711
1877,A083500,에프엔에스테크,"5,700","7,425,062",3.207393e+09,431.968514,13.195406
1897,A007770,한일화학,"11,800","3,510,000",2.843593e+09,810.140456,14.565376
1898,A005320,국동,"1,500","27,596,156",2.956053e+09,107.118289,14.003211
1929,A104040,대성파인텍,"1,270","31,301,281",2.982309e+09,95.277538,13.329480
1935,A079000,와토스코리아,"5,440","7,200,000",2.902873e+09,403.176806,13.492840
1973,A131220,대한과학,"5,010","7,454,490",2.516975e+09,337.645500,14.838048
2002,A109080,옵티시스,"6,330","5,636,000",2.771172e+09,491.691270,12.873932
2026,A053160,프리엠스,"5,660","6,000,000",2.306497e+09,384.416167,14.723626
2028,A032280,삼일,"2,090","16,213,590",2.573956e+09,158.752997,13.165106
2069,A173130,오파스넷,"7,570","4,025,902",2.289021e+09,568.573453,13.314023

In [14]:
corp_total.query('PER >=12 & PER <=15')

,종목코드,종목명,현재가,상장주식수,당기순이익,EPS,PER
5,A012330,현대모비스,"242,500","95,306,694",1.888206e+12,19811.892751,12.240123
22,A033780,KT&G,"96,800","137,292,497",8.986593e+11,6545.582312,14.788600
43,A086280,현대글로비스,"154,000","37,500,000",4.373734e+11,11663.289973,13.203822
47,A004020,현대제철,"38,900","133,445,785",4.079594e+11,3057.117428,12.724405
49,A002790,아모레G,"58,300","82,458,180",3.762712e+11,4563.176291,12.776188
66,A241560,두산밥캣,"35,900","100,249,166",2.644972e+11,2638.397700,13.606743
100,A007310,오뚜기,"649,000","3,605,237",1.608291e+11,44609.865315,14.548351
105,A263750,펄어비스,"165,400","13,021,400",1.464462e+11,11246.576943,14.706697
115,A026960,동서,"17,600","99,700,000",1.203970e+11,1207.592347,14.574455
119,A010620,현대미포조선,"42,600","39,942,149",1.206554e+11,3020.754692,14.102436
128,A204320,만도,"33,400","46,957,120",1.129276e+11,2404.909692,13.888255
132,A111770,영원무역,"33,850","44,311,468",1.112852e+11,2511.430359,13.478375
142,A009240,한샘,"57,000","23,533,928",8.995704e+10,3822.440393,14.911940
147,A214320,이노션,"65,300","20,000,000",9.238177e+10,4619.088400,14.136989
164,A240810,원익IPS,"23,200","49,083,901",8.686039e+10,1769.630922,13.110078
169,A114090,GKL,"18,050","61,855,670",7.774063e+10,1256.806854,14.361793
195,A046890,서울반도체,"15,800","58,305,400",6.260134e+10,1073.679951,14.715745
199,A014680,한솔케미칼,"80,000","11,295,195",6.775574e+10,5998.633490,13.336371
206,A018250,애경산업,"32,400","26,346,535",6.078920e+10,2307.293767,14.042425
216,A001680,대상,"23,500","34,648,025",6.539847e+10,1887.509375,12.450269
238,A200130,콜마비앤에이치,"24,100","29,543,558",4.932240e+10,1669.480602,14.435627
245,A064960,S&T모티브,"47,400","14,623,136",5.722514e+10,3913.329193,12.112449
248,A018670,SK가스,"75,300","9,141,781",5.543844e+10,6064.293489,12.416945
256,A064760,티씨케이,"56,400","11,675,000",4.685695e+10,4013.443426,14.052771
263,A108320,실리콘웍스,"38,650","16,264,300",4.896045e+10,3010.301888,12.839244
271,A027410,BGF,"6,310","95,716,791",4.720482e+10,493.171788,12.794730
272,A086450,동국제약,"67,800","8,892,000",4.943317e+10,5559.285538,12.195812
287,A002270,롯데푸드,"497,500","1,131,870",4.254009e+10,37583.897444,13.237052
320,A003230,삼양식품,"63,500","7,533,015",3.530453e+10,4686.640210,13.549152
322,A010050,우리종금,703,"674,203,406",3.336401e+10,49.486564,14.205876
...,...,...,...,...,...,...,...
1516,A019180,티에이치엔,"3,720","18,000,000",4.772684e+09,265.149111,14.029841
1528,A114810,아이원스,"4,925","13,415,919",5.339651e+09,398.008590,12.374105
1538,A083550,케이엠,"6,460","10,142,170",4.578031e+09,451.385749,14.311484
1546,A033310,디케이디앤아이,"2,965","21,972,411",4.406555e+09,200.549453,14.784383
1564,A123570,이엠넷,"2,870","22,276,078",4.500362e+09,202.026676,14.206045
1569,A000220,유유제약,"9,970","6,368,587",4.312110e+09,677.090538,14.724766
1595,A101240,씨큐브,"7,680","8,050,441",4.504161e+09,559.492455,13.726727
1611,A048430,유라테크,"5,260","11,520,000",4.479801e+09,388.871615,13.526315
1660,A037440,희림,"4,040","13,922,475",3.957145e+09,284.227122,14.213985
1681,A024840,KBI메탈,"1,675","32,950,848",4.400083e+09,133.534742,12.543552
1705,A048770,TPC,"4,150","12,900,000",4.147039e+09,321.475891,12.909211
1707,A065770,CS,"2,840","18,835,150",4.097741e+09,217.558182,13.053979
1731,A051490,나라엠앤디,"3,670","14,200,000",3.744173e+09,263.674155,13.918694
1753,A064820,케이프,"1,975","25,528,573",4.176501e+09,163.601036,12.072051
1759,A092870,엑시콘,"5,650","8,883,500",3.711680e+09,417.817302,13.522657
1772,A123700,SJM,"3,155","15,604,898",3.726141e+09,238.780221,13.212987
1790,A265560,영화테크,"9,020","5,345,090",3.898865e+09,729.429252,12.365833
1846,A008470,부스타,"5,310","8,404,800",2.987173e+09,355.412740,14.940376
1866,A050960,수산아이앤티,"6,410","6,751,000",3.120145e+09,462.175233,13.869198
1868,A085910,네오티스,"3,910","11,013,678",3.178419e+09,288.588335,13.548711
1877,A083500,에프엔에스테크,"5,700","7,425,062",3.207393e+09,431.968514,13.195406
1897,A007770,한일화학,"11,800","3,510,000",2.843593e+09,810.140456,14.565376
1898,A005320,국동,"1,500","27,596,156",2.956053e+09,107.118289,14.003211
1929,A104040,대성파인텍,"1,270","31,301,281",2.982309e+09,95.277538,13.329480
1935,A079000,와토스코리아,"5,440","7,200,000",2.902873e+09,403.176806,13.492840
1973,A131220,대한과학,"5,010","7,454,490",2.516975e+09,337.645500,14.838048
2002,A109080,옵티시스,"6,330","5,636,000",2.771172e+09,491.691270,12.873932
2026,A053160,프리엠스,"5,660","6,000,000",2.306497e+09,384.416167,14.723626
2028,A032280,삼일,"2,090","16,213,590",2.573956e+09,158.752997,13.165106
2069,A173130,오파스넷,"7,570","4,025,902",2.289021e+09,568.573453,13.314023

In [15]:
corp_filter.sort_values(by='PER')

,종목코드,종목명,현재가,상장주식수,당기순이익,EPS,PER
412,A008490,서흥,"30,600","11,569,113",2.938418e+10,2539.882012,12.047804
408,A097520,엠씨넥스,"20,250","17,745,456",2.981801e+10,1680.317823,12.051292
1753,A064820,케이프,"1,975","25,528,573",4.176501e+09,163.601036,12.072051
245,A064960,S&T모티브,"47,400","14,623,136",5.722514e+10,3913.329193,12.112449
420,A003800,에이스침대,"31,350","11,090,000",2.868884e+10,2586.910640,12.118702
272,A086450,동국제약,"67,800","8,892,000",4.943317e+10,5559.285538,12.195812
1360,A008250,이건산업,"7,250","10,952,635",6.510008e+09,594.378248,12.197620
553,A084370,유진테크,"11,050","22,916,042",2.068889e+10,902.812362,12.239531
5,A012330,현대모비스,"242,500","95,306,694",1.888206e+12,19811.892751,12.240123
463,A008350,남선알미늄,"2,810","110,179,090",2.522052e+10,228.904768,12.275847
911,A003650,미창석유,"76,000","1,739,672",1.072219e+10,6163.341710,12.330973
407,A043150,바텍,"24,250","14,854,256",2.915201e+10,1962.535922,12.356462
1790,A265560,영화테크,"9,020","5,345,090",3.898865e+09,729.429252,12.365833
498,A003220,대원제약,"14,650","19,662,677",2.328629e+10,1184.288742,12.370294
1528,A114810,아이원스,"4,925","13,415,919",5.339651e+09,398.008590,12.374105
1343,A031820,콤텍시스템,"1,695","47,851,466",6.553668e+09,136.958563,12.376006
248,A018670,SK가스,"75,300","9,141,781",5.543844e+10,6064.293489,12.416945
536,A010170,대한광통신,"3,585","73,741,625",2.128204e+10,288.602767,12.421918
1376,A006660,삼성공조,"9,700","8,126,314",6.332359e+09,779.241240,12.448006
216,A001680,대상,"23,500","34,648,025",6.539847e+10,1887.509375,12.450269
344,A029530,신도리코,"43,550","10,080,029",3.503411e+10,3475.596350,12.530224
585,A079980,휴비스,"6,900","34,500,000",1.899182e+10,550.487536,12.534344
1681,A024840,KBI메탈,"1,675","32,950,848",4.400083e+09,133.534742,12.543552
447,A080420,모다이노칩,"4,070","79,721,622",2.566002e+10,321.870333,12.644844
733,A001530,DI동일,"72,500","2,421,420",1.382487e+10,5709.406877,12.698342
451,A265520,AP시스템,"22,750","14,099,511",2.522701e+10,1789.211839,12.715096
47,A004020,현대제철,"38,900","133,445,785",4.079594e+11,3057.117428,12.724405
1460,A014440,영보화학,"3,600","20,000,000",5.657471e+09,282.873550,12.726535
1186,A075180,새론오토모티브,"4,900","19,200,000",7.392147e+09,385.007656,12.727020
999,A130580,나이스디앤비,"7,690","15,400,000",9.299592e+09,603.869610,12.734537
...,...,...,...,...,...,...,...
388,A023410,유진기업,"4,950","77,310,863",2.658165e+10,343.828189,14.396725
238,A200130,콜마비앤에이치,"24,100","29,543,558",4.932240e+10,1669.480602,14.435627
363,A011280,태림포장,"5,860","70,805,940",2.867665e+10,405.003493,14.469011
647,A003070,코오롱글로벌,"8,300","25,210,438",1.445116e+10,573.221298,14.479574
732,A046440,KG모빌리언스,"5,880","29,906,957",1.211927e+10,405.232334,14.510195
919,A067900,와이엔텍,"7,210","18,199,659",9.033205e+09,496.339245,14.526355
422,A047310,파워로직스,"10,100","34,420,982",2.392837e+10,695.168226,14.528857
100,A007310,오뚜기,"649,000","3,605,237",1.608291e+11,44609.865315,14.548351
1897,A007770,한일화학,"11,800","3,510,000",2.843593e+09,810.140456,14.565376
115,A026960,동서,"17,600","99,700,000",1.203970e+11,1207.592347,14.574455
1214,A205100,엑셈,"2,700","33,882,273",6.275021e+09,185.200710,14.578778
1425,A002920,유성기업,"2,865","25,947,500",5.092468e+09,196.260449,14.597949
383,A293480,하나제약,"23,750","16,200,000",2.616907e+10,1615.374938,14.702469
105,A263750,펄어비스,"165,400","13,021,400",1.464462e+11,11246.576943,14.706697
610,A082920,비츠로셀,"10,500","21,539,152",1.537186e+10,713.670761,14.712667
195,A046890,서울반도체,"15,800","58,305,400",6.260134e+10,1073.679951,14.715745
548,A067280,멀티캠퍼스,"43,600","5,926,779",1.755218e+10,2961.503204,14.722253
2026,A053160,프리엠스,"5,660","6,000,000",2.306497e+09,384.416167,14.723626
1569,A000220,유유제약,"9,970","6,368,587",4.312110e+09,677.090538,14.724766
1546,A033310,디케이디앤아이,"2,965","21,972,411",4.406555e+09,200.549453,14.784383
22,A033780,KT&G,"96,800","137,292,497",8.986593e+11,6545.582312,14.788600
1973,A131220,대한과학,"5,010","7,454,490",2.516975e+09,337.645500,14.838048
848,A214430,아이쓰리시스템,"20,450","7,106,760",9.784710e+09,1376.817284,14.853097
826,A100700,세운메디칼,"3,420","43,800,000",1.007516e+10,230.026553,14.867849
1213,A007590,동방아그로,"6,720","13,617,577",6.154336e+09,451.940606,14.869210
142,A009240,한샘,"57,000","23,533,928",8.995704e+10,3822.440393,14.911940
1094,A063170,서울옥션,"6,250","16,917,500",7.084634e+09,418.775469,14.924465
1846,A008470,부스타,"5,310","8,404,800",2.987173e+09,355.412740,14.940376
1453,A126600,코프라,"3,430","21,115,634",4.842683e+09,229.341113,14.955888
952,A204620,글로벌텍스프리,"3,360","37,254,218",8.365701e+09,224.557149,14.962783

In [16]:
corp_filter.sort_values(by='PER', ascending=False)

,종목코드,종목명,현재가,상장주식수,당기순이익,EPS,PER
952,A204620,글로벌텍스프리,"3,360","37,254,218",8.365701e+09,224.557149,14.962783
1453,A126600,코프라,"3,430","21,115,634",4.842683e+09,229.341113,14.955888
1846,A008470,부스타,"5,310","8,404,800",2.987173e+09,355.412740,14.940376
1094,A063170,서울옥션,"6,250","16,917,500",7.084634e+09,418.775469,14.924465
142,A009240,한샘,"57,000","23,533,928",8.995704e+10,3822.440393,14.911940
1213,A007590,동방아그로,"6,720","13,617,577",6.154336e+09,451.940606,14.869210
826,A100700,세운메디칼,"3,420","43,800,000",1.007516e+10,230.026553,14.867849
848,A214430,아이쓰리시스템,"20,450","7,106,760",9.784710e+09,1376.817284,14.853097
1973,A131220,대한과학,"5,010","7,454,490",2.516975e+09,337.645500,14.838048
22,A033780,KT&G,"96,800","137,292,497",8.986593e+11,6545.582312,14.788600
1546,A033310,디케이디앤아이,"2,965","21,972,411",4.406555e+09,200.549453,14.784383
1569,A000220,유유제약,"9,970","6,368,587",4.312110e+09,677.090538,14.724766
2026,A053160,프리엠스,"5,660","6,000,000",2.306497e+09,384.416167,14.723626
548,A067280,멀티캠퍼스,"43,600","5,926,779",1.755218e+10,2961.503204,14.722253
195,A046890,서울반도체,"15,800","58,305,400",6.260134e+10,1073.679951,14.715745
610,A082920,비츠로셀,"10,500","21,539,152",1.537186e+10,713.670761,14.712667
105,A263750,펄어비스,"165,400","13,021,400",1.464462e+11,11246.576943,14.706697
383,A293480,하나제약,"23,750","16,200,000",2.616907e+10,1615.374938,14.702469
1425,A002920,유성기업,"2,865","25,947,500",5.092468e+09,196.260449,14.597949
1214,A205100,엑셈,"2,700","33,882,273",6.275021e+09,185.200710,14.578778
115,A026960,동서,"17,600","99,700,000",1.203970e+11,1207.592347,14.574455
1897,A007770,한일화학,"11,800","3,510,000",2.843593e+09,810.140456,14.565376
100,A007310,오뚜기,"649,000","3,605,237",1.608291e+11,44609.865315,14.548351
422,A047310,파워로직스,"10,100","34,420,982",2.392837e+10,695.168226,14.528857
919,A067900,와이엔텍,"7,210","18,199,659",9.033205e+09,496.339245,14.526355
732,A046440,KG모빌리언스,"5,880","29,906,957",1.211927e+10,405.232334,14.510195
647,A003070,코오롱글로벌,"8,300","25,210,438",1.445116e+10,573.221298,14.479574
363,A011280,태림포장,"5,860","70,805,940",2.867665e+10,405.003493,14.469011
238,A200130,콜마비앤에이치,"24,100","29,543,558",4.932240e+10,1669.480602,14.435627
388,A023410,유진기업,"4,950","77,310,863",2.658165e+10,343.828189,14.396725
...,...,...,...,...,...,...,...
999,A130580,나이스디앤비,"7,690","15,400,000",9.299592e+09,603.869610,12.734537
1186,A075180,새론오토모티브,"4,900","19,200,000",7.392147e+09,385.007656,12.727020
1460,A014440,영보화학,"3,600","20,000,000",5.657471e+09,282.873550,12.726535
47,A004020,현대제철,"38,900","133,445,785",4.079594e+11,3057.117428,12.724405
451,A265520,AP시스템,"22,750","14,099,511",2.522701e+10,1789.211839,12.715096
733,A001530,DI동일,"72,500","2,421,420",1.382487e+10,5709.406877,12.698342
447,A080420,모다이노칩,"4,070","79,721,622",2.566002e+10,321.870333,12.644844
1681,A024840,KBI메탈,"1,675","32,950,848",4.400083e+09,133.534742,12.543552
585,A079980,휴비스,"6,900","34,500,000",1.899182e+10,550.487536,12.534344
344,A029530,신도리코,"43,550","10,080,029",3.503411e+10,3475.596350,12.530224
216,A001680,대상,"23,500","34,648,025",6.539847e+10,1887.509375,12.450269
1376,A006660,삼성공조,"9,700","8,126,314",6.332359e+09,779.241240,12.448006
536,A010170,대한광통신,"3,585","73,741,625",2.128204e+10,288.602767,12.421918
248,A018670,SK가스,"75,300","9,141,781",5.543844e+10,6064.293489,12.416945
1343,A031820,콤텍시스템,"1,695","47,851,466",6.553668e+09,136.958563,12.376006
1528,A114810,아이원스,"4,925","13,415,919",5.339651e+09,398.008590,12.374105
498,A003220,대원제약,"14,650","19,662,677",2.328629e+10,1184.288742,12.370294
1790,A265560,영화테크,"9,020","5,345,090",3.898865e+09,729.429252,12.365833
407,A043150,바텍,"24,250","14,854,256",2.915201e+10,1962.535922,12.356462
911,A003650,미창석유,"76,000","1,739,672",1.072219e+10,6163.341710,12.330973
463,A008350,남선알미늄,"2,810","110,179,090",2.522052e+10,228.904768,12.275847
5,A012330,현대모비스,"242,500","95,306,694",1.888206e+12,19811.892751,12.240123
553,A084370,유진테크,"11,050","22,916,042",2.068889e+10,902.812362,12.239531
1360,A008250,이건산업,"7,250","10,952,635",6.510008e+09,594.378248,12.197620
272,A086450,동국제약,"67,800","8,892,000",4.943317e+10,5559.285538,12.195812
420,A003800,에이스침대,"31,350","11,090,000",2.868884e+10,2586.910640,12.118702
245,A064960,S&T모티브,"47,400","14,623,136",5.722514e+10,3913.329193,12.112449
1753,A064820,케이프,"1,975","25,528,573",4.176501e+09,163.601036,12.072051
408,A097520,엠씨넥스,"20,250","17,745,456",2.981801e+10,1680.317823,12.051292
412,A008490,서흥,"30,600","11,569,113",2.938418e+10,2539.882012,12.047804

In [17]:
corp_filter.sort_values(by=['PER','EPS'], ascending=False)

,종목코드,종목명,현재가,상장주식수,당기순이익,EPS,PER
952,A204620,글로벌텍스프리,"3,360","37,254,218",8.365701e+09,224.557149,14.962783
1453,A126600,코프라,"3,430","21,115,634",4.842683e+09,229.341113,14.955888
1846,A008470,부스타,"5,310","8,404,800",2.987173e+09,355.412740,14.940376
1094,A063170,서울옥션,"6,250","16,917,500",7.084634e+09,418.775469,14.924465
142,A009240,한샘,"57,000","23,533,928",8.995704e+10,3822.440393,14.911940
1213,A007590,동방아그로,"6,720","13,617,577",6.154336e+09,451.940606,14.869210
826,A100700,세운메디칼,"3,420","43,800,000",1.007516e+10,230.026553,14.867849
848,A214430,아이쓰리시스템,"20,450","7,106,760",9.784710e+09,1376.817284,14.853097
1973,A131220,대한과학,"5,010","7,454,490",2.516975e+09,337.645500,14.838048
22,A033780,KT&G,"96,800","137,292,497",8.986593e+11,6545.582312,14.788600
1546,A033310,디케이디앤아이,"2,965","21,972,411",4.406555e+09,200.549453,14.784383
1569,A000220,유유제약,"9,970","6,368,587",4.312110e+09,677.090538,14.724766
2026,A053160,프리엠스,"5,660","6,000,000",2.306497e+09,384.416167,14.723626
548,A067280,멀티캠퍼스,"43,600","5,926,779",1.755218e+10,2961.503204,14.722253
195,A046890,서울반도체,"15,800","58,305,400",6.260134e+10,1073.679951,14.715745
610,A082920,비츠로셀,"10,500","21,539,152",1.537186e+10,713.670761,14.712667
105,A263750,펄어비스,"165,400","13,021,400",1.464462e+11,11246.576943,14.706697
383,A293480,하나제약,"23,750","16,200,000",2.616907e+10,1615.374938,14.702469
1425,A002920,유성기업,"2,865","25,947,500",5.092468e+09,196.260449,14.597949
1214,A205100,엑셈,"2,700","33,882,273",6.275021e+09,185.200710,14.578778
115,A026960,동서,"17,600","99,700,000",1.203970e+11,1207.592347,14.574455
1897,A007770,한일화학,"11,800","3,510,000",2.843593e+09,810.140456,14.565376
100,A007310,오뚜기,"649,000","3,605,237",1.608291e+11,44609.865315,14.548351
422,A047310,파워로직스,"10,100","34,420,982",2.392837e+10,695.168226,14.528857
919,A067900,와이엔텍,"7,210","18,199,659",9.033205e+09,496.339245,14.526355
732,A046440,KG모빌리언스,"5,880","29,906,957",1.211927e+10,405.232334,14.510195
647,A003070,코오롱글로벌,"8,300","25,210,438",1.445116e+10,573.221298,14.479574
363,A011280,태림포장,"5,860","70,805,940",2.867665e+10,405.003493,14.469011
238,A200130,콜마비앤에이치,"24,100","29,543,558",4.932240e+10,1669.480602,14.435627
388,A023410,유진기업,"4,950","77,310,863",2.658165e+10,343.828189,14.396725
...,...,...,...,...,...,...,...
999,A130580,나이스디앤비,"7,690","15,400,000",9.299592e+09,603.869610,12.734537
1186,A075180,새론오토모티브,"4,900","19,200,000",7.392147e+09,385.007656,12.727020
1460,A014440,영보화학,"3,600","20,000,000",5.657471e+09,282.873550,12.726535
47,A004020,현대제철,"38,900","133,445,785",4.079594e+11,3057.117428,12.724405
451,A265520,AP시스템,"22,750","14,099,511",2.522701e+10,1789.211839,12.715096
733,A001530,DI동일,"72,500","2,421,420",1.382487e+10,5709.406877,12.698342
447,A080420,모다이노칩,"4,070","79,721,622",2.566002e+10,321.870333,12.644844
1681,A024840,KBI메탈,"1,675","32,950,848",4.400083e+09,133.534742,12.543552
585,A079980,휴비스,"6,900","34,500,000",1.899182e+10,550.487536,12.534344
344,A029530,신도리코,"43,550","10,080,029",3.503411e+10,3475.596350,12.530224
216,A001680,대상,"23,500","34,648,025",6.539847e+10,1887.509375,12.450269
1376,A006660,삼성공조,"9,700","8,126,314",6.332359e+09,779.241240,12.448006
536,A010170,대한광통신,"3,585","73,741,625",2.128204e+10,288.602767,12.421918
248,A018670,SK가스,"75,300","9,141,781",5.543844e+10,6064.293489,12.416945
1343,A031820,콤텍시스템,"1,695","47,851,466",6.553668e+09,136.958563,12.376006
1528,A114810,아이원스,"4,925","13,415,919",5.339651e+09,398.008590,12.374105
498,A003220,대원제약,"14,650","19,662,677",2.328629e+10,1184.288742,12.370294
1790,A265560,영화테크,"9,020","5,345,090",3.898865e+09,729.429252,12.365833
407,A043150,바텍,"24,250","14,854,256",2.915201e+10,1962.535922,12.356462
911,A003650,미창석유,"76,000","1,739,672",1.072219e+10,6163.341710,12.330973
463,A008350,남선알미늄,"2,810","110,179,090",2.522052e+10,228.904768,12.275847
5,A012330,현대모비스,"242,500","95,306,694",1.888206e+12,19811.892751,12.240123
553,A084370,유진테크,"11,050","22,916,042",2.068889e+10,902.812362,12.239531
1360,A008250,이건산업,"7,250","10,952,635",6.510008e+09,594.378248,12.197620
272,A086450,동국제약,"67,800","8,892,000",4.943317e+10,5559.285538,12.195812
420,A003800,에이스침대,"31,350","11,090,000",2.868884e+10,2586.910640,12.118702
245,A064960,S&T모티브,"47,400","14,623,136",5.722514e+10,3913.329193,12.112449
1753,A064820,케이프,"1,975","25,528,573",4.176501e+09,163.601036,12.072051
408,A097520,엠씨넥스,"20,250","17,745,456",2.981801e+10,1680.317823,12.051292
412,A008490,서흥,"30,600","11,569,113",2.938418e+10,2539.882012,12.047804