In [1]:
import pandas as pd
corp_info = pd.read_csv('corp.csv', header=0)
corp_info

,순위,종목코드,종목명,현재가,대비,등락률,거래량,거래대금,시가,고가,저가,시가총액,시가총액비중(%),상장주식수,외국인 보유주식수,외국인 지분율(%),총카운트
0,1,005930,삼성전자,"46,100","-1,050",-2.2,"6,854,965","317,650,411,250","46,800","47,050","46,000","275,206,975,555,000",17.49,"5,969,782,550",NaN,NaN,2405.0
1,2,000660,SK하이닉스,"77,000","-2,800",-3.5,"2,616,455","203,392,849,900","79,000","79,400","76,500","56,056,182,105,000",3.56,"728,002,365",NaN,NaN,NaN
2,3,005935,삼성전자우,"38,100",-500,-1.3,"823,913","31,399,459,992","38,600","38,600","37,900","31,351,983,270,000",1.99,"822,886,700",NaN,NaN,NaN
3,4,005380,현대차,"128,000","-2,500",-1.9,"464,277","59,477,099,500","130,000","131,000","126,500","27,349,527,936,000",1.74,"213,668,187",NaN,NaN,NaN
4,5,051910,LG화학,"333,000",0,0.0,"168,074","55,303,005,500","333,500","333,500","325,000","23,507,250,219,000",1.49,"70,592,343",NaN,NaN,NaN
5,6,012330,현대모비스,"242,500","-3,000",-1.2,"169,686","40,865,947,500","245,500","245,500","237,500","23,111,873,295,000",1.47,"95,306,694",NaN,NaN,NaN
6,7,068270,셀트리온,"179,000","-6,000",-3.2,"433,127","78,396,577,000","183,500","184,500","179,000","22,970,903,530,000",1.46,"128,329,070",NaN,NaN,NaN
7,8,035420,NAVER,"138,500","-2,500",-1.8,"583,604","80,883,355,500","139,500","141,000","137,000","22,826,655,207,500",1.45,"164,813,395",NaN,NaN,NaN
8,9,055550,신한지주,"43,900",250,0.6,"871,054","38,233,388,300","43,800","44,150","43,600","20,817,361,869,300",1.32,"474,199,587",NaN,NaN,NaN
9,10,005490,POSCO,"228,500","-4,000",-1.7,"194,010","44,631,084,000","233,000","233,000","228,500","19,922,191,797,500",1.27,"87,186,835",NaN,NaN,NaN
10,11,017670,SK텔레콤,"246,000",500,0.2,"121,033","29,804,367,500","247,500","249,000","244,000","19,863,444,906,000",1.26,"80,745,711",NaN,NaN,NaN
11,12,051900,LG생활건강,"1,240,000","16,000",1.3,"31,789","39,285,922,000","1,230,000","1,248,000","1,226,000","19,366,564,280,000",1.23,"15,618,197",NaN,NaN,NaN
12,13,105560,KB금융,"43,600",-200,-0.5,"630,292","27,480,484,000","43,950","44,100","43,400","18,229,663,013,200",1.16,"418,111,537",NaN,NaN,NaN
13,14,207940,삼성바이오로직스,"273,000","-2,500",-0.9,"83,126","22,733,567,000","273,000","278,000","271,000","18,063,045,000,000",1.15,"66,165,000",NaN,NaN,NaN
14,15,015760,한국전력,"27,950",350,1.3,"1,840,989","51,060,219,550","27,600","27,950","27,300","17,942,895,952,150",1.14,"641,964,077",NaN,NaN,NaN
15,16,028260,삼성물산,"92,300","-2,200",-2.3,"213,772","19,794,618,700","94,000","94,100","91,800","17,508,390,968,900",1.11,"189,690,043",NaN,NaN,NaN
16,17,000270,기아차,"42,850",-750,-1.7,"782,422","33,611,610,600","43,800","43,900","42,500","17,369,819,418,950",1.10,"405,363,347",NaN,NaN,NaN
17,18,018260,삼성에스디에스,"212,000","-3,500",-1.6,"66,628","14,254,540,000","215,500","219,000","212,000","16,404,093,600,000",1.04,"77,377,800",NaN,NaN,NaN
18,19,006400,삼성SDI,"229,000","-3,000",-1.3,"180,305","41,102,882,000","231,500","232,500","225,500","15,747,077,370,000",1.00,"68,764,530",NaN,NaN,NaN
19,20,096770,SK이노베이션,"169,000","-4,000",-2.3,"282,740","47,497,441,561","174,000","174,000","164,500","15,626,680,316,000",0.99,"92,465,564",NaN,NaN,NaN
20,21,034730,SK,"221,500","-3,000",-1.3,"71,878","15,921,621,000","224,500","224,500","219,500","15,584,805,785,500",0.99,"70,360,297",NaN,NaN,NaN
21,22,032830,삼성생명,"77,000",-800,-1.0,"221,890","17,015,807,000","77,700","78,200","76,000","15,400,000,000,000",0.98,"200,000,000",NaN,NaN,NaN
22,23,033780,KT&G,"96,800",0,0.0,"205,333","19,950,938,000","97,100","97,900","96,800","13,289,913,709,600",0.84,"137,292,497",NaN,NaN,NaN
23,24,003550,LG,"73,300",-800,-1.1,"138,814","10,159,491,100","73,700","74,300","72,200","12,648,437,702,300",0.80,"172,557,131",NaN,NaN,NaN
24,25,000810,삼성화재,"262,500",-500,-0.2,"64,363","16,805,742,750","262,500","263,500","258,000","12,435,894,712,500",0.79,"47,374,837",NaN,NaN,NaN
25,26,066570,LG전자,"68,600",0,0.0,"377,472","25,967,194,700","68,300","69,700","68,000","11,226,240,040,400",0.71,"163,647,814",NaN,NaN,NaN
26,27,035720,카카오,"129,000","-2,000",-1.5,"368,365","47,659,535,500","130,000","132,000","128,000","10,768,353,690,000",0.68,"83,475,610",NaN,NaN,NaN
27,28,036570,엔씨소프트,"485,000","-7,000",-1.4,"53,965","26,253,350,000","490,000","495,000","481,000","10,644,063,170,000",0.68,"21,946,522",NaN,NaN,NaN
28,29,086790,하나금융지주,"35,100",-250,-0.7,"926,666","32,582,323,800","35,350","35,500","34,900","10,538,496,376,200",0.67,"300,242,062",NaN,NaN,NaN
29,30,010950,S-Oil,"91,700","-1,300",-1.4,"276,318","25,198,697,800","92,900","92,900","90,300","10,323,842,026,400",0.66,"112,582,792",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2375,2376,002785,진흥기업우B,"5,190",-240,-4.4,"23,393","121,733,250","5,400","5,470","5,020","4,448,961,420",0.00,"857,218",NaN,NaN,NaN
2376,2377,005965,동부건설우,"19,250",350,1.8,"2,337","43,569,150","18,900","19,500","18,200","4,345,341,000",0.00,"225,732",NaN,NaN,NaN
2377,2378,099350,하나니켈2호,"1,305",-135,-9.4,"68,876","93,513,190","1,415","1,450","1,300","4,285,620,000",0.00,"3,284,000",NaN,NaN,NaN
2378,2379,001755,한양증권우,"8,090",-260,-3.1,"3,313","26,739,700","8,360","8,360","7,910","4,247,250,000",0.00,"525,000",NaN,NaN,NaN
2379,2380,245450,씨앤에스링크,"2,640",-460,-14.8,472,"1,252,540","3,100","3,100","2,640","4,171,094,400",0.00,"1,579,960",NaN,NaN,NaN
2380,2381,001065,JW중외제약우,"24,800",-950,-3.7,"1,199","29,888,500","25,300","26,000","24,650","4,150,900,000",0.00,"167,375",NaN,NaN,NaN
2381,2382,271850,다이오진,"1,375",-80,-5.5,"4,621","5,795,605","1,515","1,515","1,250","4,125,000,000",0.00,"3,000,000",NaN,NaN,NaN
2382,2383,000995,DB하이텍1우,"36,050","-1,250",-3.4,979,"34,877,750","37,000","37,000","34,600","4,048,991,800",0.00,"112,316",NaN,NaN,NaN
2383,2384,002787,진흥기업2우B,"13,500",-400,-2.9,"5,760","77,446,750","13,900","13,900","13,250","3,979,908,000",0.00,"294,808",NaN,NaN,NaN
2384,2385,084440,유비온,"1,300",0,0.0,10,"13,000","1,300","1,300","1,300","3,896,239,100",0.00,"2,997,107",NaN,NaN,NaN
2385,2386,000545,흥국화재우,"4,975",-95,-1.9,"2,249","11,100,205","5,230","5,230","4,800","3,820,800,000",0.00,"768,000",NaN,NaN,NaN
2386,2387,092590,럭스피아,517,-61,-10.6,15,"9,653",664,664,517,"3,769,497,666",0.00,"7,291,098",NaN,NaN,NaN
2387,2388,001067,JW중외제약2우B,"39,350",-600,-1.5,590,"23,487,150","39,950","41,400","39,250","3,454,536,500",0.00,"87,790",NaN,NaN,NaN
2388,2389,189350,코셋,835,-80,-8.7,"1,026","1,073,961","1,050","1,050",788,"3,340,000,000",0.00,"4,000,000",NaN,NaN,NaN
2389,2390,149940,모다,155,0,0.0,0,0,0,0,0,"3,279,863,395",0.00,"21,160,409",NaN,NaN,NaN
2390,2391,00781K,코리아써키트2우B,"4,100",-210,-4.9,439,"1,785,855","4,065","4,140","4,065","3,213,165,900",0.00,"783,699",NaN,NaN,NaN
2391,2392,000325,노루홀딩스우,"17,200",-800,-4.4,300,"5,202,350","18,400","18,400","17,200","3,186,300,000",0.00,"185,250",NaN,NaN,NaN
2392,2393,032685,소프트센우,"22,000",-150,-0.7,"1,417","31,284,200","22,150","23,500","21,650","3,142,854,000",0.00,"142,857",NaN,NaN,NaN
2393,2394,227420,포레스팅블록체인,399,-31,-7.2,2,798,399,399,399,"3,027,586,464",0.00,"7,587,936",NaN,NaN,NaN
2394,2395,001527,동양2우B,"9,810",-290,-2.9,683,"6,778,610","10,500","10,500","9,700","3,027,061,890",0.00,"308,569",NaN,NaN,NaN
2395,2396,000547,흥국화재2우B,"19,200","-1,650",-7.9,"1,082","21,402,850","20,850","20,850","19,200","2,949,120,000",0.00,"153,600",NaN,NaN,NaN
2396,2397,000227,유유제약2우B,"17,900",-400,-2.2,350,"6,340,400","18,000","19,050","17,900","2,937,032,000",0.00,"164,080",NaN,NaN,NaN
2397,2398,001799,대한제당3우B,"21,500","-1,600",-6.9,"1,415","31,142,150","23,200","23,200","21,500","2,787,604,000",0.00,"129,656",NaN,NaN,NaN
2398,2399,223220,아이피몬스터,256,0,0.0,0,0,0,0,0,"2,761,538,816",0.00,"10,787,261",NaN,NaN,NaN
2399,2400,208890,에듀파트너,"1,310",-220,-14.4,11,"15,310","1,400","1,400","1,310","2,607,974,200",0.00,"1,990,820",NaN,NaN,NaN
2400,2401,276240,엘리비젼,997,1,0.1,"1,123","1,120,472",854,"1,140",854,"2,579,438,400",0.00,"2,587,200",NaN,NaN,NaN
2401,2402,001529,동양3우B,"27,600",-950,-3.3,"1,889","52,265,350","28,150","29,000","27,200","2,476,327,200",0.00,"89,722",NaN,NaN,NaN
2402,2403,247300,인프라웨어테크놀러지,370,-36,-8.9,"2,860","1,058,200",370,370,370,"2,263,733,260",0.00,"6,118,198",NaN,NaN,NaN
2403,2404,224020,에스케이씨에스,830,-140,-14.4,"1,151","1,004,780",873,873,830,"2,241,000,000",0.00,"2,700,000",NaN,NaN,NaN
2404,2405,135270,세종머티리얼즈,104,0,0.0,0,0,0,0,0,"743,189,304",0.00,"7,146,051",NaN,NaN,NaN

In [2]:
corp_info = corp_info[['종목코드','종목명','현재가','상장주식수']]
corp_info

        종목코드         종목명        현재가          상장주식수
0     005930        삼성전자     46,100  5,969,782,550
1     000660      SK하이닉스     77,000    728,002,365
2     005935       삼성전자우     38,100    822,886,700
3     005380         현대차    128,000    213,668,187
4     051910        LG화학    333,000     70,592,343
5     012330       현대모비스    242,500     95,306,694
6     068270        셀트리온    179,000    128,329,070
7     035420       NAVER    138,500    164,813,395
8     055550        신한지주     43,900    474,199,587
9     005490       POSCO    228,500     87,186,835
10    017670       SK텔레콤    246,000     80,745,711
11    051900      LG생활건강  1,240,000     15,618,197
12    105560        KB금융     43,600    418,111,537
13    207940    삼성바이오로직스    273,000     66,165,000
14    015760        한국전력     27,950    641,964,077
15    028260        삼성물산     92,300    189,690,043
16    000270         기아차     42,850    405,363,347
17    018260     삼성에스디에스    212,000     77,377,800
18    006400       삼성SDI    229,000     68,764,530
19    096770     SK이노베이션    169,000     92,465,564
20    034730          SK    221,500     70,360,297
21    032830        삼성생명     77,000    200,000,000
22    033780        KT&G     96,800    137,292,497
23    003550          LG     73,300    172,557,131
24    000810        삼성화재    262,500     47,374,837
25    066570        LG전자     68,600    163,647,814
26    035720         카카오    129,000     83,475,610
27    036570       엔씨소프트    485,000     21,946,522
28    086790      하나금융지주     35,100    300,242,062
29    010950       S-Oil     91,700    112,582,792
...      ...         ...        ...            ...
2375  002785      진흥기업우B      5,190        857,218
2376  005965       동부건설우     19,250        225,732
2377  099350      하나니켈2호      1,305      3,284,000
2378  001755       한양증권우      8,090        525,000
2379  245450      씨앤에스링크      2,640      1,579,960
2380  001065     JW중외제약우     24,800        167,375
2381  271850        다이오진      1,375      3,000,000
2382  000995     DB하이텍1우     36,050        112,316
2383  002787     진흥기업2우B     13,500        294,808
2384  084440         유비온      1,300      2,997,107
2385  000545       흥국화재우      4,975        768,000
2386  092590        럭스피아        517      7,291,098
2387  001067   JW중외제약2우B     39,350         87,790
2388  189350          코셋        835      4,000,000
2389  149940          모다        155     21,160,409
2390  00781K   코리아써키트2우B      4,100        783,699
2391  000325      노루홀딩스우     17,200        185,250
2392  032685       소프트센우     22,000        142,857
2393  227420    포레스팅블록체인        399      7,587,936
2394  001527       동양2우B      9,810        308,569
2395  000547     흥국화재2우B     19,200        153,600
2396  000227     유유제약2우B     17,900        164,080
2397  001799     대한제당3우B     21,500        129,656
2398  223220      아이피몬스터        256     10,787,261
2399  208890       에듀파트너      1,310      1,990,820
2400  276240        엘리비젼        997      2,587,200
2401  001529       동양3우B     27,600         89,722
2402  247300  인프라웨어테크놀러지        370      6,118,198
2403  224020     에스케이씨에스        830      2,700,000
2404  135270     세종머티리얼즈        104      7,146,051

[2405 rows x 4 columns]

In [3]:
corp_info['종목코드'] = 'A' + corp_info['종목코드'].astype(str)
corp_info

         종목코드         종목명        현재가          상장주식수
0     A005930        삼성전자     46,100  5,969,782,550
1     A000660      SK하이닉스     77,000    728,002,365
2     A005935       삼성전자우     38,100    822,886,700
3     A005380         현대차    128,000    213,668,187
4     A051910        LG화학    333,000     70,592,343
5     A012330       현대모비스    242,500     95,306,694
6     A068270        셀트리온    179,000    128,329,070
7     A035420       NAVER    138,500    164,813,395
8     A055550        신한지주     43,900    474,199,587
9     A005490       POSCO    228,500     87,186,835
10    A017670       SK텔레콤    246,000     80,745,711
11    A051900      LG생활건강  1,240,000     15,618,197
12    A105560        KB금융     43,600    418,111,537
13    A207940    삼성바이오로직스    273,000     66,165,000
14    A015760        한국전력     27,950    641,964,077
15    A028260        삼성물산     92,300    189,690,043
16    A000270         기아차     42,850    405,363,347
17    A018260     삼성에스디에스    212,000     77,377,800
18    A006400       삼성SDI    229,000     68,764,530
19    A096770     SK이노베이션    169,000     92,465,564
20    A034730          SK    221,500     70,360,297
21    A032830        삼성생명     77,000    200,000,000
22    A033780        KT&G     96,800    137,292,497
23    A003550          LG     73,300    172,557,131
24    A000810        삼성화재    262,500     47,374,837
25    A066570        LG전자     68,600    163,647,814
26    A035720         카카오    129,000     83,475,610
27    A036570       엔씨소프트    485,000     21,946,522
28    A086790      하나금융지주     35,100    300,242,062
29    A010950       S-Oil     91,700    112,582,792
...       ...         ...        ...            ...
2375  A002785      진흥기업우B      5,190        857,218
2376  A005965       동부건설우     19,250        225,732
2377  A099350      하나니켈2호      1,305      3,284,000
2378  A001755       한양증권우      8,090        525,000
2379  A245450      씨앤에스링크      2,640      1,579,960
2380  A001065     JW중외제약우     24,800        167,375
2381  A271850        다이오진      1,375      3,000,000
2382  A000995     DB하이텍1우     36,050        112,316
2383  A002787     진흥기업2우B     13,500        294,808
2384  A084440         유비온      1,300      2,997,107
2385  A000545       흥국화재우      4,975        768,000
2386  A092590        럭스피아        517      7,291,098
2387  A001067   JW중외제약2우B     39,350         87,790
2388  A189350          코셋        835      4,000,000
2389  A149940          모다        155     21,160,409
2390  A00781K   코리아써키트2우B      4,100        783,699
2391  A000325      노루홀딩스우     17,200        185,250
2392  A032685       소프트센우     22,000        142,857
2393  A227420    포레스팅블록체인        399      7,587,936
2394  A001527       동양2우B      9,810        308,569
2395  A000547     흥국화재2우B     19,200        153,600
2396  A000227     유유제약2우B     17,900        164,080
2397  A001799     대한제당3우B     21,500        129,656
2398  A223220      아이피몬스터        256     10,787,261
2399  A208890       에듀파트너      1,310      1,990,820
2400  A276240        엘리비젼        997      2,587,200
2401  A001529       동양3우B     27,600         89,722
2402  A247300  인프라웨어테크놀러지        370      6,118,198
2403  A224020     에스케이씨에스        830      2,700,000
2404  A135270     세종머티리얼즈        104      7,146,051

[2405 rows x 4 columns]

In [4]:
corp_result = pd.read_excel('SAMPLE_2018.xlsx')
corp_result

,종목코드,회사명,당기순이익,유동자산,부채총계,매출총이익,자본총계,자산총계
0,A000020,동화약품,10068113000,227887463000,73198591000,115903237000,297400652000,370599243000
1,A000040,KR모터스,-24442080000,86949763000,85006462000,-631020000,69894605000,154901067000
2,A000050,경방,20189241000,120711492000,593023494000,107395818000,708769347000,1301792841000
3,A000060,메리츠화재,234721346000,0,18195561629000,0,2283200522000,20478762151000
4,A000070,삼양홀딩스,102512252000,1057235344000,1311855275000,482105988000,2001941981000,3313797255000
5,A000080,하이트진로,22272353000,1064966843000,2265764980000,761860402000,1162378535000,3428143515000
6,A000100,유한양행,58334962000,1110961783000,522077130000,413792024000,1651735504000,2173812633000
7,A000120,CJ대한통운,51800069000,2180844615000,4737828935000,828072934000,3138903155000,7876732089000
8,A000140,하이트진로홀딩스,8640980000,1083713642000,2893499586000,767141228000,1095786557000,3989286143000
9,A000150,두산,-340510995000,11585894166000,21735235429000,3323508790000,7145046191000,28880281620000
10,A000180,성창기업지주,-7933704000,85694716000,159282203000,17312092000,489378544000,648660747000
11,A000210,대림산업,678088774000,6366648561000,6783472630000,1420161607000,6050244102000,12833716732000
12,A000220,유유제약,4312110000,68869662000,48354059000,40636937000,86872256000,135226315000
13,A000230,일동홀딩스,-3831883000,54890858000,100522263000,20013961000,164946011000,265468274000
14,A000240,한국타이어월드와이드,218355604000,590386119000,262718282000,284108210000,3235872326000,3498590608000
15,A000250,삼천당제약,14592937000,142271889000,55394974000,83197927000,205763466000,261158440000
16,A000270,기아차,1155943000000,19711791000000,24543141000000,7992530000000,27243464000000,51786605000000
17,A000300,대유플러스,19120849000,250712765000,863495206000,73675381000,140608976000,1004104182000
18,A000320,노루홀딩스,2664076000,449147290000,425647066000,183192460000,561495276000,987142342000
19,A000370,한화손해보험,81759590000,0,15318315284000,0,1415552026000,16733867311000
20,A000390,삼화페인트,800759000,275185176000,276200374000,87345386000,281779106000,557979480000
21,A000400,롯데손해보험,91314265000,0,13651651397000,0,563337402000,14214988799000
22,A000430,대원강업,23857286000,352164240000,515047305000,114161257000,570720025000,1085767330000
23,A000440,중앙에너비스,889990000,4174206000,13480020000,12696157000,45263718000,58743738000
24,A000480,조선내화,57955243000,369512835000,336922588000,116768660000,693699617000,1030622205000
25,A000490,대동공업,1464262000,447800610000,555212961000,125048867000,217503766000,772716728000
26,A000500,가온전선,98902000,277829165000,266088415000,35493547000,260405860000,526494275000
27,A000520,삼일제약,-8562748000,59184330000,91865621000,34791021000,56082999000,147948619000
28,A000540,흥국화재,50441000000,0,11256838000000,0,682034000000,11938872000000
29,A000590,CS홀딩스,12641149000,188480772000,29665433000,28531036000,274752760000,304418193000
...,...,...,...,...,...,...,...,...
1979,A297570,IBKS제9호스팩,-756000,0,939793000,0,5267905000,6207699000
1980,A298000,효성화학,20394861000,438322896000,1286001139000,114602893000,367248241000,1653249379000
1981,A298020,효성티앤씨,31498303000,1428058179000,2651942914000,255765643000,486901345000,3138844259000
1982,A298040,효성중공업,1908746000,1492635018000,2527800474000,239206367000,904711079000,3432511553000
1983,A298050,효성첨단소재,-23744728000,1030997728000,2068681942000,182774224000,466015869000,2534697811000
1984,A298380,에이비엘바이오,-117234140000,161091085000,11906880000,1257884000,156962235000,168869115000
1985,A298690,에어부산,20294184000,105633987000,150402815000,65447298000,152296942000,302699757000
1986,A299170,IBKS제10호스팩,-25108000,0,1499562000,0,8332973000,9832536000
1987,A299660,셀리드,-11286321000,8239136000,720628000,0,13495505000,14216133000
1988,A300720,한일시멘트,53726823000,565218272000,499783148000,119349714000,868218023000,1368001171000
1989,A302430,이노메트리,5247720000,52774757000,11292993000,11012834000,48364402000,59657395000
1990,A303030,대신밸런스제5호스팩,-4049000,0,651846000,0,7758537000,8410382000
1991,A306200,세아제강,7030156000,479655614000,500666740000,32708406000,553451801000,1054118541000
1992,A306620,DB금융스팩6호,33000,0,1056050000,0,8797198000,9853248000
1993,A307070,SK4호스팩,-24500000,0,738660000,0,9116796000,9855456000
1994,A307160,하나머스트제6호스팩,-9884000,0,716747000,0,8216413000,8933159000
1995,A307180,신영스팩4호,-131025000,0,1230484000,0,8611395000,9841878000
1996,A307280,교보8호스팩,-28370000,0,1062020000,0,6774388000,7836408000
1997,A307750,대신밸런스제6호스팩,-26859000,0,710480000,0,9613697000,10324178000
1998,A307870,골든브릿지이안5호,-2987000,0,898008000,0,8839206000,9737214000
1999,A307950,현대오토에버,55228435000,689503604000,377482748000,145535428000,451588443000,829071191000
2000,A309930,삼성머스트스팩3호,-7758000,0,696723000,0,8272471000,8969194000
2001,A310200,미래에셋대우스팩2호,-11654000,0,1163795000,0,5804306000,6968101000
2002,A310840,엔에이치스팩13호,-10869000,0,1407776000,0,6475928000,7883704000
2003,A310870,한국제8호스팩,-7076000,0,529500000,0,6350131000,6879631000
2004,A311270,키움제5호스팩,-130749000,0,769275000,0,7103863000,7873138000
2005,A313750,유안타제4호스팩,-13122000,0,1103143000,0,685353000,1788497000
2006,A316140,우리금융지주,0,0,0,0,0,0
2007,A317030,케이비17호스팩,0,0,0,0,0,0
2008,A317320,한화에스비아이스팩,0,0,0,0,0,0

In [5]:
corp_data = corp_result[['종목코드', '매출총이익', '자본총계', '자산총계', '부채총계']]
corp_data

         종목코드          매출총이익            자본총계            자산총계            부채총계
0     A000020   115903237000    297400652000    370599243000     73198591000
1     A000040     -631020000     69894605000    154901067000     85006462000
2     A000050   107395818000    708769347000   1301792841000    593023494000
3     A000060              0   2283200522000  20478762151000  18195561629000
4     A000070   482105988000   2001941981000   3313797255000   1311855275000
5     A000080   761860402000   1162378535000   3428143515000   2265764980000
6     A000100   413792024000   1651735504000   2173812633000    522077130000
7     A000120   828072934000   3138903155000   7876732089000   4737828935000
8     A000140   767141228000   1095786557000   3989286143000   2893499586000
9     A000150  3323508790000   7145046191000  28880281620000  21735235429000
10    A000180    17312092000    489378544000    648660747000    159282203000
11    A000210  1420161607000   6050244102000  12833716732000   6783472630000
12    A000220    40636937000     86872256000    135226315000     48354059000
13    A000230    20013961000    164946011000    265468274000    100522263000
14    A000240   284108210000   3235872326000   3498590608000    262718282000
15    A000250    83197927000    205763466000    261158440000     55394974000
16    A000270  7992530000000  27243464000000  51786605000000  24543141000000
17    A000300    73675381000    140608976000   1004104182000    863495206000
18    A000320   183192460000    561495276000    987142342000    425647066000
19    A000370              0   1415552026000  16733867311000  15318315284000
20    A000390    87345386000    281779106000    557979480000    276200374000
21    A000400              0    563337402000  14214988799000  13651651397000
22    A000430   114161257000    570720025000   1085767330000    515047305000
23    A000440    12696157000     45263718000     58743738000     13480020000
24    A000480   116768660000    693699617000   1030622205000    336922588000
25    A000490   125048867000    217503766000    772716728000    555212961000
26    A000500    35493547000    260405860000    526494275000    266088415000
27    A000520    34791021000     56082999000    147948619000     91865621000
28    A000540              0    682034000000  11938872000000  11256838000000
29    A000590    28531036000    274752760000    304418193000     29665433000
...       ...            ...             ...             ...             ...
1979  A297570              0      5267905000      6207699000       939793000
1980  A298000   114602893000    367248241000   1653249379000   1286001139000
1981  A298020   255765643000    486901345000   3138844259000   2651942914000
1982  A298040   239206367000    904711079000   3432511553000   2527800474000
1983  A298050   182774224000    466015869000   2534697811000   2068681942000
1984  A298380     1257884000    156962235000    168869115000     11906880000
1985  A298690    65447298000    152296942000    302699757000    150402815000
1986  A299170              0      8332973000      9832536000      1499562000
1987  A299660              0     13495505000     14216133000       720628000
1988  A300720   119349714000    868218023000   1368001171000    499783148000
1989  A302430    11012834000     48364402000     59657395000     11292993000
1990  A303030              0      7758537000      8410382000       651846000
1991  A306200    32708406000    553451801000   1054118541000    500666740000
1992  A306620              0      8797198000      9853248000      1056050000
1993  A307070              0      9116796000      9855456000       738660000
1994  A307160              0      8216413000      8933159000       716747000
1995  A307180              0      8611395000      9841878000      1230484000
1996  A307280              0      6774388000      7836408000      1062020000
1997  A307750              0      9613697000     10324178000       710480000
1998  A307870              0      8839206000      9737214000       898008000
1999  A307950   145535428000    451588443000    829071191000    377482748000
2000  A309930              0      8272471000      8969194000       696723000
2001  A310200              0      5804306000      6968101000      1163795000
2002  A310840              0      6475928000      7883704000      1407776000
2003  A310870              0      6350131000      6879631000       529500000
2004  A311270              0      7103863000      7873138000       769275000
2005  A313750              0       685353000      1788497000      1103143000
2006  A316140              0               0               0               0
2007  A317030              0               0               0               0
2008  A317320              0               0               0               0

[2009 rows x 5 columns]

In [6]:
corp_total = pd.merge(corp_info, corp_data, how='left', on='종목코드')
corp_total

,종목코드,종목명,현재가,상장주식수,매출총이익,자본총계,자산총계,부채총계
0,A005930,삼성전자,"46,100","5,969,782,550",1.113770e+14,2.477532e+14,3.393572e+14,9.160407e+13
1,A000660,SK하이닉스,"77,000","728,002,365",2.526423e+13,4.685233e+13,6.365834e+13,1.680600e+13
2,A005935,삼성전자우,"38,100","822,886,700",NaN,NaN,NaN,NaN
3,A005380,현대차,"128,000","213,668,187",1.514213e+13,7.389601e+13,1.806558e+14,1.067597e+14
4,A051910,LG화학,"333,000","70,592,343",5.346197e+12,1.732213e+13,2.894414e+13,1.162201e+13
5,A012330,현대모비스,"242,500","95,306,694",4.567004e+12,3.070343e+13,4.307113e+13,1.236770e+13
6,A068270,셀트리온,"179,000","128,329,070",5.491659e+11,2.632778e+12,3.540627e+12,9.078488e+11
7,A035420,NAVER,"138,500","164,813,395",5.586905e+12,5.949141e+12,9.881191e+12,3.932050e+12
8,A055550,신한지주,"43,900","474,199,587",0.000000e+00,3.665143e+13,4.596005e+14,4.229491e+14
9,A005490,POSCO,"228,500","87,186,835",7.972381e+12,4.675955e+13,7.824827e+13,3.148871e+13
10,A017670,SK텔레콤,"246,000","80,745,711",1.687396e+13,2.234925e+13,4.236911e+13,2.001986e+13
11,A051900,LG생활건강,"1,240,000","15,618,197",4.051123e+12,3.594020e+12,5.275874e+12,1.681854e+12
12,A105560,KB금융,"43,600","418,111,537",0.000000e+00,3.571303e+13,4.795883e+14,4.438753e+14
13,A207940,삼성바이오로직스,"273,000","66,165,000",1.451599e+11,4.155468e+12,5.980409e+12,1.824940e+12
14,A015760,한국전력,"27,950","641,964,077",2.419889e+12,7.109276e+13,1.852491e+14,1.141563e+14
15,A028260,삼성물산,"92,300","189,690,043",3.985309e+12,2.254894e+13,4.240665e+13,1.985772e+13
16,A000270,기아차,"42,850","405,363,347",7.992530e+12,2.724346e+13,5.178660e+13,2.454314e+13
17,A018260,삼성에스디에스,"212,000","77,377,800",1.664389e+12,6.148552e+12,8.013849e+12,1.865297e+12
18,A006400,삼성SDI,"229,000","68,764,530",2.040084e+12,1.222522e+13,1.934972e+13,7.124502e+12
19,A096770,SK이노베이션,"169,000","92,465,564",3.981682e+12,1.932798e+13,3.608538e+13,1.675740e+13
20,A034730,SK,"221,500","70,360,297",9.650795e+12,5.088787e+13,1.194570e+14,6.856912e+13
21,A032830,삼성생명,"77,000","200,000,000",0.000000e+00,3.050546e+13,2.894277e+14,2.589222e+14
22,A033780,KT&G,"96,800","137,292,497",2.635484e+12,8.133080e+12,1.015510e+13,2.022021e+12
23,A003550,LG,"73,300","172,557,131",2.386962e+12,1.816448e+13,2.283591e+13,4.671433e+12
24,A000810,삼성화재,"262,500","47,374,837",0.000000e+00,1.238305e+13,7.941639e+13,6.703334e+13
25,A066570,LG전자,"68,600","163,647,814",1.508104e+13,1.630691e+13,4.432844e+13,2.802154e+13
26,A035720,카카오,"129,000","83,475,610",2.416992e+12,5.627158e+12,7.959542e+12,2.332385e+12
27,A036570,엔씨소프트,"485,000","21,946,522",1.715116e+12,2.378971e+12,2.941279e+12,5.623073e+11
28,A086790,하나금융지주,"35,100","300,242,062",0.000000e+00,2.710846e+13,3.850086e+14,3.579002e+14
29,A010950,S-Oil,"91,700","112,582,792",1.263049e+12,6.469234e+12,1.595504e+13,9.485810e+12
...,...,...,...,...,...,...,...,...
2375,A002785,진흥기업우B,"5,190","857,218",NaN,NaN,NaN,NaN
2376,A005965,동부건설우,"19,250","225,732",NaN,NaN,NaN,NaN
2377,A099350,하나니켈2호,"1,305","3,284,000",NaN,NaN,NaN,NaN
2378,A001755,한양증권우,"8,090","525,000",NaN,NaN,NaN,NaN
2379,A245450,씨앤에스링크,"2,640","1,579,960",NaN,NaN,NaN,NaN
2380,A001065,JW중외제약우,"24,800","167,375",NaN,NaN,NaN,NaN
2381,A271850,다이오진,"1,375","3,000,000",NaN,NaN,NaN,NaN
2382,A000995,DB하이텍1우,"36,050","112,316",NaN,NaN,NaN,NaN
2383,A002787,진흥기업2우B,"13,500","294,808",NaN,NaN,NaN,NaN
2384,A084440,유비온,"1,300","2,997,107",NaN,NaN,NaN,NaN
2385,A000545,흥국화재우,"4,975","768,000",NaN,NaN,NaN,NaN
2386,A092590,럭스피아,517,"7,291,098",NaN,NaN,NaN,NaN
2387,A001067,JW중외제약2우B,"39,350","87,790",NaN,NaN,NaN,NaN
2388,A189350,코셋,835,"4,000,000",NaN,NaN,NaN,NaN
2389,A149940,모다,155,"21,160,409",7.766928e+10,6.091668e+10,2.299720e+11,1.690554e+11
2390,A00781K,코리아써키트2우B,"4,100","783,699",NaN,NaN,NaN,NaN
2391,A000325,노루홀딩스우,"17,200","185,250",NaN,NaN,NaN,NaN
2392,A032685,소프트센우,"22,000","142,857",NaN,NaN,NaN,NaN
2393,A227420,포레스팅블록체인,399,"7,587,936",NaN,NaN,NaN,NaN
2394,A001527,동양2우B,"9,810","308,569",NaN,NaN,NaN,NaN
2395,A000547,흥국화재2우B,"19,200","153,600",NaN,NaN,NaN,NaN
2396,A000227,유유제약2우B,"17,900","164,080",NaN,NaN,NaN,NaN
2397,A001799,대한제당3우B,"21,500","129,656",NaN,NaN,NaN,NaN
2398,A223220,아이피몬스터,256,"10,787,261",NaN,NaN,NaN,NaN
2399,A208890,에듀파트너,"1,310","1,990,820",NaN,NaN,NaN,NaN
2400,A276240,엘리비젼,997,"2,587,200",NaN,NaN,NaN,NaN
2401,A001529,동양3우B,"27,600","89,722",NaN,NaN,NaN,NaN
2402,A247300,인프라웨어테크놀러지,370,"6,118,198",NaN,NaN,NaN,NaN
2403,A224020,에스케이씨에스,830,"2,700,000",NaN,NaN,NaN,NaN
2404,A135270,세종머티리얼즈,104,"7,146,051",NaN,NaN,NaN,NaN

In [7]:
corp_total = corp_info.join(corp_data.set_index('종목코드'), how='outer', on='종목코드')
corp_total

,종목코드,종목명,현재가,상장주식수,매출총이익,자본총계,자산총계,부채총계
0,A005930,삼성전자,"46,100","5,969,782,550",1.113770e+14,2.477532e+14,3.393572e+14,9.160407e+13
1,A000660,SK하이닉스,"77,000","728,002,365",2.526423e+13,4.685233e+13,6.365834e+13,1.680600e+13
2,A005935,삼성전자우,"38,100","822,886,700",NaN,NaN,NaN,NaN
3,A005380,현대차,"128,000","213,668,187",1.514213e+13,7.389601e+13,1.806558e+14,1.067597e+14
4,A051910,LG화학,"333,000","70,592,343",5.346197e+12,1.732213e+13,2.894414e+13,1.162201e+13
5,A012330,현대모비스,"242,500","95,306,694",4.567004e+12,3.070343e+13,4.307113e+13,1.236770e+13
6,A068270,셀트리온,"179,000","128,329,070",5.491659e+11,2.632778e+12,3.540627e+12,9.078488e+11
7,A035420,NAVER,"138,500","164,813,395",5.586905e+12,5.949141e+12,9.881191e+12,3.932050e+12
8,A055550,신한지주,"43,900","474,199,587",0.000000e+00,3.665143e+13,4.596005e+14,4.229491e+14
9,A005490,POSCO,"228,500","87,186,835",7.972381e+12,4.675955e+13,7.824827e+13,3.148871e+13
10,A017670,SK텔레콤,"246,000","80,745,711",1.687396e+13,2.234925e+13,4.236911e+13,2.001986e+13
11,A051900,LG생활건강,"1,240,000","15,618,197",4.051123e+12,3.594020e+12,5.275874e+12,1.681854e+12
12,A105560,KB금융,"43,600","418,111,537",0.000000e+00,3.571303e+13,4.795883e+14,4.438753e+14
13,A207940,삼성바이오로직스,"273,000","66,165,000",1.451599e+11,4.155468e+12,5.980409e+12,1.824940e+12
14,A015760,한국전력,"27,950","641,964,077",2.419889e+12,7.109276e+13,1.852491e+14,1.141563e+14
15,A028260,삼성물산,"92,300","189,690,043",3.985309e+12,2.254894e+13,4.240665e+13,1.985772e+13
16,A000270,기아차,"42,850","405,363,347",7.992530e+12,2.724346e+13,5.178660e+13,2.454314e+13
17,A018260,삼성에스디에스,"212,000","77,377,800",1.664389e+12,6.148552e+12,8.013849e+12,1.865297e+12
18,A006400,삼성SDI,"229,000","68,764,530",2.040084e+12,1.222522e+13,1.934972e+13,7.124502e+12
19,A096770,SK이노베이션,"169,000","92,465,564",3.981682e+12,1.932798e+13,3.608538e+13,1.675740e+13
20,A034730,SK,"221,500","70,360,297",9.650795e+12,5.088787e+13,1.194570e+14,6.856912e+13
21,A032830,삼성생명,"77,000","200,000,000",0.000000e+00,3.050546e+13,2.894277e+14,2.589222e+14
22,A033780,KT&G,"96,800","137,292,497",2.635484e+12,8.133080e+12,1.015510e+13,2.022021e+12
23,A003550,LG,"73,300","172,557,131",2.386962e+12,1.816448e+13,2.283591e+13,4.671433e+12
24,A000810,삼성화재,"262,500","47,374,837",0.000000e+00,1.238305e+13,7.941639e+13,6.703334e+13
25,A066570,LG전자,"68,600","163,647,814",1.508104e+13,1.630691e+13,4.432844e+13,2.802154e+13
26,A035720,카카오,"129,000","83,475,610",2.416992e+12,5.627158e+12,7.959542e+12,2.332385e+12
27,A036570,엔씨소프트,"485,000","21,946,522",1.715116e+12,2.378971e+12,2.941279e+12,5.623073e+11
28,A086790,하나금융지주,"35,100","300,242,062",0.000000e+00,2.710846e+13,3.850086e+14,3.579002e+14
29,A010950,S-Oil,"91,700","112,582,792",1.263049e+12,6.469234e+12,1.595504e+13,9.485810e+12
...,...,...,...,...,...,...,...,...
2378,A001755,한양증권우,"8,090","525,000",NaN,NaN,NaN,NaN
2379,A245450,씨앤에스링크,"2,640","1,579,960",NaN,NaN,NaN,NaN
2380,A001065,JW중외제약우,"24,800","167,375",NaN,NaN,NaN,NaN
2381,A271850,다이오진,"1,375","3,000,000",NaN,NaN,NaN,NaN
2382,A000995,DB하이텍1우,"36,050","112,316",NaN,NaN,NaN,NaN
2383,A002787,진흥기업2우B,"13,500","294,808",NaN,NaN,NaN,NaN
2384,A084440,유비온,"1,300","2,997,107",NaN,NaN,NaN,NaN
2385,A000545,흥국화재우,"4,975","768,000",NaN,NaN,NaN,NaN
2386,A092590,럭스피아,517,"7,291,098",NaN,NaN,NaN,NaN
2387,A001067,JW중외제약2우B,"39,350","87,790",NaN,NaN,NaN,NaN
2388,A189350,코셋,835,"4,000,000",NaN,NaN,NaN,NaN
2389,A149940,모다,155,"21,160,409",7.766928e+10,6.091668e+10,2.299720e+11,1.690554e+11
2390,A00781K,코리아써키트2우B,"4,100","783,699",NaN,NaN,NaN,NaN
2391,A000325,노루홀딩스우,"17,200","185,250",NaN,NaN,NaN,NaN
2392,A032685,소프트센우,"22,000","142,857",NaN,NaN,NaN,NaN
2393,A227420,포레스팅블록체인,399,"7,587,936",NaN,NaN,NaN,NaN
2394,A001527,동양2우B,"9,810","308,569",NaN,NaN,NaN,NaN
2395,A000547,흥국화재2우B,"19,200","153,600",NaN,NaN,NaN,NaN
2396,A000227,유유제약2우B,"17,900","164,080",NaN,NaN,NaN,NaN
2397,A001799,대한제당3우B,"21,500","129,656",NaN,NaN,NaN,NaN
2398,A223220,아이피몬스터,256,"10,787,261",NaN,NaN,NaN,NaN
2399,A208890,에듀파트너,"1,310","1,990,820",NaN,NaN,NaN,NaN
2400,A276240,엘리비젼,997,"2,587,200",NaN,NaN,NaN,NaN
2401,A001529,동양3우B,"27,600","89,722",NaN,NaN,NaN,NaN
2402,A247300,인프라웨어테크놀러지,370,"6,118,198",NaN,NaN,NaN,NaN
2403,A224020,에스케이씨에스,830,"2,700,000",NaN,NaN,NaN,NaN
2404,A135270,세종머티리얼즈,104,"7,146,051",NaN,NaN,NaN,NaN
2404,A002250,NaN,NaN,NaN,9.219373e+10,2.169061e+11,2.768905e+11,5.998438e+10
2404,A026180,NaN,NaN,NaN,4.455009e+09,4.352216e+10,1.772086e+11,1.336864e+11
2404,A079660,NaN,NaN,NaN,7.692682e+10,1.553774e+11,4.001202e+11,2.447428e+11

In [8]:
corp_total["GP/A"] = corp_total["매출총이익"] / corp_total["자본총계"]
corp_total["BPS"] = (corp_total["자본총계"]) / corp_total['상장주식수'].str.replace(',','').astype("float64")
corp_total["PBR"] = corp_total["현재가"].str.replace(',', '').astype("float64") / corp_total["BPS"].astype("float64")
corp_total

,종목코드,종목명,현재가,상장주식수,매출총이익,자본총계,자산총계,부채총계,GP/A,BPS,PBR
0,A005930,삼성전자,"46,100","5,969,782,550",1.113770e+14,2.477532e+14,3.393572e+14,9.160407e+13,0.449548,41501.206271,1.110811
1,A000660,SK하이닉스,"77,000","728,002,365",2.526423e+13,4.685233e+13,6.365834e+13,1.680600e+13,0.539231,64357.388454,1.196444
2,A005935,삼성전자우,"38,100","822,886,700",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A005380,현대차,"128,000","213,668,187",1.514213e+13,7.389601e+13,1.806558e+14,1.067597e+14,0.204911,345844.699848,0.370108
4,A051910,LG화학,"333,000","70,592,343",5.346197e+12,1.732213e+13,2.894414e+13,1.162201e+13,0.308634,245382.533910,1.357065
5,A012330,현대모비스,"242,500","95,306,694",4.567004e+12,3.070343e+13,4.307113e+13,1.236770e+13,0.148746,322153.950697,0.752746
6,A068270,셀트리온,"179,000","128,329,070",5.491659e+11,2.632778e+12,3.540627e+12,9.078488e+11,0.208588,20515.833723,8.724968
7,A035420,NAVER,"138,500","164,813,395",5.586905e+12,5.949141e+12,9.881191e+12,3.932050e+12,0.939111,36096.219685,3.836967
8,A055550,신한지주,"43,900","474,199,587",0.000000e+00,3.665143e+13,4.596005e+14,4.229491e+14,0.000000,77291.147029,0.567982
9,A005490,POSCO,"228,500","87,186,835",7.972381e+12,4.675955e+13,7.824827e+13,3.148871e+13,0.170497,536314.351473,0.426056
10,A017670,SK텔레콤,"246,000","80,745,711",1.687396e+13,2.234925e+13,4.236911e+13,2.001986e+13,0.755012,276785.599176,0.888775
11,A051900,LG생활건강,"1,240,000","15,618,197",4.051123e+12,3.594020e+12,5.275874e+12,1.681854e+12,1.127184,230117.479502,5.388552
12,A105560,KB금융,"43,600","418,111,537",0.000000e+00,3.571303e+13,4.795883e+14,4.438753e+14,0.000000,85415.071912,0.510449
13,A207940,삼성바이오로직스,"273,000","66,165,000",1.451599e+11,4.155468e+12,5.980409e+12,1.824940e+12,0.034932,62804.631618,4.346813
14,A015760,한국전력,"27,950","641,964,077",2.419889e+12,7.109276e+13,1.852491e+14,1.141563e+14,0.034038,110742.585991,0.252387
15,A028260,삼성물산,"92,300","189,690,043",3.985309e+12,2.254894e+13,4.240665e+13,1.985772e+13,0.176740,118872.528528,0.776462
16,A000270,기아차,"42,850","405,363,347",7.992530e+12,2.724346e+13,5.178660e+13,2.454314e+13,0.293374,67207.516914,0.637577
17,A018260,삼성에스디에스,"212,000","77,377,800",1.664389e+12,6.148552e+12,8.013849e+12,1.865297e+12,0.270696,79461.449977,2.667960
18,A006400,삼성SDI,"229,000","68,764,530",2.040084e+12,1.222522e+13,1.934972e+13,7.124502e+12,0.166875,177783.796617,1.288081
19,A096770,SK이노베이션,"169,000","92,465,564",3.981682e+12,1.932798e+13,3.608538e+13,1.675740e+13,0.206006,209028.981481,0.808500
20,A034730,SK,"221,500","70,360,297",9.650795e+12,5.088787e+13,1.194570e+14,6.856912e+13,0.189648,723246.975492,0.306258
21,A032830,삼성생명,"77,000","200,000,000",0.000000e+00,3.050546e+13,2.894277e+14,2.589222e+14,0.000000,152527.295000,0.504828
22,A033780,KT&G,"96,800","137,292,497",2.635484e+12,8.133080e+12,1.015510e+13,2.022021e+12,0.324045,59239.072802,1.634057
23,A003550,LG,"73,300","172,557,131",2.386962e+12,1.816448e+13,2.283591e+13,4.671433e+12,0.131408,105266.458098,0.696328
24,A000810,삼성화재,"262,500","47,374,837",0.000000e+00,1.238305e+13,7.941639e+13,6.703334e+13,0.000000,261384.496331,1.004268
25,A066570,LG전자,"68,600","163,647,814",1.508104e+13,1.630691e+13,4.432844e+13,2.802154e+13,0.924826,99646.347858,0.688435
26,A035720,카카오,"129,000","83,475,610",2.416992e+12,5.627158e+12,7.959542e+12,2.332385e+12,0.429523,67410.798963,1.913640
27,A036570,엔씨소프트,"485,000","21,946,522",1.715116e+12,2.378971e+12,2.941279e+12,5.623073e+11,0.720948,108398.561057,4.474229
28,A086790,하나금융지주,"35,100","300,242,062",0.000000e+00,2.710846e+13,3.850086e+14,3.579002e+14,0.000000,90288.681804,0.388753
29,A010950,S-Oil,"91,700","112,582,792",1.263049e+12,6.469234e+12,1.595504e+13,9.485810e+12,0.195239,57462.014266,1.595837
...,...,...,...,...,...,...,...,...,...,...,...
2378,A001755,한양증권우,"8,090","525,000",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2379,A245450,씨앤에스링크,"2,640","1,579,960",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2380,A001065,JW중외제약우,"24,800","167,375",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2381,A271850,다이오진,"1,375","3,000,000",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2382,A000995,DB하이텍1우,"36,050","112,316",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2383,A002787,진흥기업2우B,"13,500","294,808",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2384,A084440,유비온,"1,300","2,997,107",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2385,A000545,흥국화재우,"4,975","768,000",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2386,A092590,럭스피아,517,"7,291,098",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2387,A001067,JW중외제약2우B,"39,350","87,790",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2388,A189350,코셋,835,"4,000,000",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2389,A149940,모다,155,"21,160,409",7.766928e+10,6.091668e+10,2.299720e+11,1.690554e+11,1.275008,2878.804611,0.053842
2390,A00781K,코리아써키트2우B,"4,100","783,699",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2391,A000325,노루홀딩스우,"17,200","185,250",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2392,A032685,소프트센우,"22,000","142,857",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2393,A227420,포레스팅블록체인,399,"7,587,936",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2394,A001527,동양2우B,"9,810","308,569",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2395,A000547,흥국화재2우B,"19,200","153,600",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2396,A000227,유유제약2우B,"17,900","164,080",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2397,A001799,대한제당3우B,"21,500","129,656",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2398,A223220,아이피몬스터,256,"10,787,261",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2399,A208890,에듀파트너,"1,310","1,990,820",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2400,A276240,엘리비젼,997,"2,587,200",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2401,A001529,동양3우B,"27,600","89,722",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2402,A247300,인프라웨어테크놀러지,370,"6,118,198",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2403,A224020,에스케이씨에스,830,"2,700,000",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2404,A135270,세종머티리얼즈,104,"7,146,051",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2404,A002250,NaN,NaN,NaN,9.219373e+10,2.169061e+11,2.768905e+11,5.998438e+10,0.425040,NaN,NaN
2404,A026180,NaN,NaN,NaN,4.455009e+09,4.352216e+10,1.772086e+11,1.336864e+11,0.102362,NaN,NaN
2404,A079660,NaN,NaN,NaN,7.692682e+10,1.553774e+11,4.001202e+11,2.447428e+11,0.495097,NaN,NaN

In [9]:
corp_total = corp_total[pd.notnull(corp_total['PBR']) | pd.notnull(corp_total['GP/A'])]
corp_total

,종목코드,종목명,현재가,상장주식수,매출총이익,자본총계,자산총계,부채총계,GP/A,BPS,PBR
0,A005930,삼성전자,"46,100","5,969,782,550",1.113770e+14,2.477532e+14,3.393572e+14,9.160407e+13,0.449548,41501.206271,1.110811
1,A000660,SK하이닉스,"77,000","728,002,365",2.526423e+13,4.685233e+13,6.365834e+13,1.680600e+13,0.539231,64357.388454,1.196444
3,A005380,현대차,"128,000","213,668,187",1.514213e+13,7.389601e+13,1.806558e+14,1.067597e+14,0.204911,345844.699848,0.370108
4,A051910,LG화학,"333,000","70,592,343",5.346197e+12,1.732213e+13,2.894414e+13,1.162201e+13,0.308634,245382.533910,1.357065
5,A012330,현대모비스,"242,500","95,306,694",4.567004e+12,3.070343e+13,4.307113e+13,1.236770e+13,0.148746,322153.950697,0.752746
6,A068270,셀트리온,"179,000","128,329,070",5.491659e+11,2.632778e+12,3.540627e+12,9.078488e+11,0.208588,20515.833723,8.724968
7,A035420,NAVER,"138,500","164,813,395",5.586905e+12,5.949141e+12,9.881191e+12,3.932050e+12,0.939111,36096.219685,3.836967
8,A055550,신한지주,"43,900","474,199,587",0.000000e+00,3.665143e+13,4.596005e+14,4.229491e+14,0.000000,77291.147029,0.567982
9,A005490,POSCO,"228,500","87,186,835",7.972381e+12,4.675955e+13,7.824827e+13,3.148871e+13,0.170497,536314.351473,0.426056
10,A017670,SK텔레콤,"246,000","80,745,711",1.687396e+13,2.234925e+13,4.236911e+13,2.001986e+13,0.755012,276785.599176,0.888775
11,A051900,LG생활건강,"1,240,000","15,618,197",4.051123e+12,3.594020e+12,5.275874e+12,1.681854e+12,1.127184,230117.479502,5.388552
12,A105560,KB금융,"43,600","418,111,537",0.000000e+00,3.571303e+13,4.795883e+14,4.438753e+14,0.000000,85415.071912,0.510449
13,A207940,삼성바이오로직스,"273,000","66,165,000",1.451599e+11,4.155468e+12,5.980409e+12,1.824940e+12,0.034932,62804.631618,4.346813
14,A015760,한국전력,"27,950","641,964,077",2.419889e+12,7.109276e+13,1.852491e+14,1.141563e+14,0.034038,110742.585991,0.252387
15,A028260,삼성물산,"92,300","189,690,043",3.985309e+12,2.254894e+13,4.240665e+13,1.985772e+13,0.176740,118872.528528,0.776462
16,A000270,기아차,"42,850","405,363,347",7.992530e+12,2.724346e+13,5.178660e+13,2.454314e+13,0.293374,67207.516914,0.637577
17,A018260,삼성에스디에스,"212,000","77,377,800",1.664389e+12,6.148552e+12,8.013849e+12,1.865297e+12,0.270696,79461.449977,2.667960
18,A006400,삼성SDI,"229,000","68,764,530",2.040084e+12,1.222522e+13,1.934972e+13,7.124502e+12,0.166875,177783.796617,1.288081
19,A096770,SK이노베이션,"169,000","92,465,564",3.981682e+12,1.932798e+13,3.608538e+13,1.675740e+13,0.206006,209028.981481,0.808500
20,A034730,SK,"221,500","70,360,297",9.650795e+12,5.088787e+13,1.194570e+14,6.856912e+13,0.189648,723246.975492,0.306258
21,A032830,삼성생명,"77,000","200,000,000",0.000000e+00,3.050546e+13,2.894277e+14,2.589222e+14,0.000000,152527.295000,0.504828
22,A033780,KT&G,"96,800","137,292,497",2.635484e+12,8.133080e+12,1.015510e+13,2.022021e+12,0.324045,59239.072802,1.634057
23,A003550,LG,"73,300","172,557,131",2.386962e+12,1.816448e+13,2.283591e+13,4.671433e+12,0.131408,105266.458098,0.696328
24,A000810,삼성화재,"262,500","47,374,837",0.000000e+00,1.238305e+13,7.941639e+13,6.703334e+13,0.000000,261384.496331,1.004268
25,A066570,LG전자,"68,600","163,647,814",1.508104e+13,1.630691e+13,4.432844e+13,2.802154e+13,0.924826,99646.347858,0.688435
26,A035720,카카오,"129,000","83,475,610",2.416992e+12,5.627158e+12,7.959542e+12,2.332385e+12,0.429523,67410.798963,1.913640
27,A036570,엔씨소프트,"485,000","21,946,522",1.715116e+12,2.378971e+12,2.941279e+12,5.623073e+11,0.720948,108398.561057,4.474229
28,A086790,하나금융지주,"35,100","300,242,062",0.000000e+00,2.710846e+13,3.850086e+14,3.579002e+14,0.000000,90288.681804,0.388753
29,A010950,S-Oil,"91,700","112,582,792",1.263049e+12,6.469234e+12,1.595504e+13,9.485810e+12,0.195239,57462.014266,1.595837
30,A316140,우리금융지주,"13,150","680,164,306",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf
...,...,...,...,...,...,...,...,...,...,...,...
2282,A192410,감마누,408,"24,435,800",1.118473e+10,4.486004e+10,1.126900e+11,6.782991e+10,0.249325,1835.832876,0.222242
2283,A307870,상상인이안1호스팩,"2,090","4,750,000",0.000000e+00,8.839206e+09,9.737214e+09,8.980080e+08,0.000000,1860.885474,1.123121
2285,A270520,하나금융10호스팩,"2,150","4,602,000",0.000000e+00,8.537089e+09,9.515985e+09,9.788960e+08,0.000000,1855.082355,1.158978
2286,A299170,IBKS제10호스팩,"2,285","4,330,000",0.000000e+00,8.332973e+09,9.832536e+09,1.499562e+09,0.000000,1924.474134,1.187337
2288,A309930,삼성머스트스팩3호,"2,150","4,590,000",0.000000e+00,8.272471e+09,8.969194e+09,6.967230e+08,0.000000,1802.281264,1.192933
2289,A281410,한국제6호스팩,"2,175","4,510,000",0.000000e+00,8.479220e+09,8.939444e+09,4.602240e+08,0.000000,1880.093126,1.156858
2290,A313750,유안타제4호스팩,"2,095","4,650,000",0.000000e+00,6.853530e+08,1.788497e+09,1.103143e+09,0.000000,147.387742,14.214208
2291,A267320,교보7호스팩,"2,420","4,020,000",0.000000e+00,7.851738e+09,9.982683e+09,2.130944e+09,0.000000,1953.168657,1.239012
2292,A083470,KJ프리텍,387,"24,704,729",-5.055786e+09,1.145038e+10,5.707226e+10,4.562188e+10,-0.441539,463.489318,0.834971
2296,A265920,한화수성스팩,"2,120","4,440,000",0.000000e+00,8.509965e+09,9.778437e+09,1.268472e+09,0.000000,1916.658784,1.106092
2297,A307180,신영스팩4호,"2,150","4,355,000",0.000000e+00,8.611395e+09,9.841878e+09,1.230484e+09,0.000000,1977.358209,1.087309
2299,A261200,하나금융9호스팩,"2,160","4,260,000",0.000000e+00,8.223134e+09,9.052701e+09,8.295670e+08,0.000000,1930.313146,1.118989
2302,A287410,유안타제3호스팩,"2,145","4,235,000",0.000000e+00,7.663354e+09,8.251681e+09,5.883270e+08,0.000000,1809.528689,1.185392
2306,A271740,한국제5호스팩,"2,200","4,000,000",0.000000e+00,7.463662e+09,7.938300e+09,4.746380e+08,0.000000,1865.915500,1.179046
2310,A276920,IBKS제7호스팩,"2,285","3,650,000",0.000000e+00,7.202018e+09,8.476683e+09,1.274665e+09,0.000000,1973.155616,1.158043
2314,A307280,교보8호스팩,"2,180","3,720,000",0.000000e+00,6.774388e+09,7.836408e+09,1.062020e+09,0.000000,1821.072043,1.197097
2320,A257730,신한제3호스팩,"2,260","3,505,000",0.000000e+00,6.485074e+09,7.152366e+09,6.672920e+08,0.000000,1850.235093,1.221466
2322,A311270,키움제5호스팩,"2,175","3,600,000",0.000000e+00,7.103863e+09,7.873138e+09,7.692750e+08,0.000000,1973.295278,1.102217
2326,A030270,에스마크,998,"7,562,701",2.662886e+09,2.678153e+10,6.165978e+10,3.487825e+10,0.099430,3541.265350,0.281820
2330,A310200,미래에셋대우스팩2호,"2,465","3,050,000",0.000000e+00,5.804306e+09,6.968101e+09,1.163795e+09,0.000000,1903.051148,1.295288
2331,A279410,한화에이스스팩4호,"2,135","3,495,000",0.000000e+00,6.650291e+09,7.865365e+09,1.215075e+09,0.000000,1902.801431,1.122030
2332,A258790,케이비제11호스팩,"2,315","3,210,000",0.000000e+00,6.073383e+09,6.820242e+09,7.468590e+08,0.000000,1892.019626,1.223560
2333,A232330,SK3호스팩,"2,060","3,600,000",0.000000e+00,6.904183e+09,7.991530e+09,1.087347e+09,0.000000,1917.828611,1.074131
2336,A310840,엔에이치스팩13호,"2,150","3,420,000",0.000000e+00,6.475928e+09,7.883704e+09,1.407776e+09,0.000000,1893.546199,1.135436
2338,A310870,한국제8호스팩,"2,135","3,420,000",0.000000e+00,6.350131e+09,6.879631e+09,5.295000e+08,0.000000,1856.763450,1.149850
2342,A264290,한화에이스스팩3호,"2,295","3,080,000",0.000000e+00,5.828101e+09,6.907653e+09,1.079552e+09,0.000000,1892.240584,1.212848
2389,A149940,모다,155,"21,160,409",7.766928e+10,6.091668e+10,2.299720e+11,1.690554e+11,1.275008,2878.804611,0.053842
2404,A002250,NaN,NaN,NaN,9.219373e+10,2.169061e+11,2.768905e+11,5.998438e+10,0.425040,NaN,NaN
2404,A026180,NaN,NaN,NaN,4.455009e+09,4.352216e+10,1.772086e+11,1.336864e+11,0.102362,NaN,NaN
2404,A079660,NaN,NaN,NaN,7.692682e+10,1.553774e+11,4.001202e+11,2.447428e+11,0.495097,NaN,NaN

In [10]:
corp_total["GP/A Rank"] = corp_total["GP/A"].rank()

In [11]:
#Rank
corp_total["GP/A Rank"] = corp_total["GP/A"].rank()
corp_total["PBR Rank"] = corp_total["PBR"].rank(ascending=False)
corp_total["Total Rank"] = corp_total["GP/A Rank"] + corp_total["PBR Rank"]
corp_total

,종목코드,종목명,현재가,상장주식수,매출총이익,자본총계,자산총계,부채총계,GP/A,BPS,PBR,GP/A Rank,PBR Rank,Total Rank
0,A005930,삼성전자,"46,100","5,969,782,550",1.113770e+14,2.477532e+14,3.393572e+14,9.160407e+13,0.449548,41501.206271,1.110811,1545.0,951.0,2496.0
1,A000660,SK하이닉스,"77,000","728,002,365",2.526423e+13,4.685233e+13,6.365834e+13,1.680600e+13,0.539231,64357.388454,1.196444,1677.0,872.0,2549.0
3,A005380,현대차,"128,000","213,668,187",1.514213e+13,7.389601e+13,1.806558e+14,1.067597e+14,0.204911,345844.699848,0.370108,809.0,1846.0,2655.0
4,A051910,LG화학,"333,000","70,592,343",5.346197e+12,1.732213e+13,2.894414e+13,1.162201e+13,0.308634,245382.533910,1.357065,1198.0,753.0,1951.0
5,A012330,현대모비스,"242,500","95,306,694",4.567004e+12,3.070343e+13,4.307113e+13,1.236770e+13,0.148746,322153.950697,0.752746,593.0,1310.0,1903.0
6,A068270,셀트리온,"179,000","128,329,070",5.491659e+11,2.632778e+12,3.540627e+12,9.078488e+11,0.208588,20515.833723,8.724968,828.0,60.0,888.0
7,A035420,NAVER,"138,500","164,813,395",5.586905e+12,5.949141e+12,9.881191e+12,3.932050e+12,0.939111,36096.219685,3.836967,1879.0,184.0,2063.0
8,A055550,신한지주,"43,900","474,199,587",0.000000e+00,3.665143e+13,4.596005e+14,4.229491e+14,0.000000,77291.147029,0.567982,117.5,1563.0,1680.5
9,A005490,POSCO,"228,500","87,186,835",7.972381e+12,4.675955e+13,7.824827e+13,3.148871e+13,0.170497,536314.351473,0.426056,683.0,1771.0,2454.0
10,A017670,SK텔레콤,"246,000","80,745,711",1.687396e+13,2.234925e+13,4.236911e+13,2.001986e+13,0.755012,276785.599176,0.888775,1820.0,1171.0,2991.0
11,A051900,LG생활건강,"1,240,000","15,618,197",4.051123e+12,3.594020e+12,5.275874e+12,1.681854e+12,1.127184,230117.479502,5.388552,1916.0,114.0,2030.0
12,A105560,KB금융,"43,600","418,111,537",0.000000e+00,3.571303e+13,4.795883e+14,4.438753e+14,0.000000,85415.071912,0.510449,117.5,1635.0,1752.5
13,A207940,삼성바이오로직스,"273,000","66,165,000",1.451599e+11,4.155468e+12,5.980409e+12,1.824940e+12,0.034932,62804.631618,4.346813,247.0,148.0,395.0
14,A015760,한국전력,"27,950","641,964,077",2.419889e+12,7.109276e+13,1.852491e+14,1.141563e+14,0.034038,110742.585991,0.252387,241.0,1953.0,2194.0
15,A028260,삼성물산,"92,300","189,690,043",3.985309e+12,2.254894e+13,4.240665e+13,1.985772e+13,0.176740,118872.528528,0.776462,703.0,1285.0,1988.0
16,A000270,기아차,"42,850","405,363,347",7.992530e+12,2.724346e+13,5.178660e+13,2.454314e+13,0.293374,67207.516914,0.637577,1148.0,1458.0,2606.0
17,A018260,삼성에스디에스,"212,000","77,377,800",1.664389e+12,6.148552e+12,8.013849e+12,1.865297e+12,0.270696,79461.449977,2.667960,1075.0,315.0,1390.0
18,A006400,삼성SDI,"229,000","68,764,530",2.040084e+12,1.222522e+13,1.934972e+13,7.124502e+12,0.166875,177783.796617,1.288081,661.0,799.0,1460.0
19,A096770,SK이노베이션,"169,000","92,465,564",3.981682e+12,1.932798e+13,3.608538e+13,1.675740e+13,0.206006,209028.981481,0.808500,813.0,1255.0,2068.0
20,A034730,SK,"221,500","70,360,297",9.650795e+12,5.088787e+13,1.194570e+14,6.856912e+13,0.189648,723246.975492,0.306258,745.0,1900.0,2645.0
21,A032830,삼성생명,"77,000","200,000,000",0.000000e+00,3.050546e+13,2.894277e+14,2.589222e+14,0.000000,152527.295000,0.504828,117.5,1644.0,1761.5
22,A033780,KT&G,"96,800","137,292,497",2.635484e+12,8.133080e+12,1.015510e+13,2.022021e+12,0.324045,59239.072802,1.634057,1254.0,614.0,1868.0
23,A003550,LG,"73,300","172,557,131",2.386962e+12,1.816448e+13,2.283591e+13,4.671433e+12,0.131408,105266.458098,0.696328,532.0,1395.0,1927.0
24,A000810,삼성화재,"262,500","47,374,837",0.000000e+00,1.238305e+13,7.941639e+13,6.703334e+13,0.000000,261384.496331,1.004268,117.5,1051.0,1168.5
25,A066570,LG전자,"68,600","163,647,814",1.508104e+13,1.630691e+13,4.432844e+13,2.802154e+13,0.924826,99646.347858,0.688435,1876.0,1402.0,3278.0
26,A035720,카카오,"129,000","83,475,610",2.416992e+12,5.627158e+12,7.959542e+12,2.332385e+12,0.429523,67410.798963,1.913640,1496.0,502.0,1998.0
27,A036570,엔씨소프트,"485,000","21,946,522",1.715116e+12,2.378971e+12,2.941279e+12,5.623073e+11,0.720948,108398.561057,4.474229,1801.0,140.0,1941.0
28,A086790,하나금융지주,"35,100","300,242,062",0.000000e+00,2.710846e+13,3.850086e+14,3.579002e+14,0.000000,90288.681804,0.388753,117.5,1824.0,1941.5
29,A010950,S-Oil,"91,700","112,582,792",1.263049e+12,6.469234e+12,1.595504e+13,9.485810e+12,0.195239,57462.014266,1.595837,768.0,634.0,1402.0
30,A316140,우리금융지주,"13,150","680,164,306",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,8.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2282,A192410,감마누,408,"24,435,800",1.118473e+10,4.486004e+10,1.126900e+11,6.782991e+10,0.249325,1835.832876,0.222242,975.0,1970.0,2945.0
2283,A307870,상상인이안1호스팩,"2,090","4,750,000",0.000000e+00,8.839206e+09,9.737214e+09,8.980080e+08,0.000000,1860.885474,1.123121,117.5,937.0,1054.5
2285,A270520,하나금융10호스팩,"2,150","4,602,000",0.000000e+00,8.537089e+09,9.515985e+09,9.788960e+08,0.000000,1855.082355,1.158978,117.5,909.0,1026.5
2286,A299170,IBKS제10호스팩,"2,285","4,330,000",0.000000e+00,8.332973e+09,9.832536e+09,1.499562e+09,0.000000,1924.474134,1.187337,117.5,878.0,995.5
2288,A309930,삼성머스트스팩3호,"2,150","4,590,000",0.000000e+00,8.272471e+09,8.969194e+09,6.967230e+08,0.000000,1802.281264,1.192933,117.5,876.0,993.5
2289,A281410,한국제6호스팩,"2,175","4,510,000",0.000000e+00,8.479220e+09,8.939444e+09,4.602240e+08,0.000000,1880.093126,1.156858,117.5,912.0,1029.5
2290,A313750,유안타제4호스팩,"2,095","4,650,000",0.000000e+00,6.853530e+08,1.788497e+09,1.103143e+09,0.000000,147.387742,14.214208,117.5,35.0,152.5
2291,A267320,교보7호스팩,"2,420","4,020,000",0.000000e+00,7.851738e+09,9.982683e+09,2.130944e+09,0.000000,1953.168657,1.239012,117.5,833.0,950.5
2292,A083470,KJ프리텍,387,"24,704,729",-5.055786e+09,1.145038e+10,5.707226e+10,4.562188e+10,-0.441539,463.489318,0.834971,7.0,1227.0,1234.0
2296,A265920,한화수성스팩,"2,120","4,440,000",0.000000e+00,8.509965e+09,9.778437e+09,1.268472e+09,0.000000,1916.658784,1.106092,117.5,954.0,1071.5
2297,A307180,신영스팩4호,"2,150","4,355,000",0.000000e+00,8.611395e+09,9.841878e+09,1.230484e+09,0.000000,1977.358209,1.087309,117.5,972.0,1089.5
2299,A261200,하나금융9호스팩,"2,160","4,260,000",0.000000e+00,8.223134e+09,9.052701e+09,8.295670e+08,0.000000,1930.313146,1.118989,117.5,942.0,1059.5
2302,A287410,유안타제3호스팩,"2,145","4,235,000",0.000000e+00,7.663354e+09,8.251681e+09,5.883270e+08,0.000000,1809.528689,1.185392,117.5,882.0,999.5
2306,A271740,한국제5호스팩,"2,200","4,000,000",0.000000e+00,7.463662e+09,7.938300e+09,4.746380e+08,0.000000,1865.915500,1.179046,117.5,891.0,1008.5
2310,A276920,IBKS제7호스팩,"2,285","3,650,000",0.000000e+00,7.202018e+09,8.476683e+09,1.274665e+09,0.000000,1973.155616,1.158043,117.5,910.0,1027.5
2314,A307280,교보8호스팩,"2,180","3,720,000",0.000000e+00,6.774388e+09,7.836408e+09,1.062020e+09,0.000000,1821.072043,1.197097,117.5,871.0,988.5
2320,A257730,신한제3호스팩,"2,260","3,505,000",0.000000e+00,6.485074e+09,7.152366e+09,6.672920e+08,0.000000,1850.235093,1.221466,117.5,850.0,967.5
2322,A311270,키움제5호스팩,"2,175","3,600,000",0.000000e+00,7.103863e+09,7.873138e+09,7.692750e+08,0.000000,1973.295278,1.102217,117.5,962.0,1079.5
2326,A030270,에스마크,998,"7,562,701",2.662886e+09,2.678153e+10,6.165978e+10,3.487825e+10,0.099430,3541.265350,0.281820,416.0,1930.0,2346.0
2330,A310200,미래에셋대우스팩2호,"2,465","3,050,000",0.000000e+00,5.804306e+09,6.968101e+09,1.163795e+09,0.000000,1903.051148,1.295288,117.5,792.0,909.5
2331,A279410,한화에이스스팩4호,"2,135","3,495,000",0.000000e+00,6.650291e+09,7.865365e+09,1.215075e+09,0.000000,1902.801431,1.122030,117.5,938.0,1055.5
2332,A258790,케이비제11호스팩,"2,315","3,210,000",0.000000e+00,6.073383e+09,6.820242e+09,7.468590e+08,0.000000,1892.019626,1.223560,117.5,846.0,963.5
2333,A232330,SK3호스팩,"2,060","3,600,000",0.000000e+00,6.904183e+09,7.991530e+09,1.087347e+09,0.000000,1917.828611,1.074131,117.5,982.0,1099.5
2336,A310840,엔에이치스팩13호,"2,150","3,420,000",0.000000e+00,6.475928e+09,7.883704e+09,1.407776e+09,0.000000,1893.546199,1.135436,117.5,925.0,1042.5
2338,A310870,한국제8호스팩,"2,135","3,420,000",0.000000e+00,6.350131e+09,6.879631e+09,5.295000e+08,0.000000,1856.763450,1.149850,117.5,916.0,1033.5
2342,A264290,한화에이스스팩3호,"2,295","3,080,000",0.000000e+00,5.828101e+09,6.907653e+09,1.079552e+09,0.000000,1892.240584,1.212848,117.5,861.0,978.5
2389,A149940,모다,155,"21,160,409",7.766928e+10,6.091668e+10,2.299720e+11,1.690554e+11,1.275008,2878.804611,0.053842,1937.0,2005.0,3942.0
2404,A002250,NaN,NaN,NaN,9.219373e+10,2.169061e+11,2.768905e+11,5.998438e+10,0.425040,NaN,NaN,1483.0,NaN,NaN
2404,A026180,NaN,NaN,NaN,4.455009e+09,4.352216e+10,1.772086e+11,1.336864e+11,0.102362,NaN,NaN,429.0,NaN,NaN
2404,A079660,NaN,NaN,NaN,7.692682e+10,1.553774e+11,4.001202e+11,2.447428e+11,0.495097,NaN,NaN,1614.0,NaN,NaN

In [25]:
corp_total.sort_values(by=['Total Rank'], ascending=False)

,종목코드,종목명,현재가,상장주식수,매출총이익,자본총계,자산총계,부채총계,GP/A,BPS,PBR,GP/A Rank,PBR Rank,Total Rank
2389,A149940,모다,155,"21,160,409",7.766928e+10,6.091668e+10,2.299720e+11,1.690554e+11,1.275008,2878.804611,0.053842,1969.0,2043.0,4012.0
574,A084690,대상홀딩스,"6,700","36,212,538",8.912242e+11,1.094780e+12,2.629589e+12,1.534809e+12,0.814067,30232.062608,0.221619,1876.0,2009.0,3885.0
788,A005990,매일홀딩스,"11,700","13,718,304",4.548671e+11,5.160672e+11,8.489405e+11,3.328733e+11,0.881411,37618.876721,0.311014,1900.0,1935.0,3835.0
633,A095570,AJ네트웍스,"4,660","46,822,295",1.056691e+12,5.082648e+11,2.575139e+12,2.066875e+12,2.079017,10855.188559,0.429288,2009.0,1801.0,3810.0
2245,A194510,파티게임즈,536,"24,488,350",4.225842e+10,6.304665e+10,1.779223e+11,1.148757e+11,0.670272,2574.556799,0.208191,1794.0,2014.0,3808.0
510,A000140,하이트진로홀딩스,"12,000","23,206,765",7.671412e+11,1.095787e+12,3.989286e+12,2.893500e+12,0.700083,47218.410537,0.254138,1817.0,1989.0,3806.0
89,A001040,CJ,"94,000","29,176,998",8.353219e+12,1.252181e+13,3.172955e+13,1.920774e+13,0.667094,429167.190024,0.219029,1790.0,2010.0,3800.0
888,A001390,KG케미칼,"10,950","12,455,526",3.987176e+11,6.041586e+11,1.508599e+12,9.044405e+11,0.659955,48505.262805,0.225749,1782.0,2005.0,3787.0
822,A005740,크라운해태홀딩스,"10,250","14,847,347",3.690811e+11,4.936934e+11,1.286505e+12,7.928112e+11,0.747592,33251.288463,0.308259,1840.0,1937.0,3777.0
1543,A069640,한세엠케이,"5,050","12,909,322",1.916986e+11,1.485118e+11,2.056286e+11,5.711690e+10,1.290797,11504.225396,0.438969,1971.0,1779.0,3750.0
1739,A036710,심텍홀딩스,"1,440","35,736,919",1.298515e+11,2.303702e+11,8.403261e+11,6.099559e+11,0.563665,6446.280470,0.223385,1728.0,2007.0,3735.0
1407,A058860,KTis,"2,185","34,802,000",4.508260e+11,1.602497e+11,2.292460e+11,6.899632e+10,2.813272,4604.612752,0.474524,2015.0,1719.0,3734.0
1850,A031980,피에스케이홀딩스,"7,960","5,566,584",1.446747e+11,2.715968e+11,3.198342e+11,4.823745e+10,0.532682,48790.568327,0.163146,1700.0,2034.0,3734.0
1733,A084870,TBH글로벌,"2,495","20,856,819",1.165821e+11,1.834459e+11,2.662459e+11,8.279998e+10,0.635512,8795.487126,0.283668,1766.0,1967.0,3733.0
328,A037560,CJ헬로,"5,970","77,446,865",1.061144e+12,1.059260e+12,1.935139e+12,8.758786e+11,1.001779,13677.249221,0.436491,1931.0,1785.0,3716.0
671,A002020,코오롱,"15,850","12,626,426",4.469896e+11,8.353672e+11,3.480352e+12,2.644985e+12,0.535082,66160.226021,0.239570,1703.0,2001.0,3704.0
292,A006840,AK홀딩스,"41,500","13,247,561",1.045615e+12,1.473898e+12,3.397931e+12,1.924034e+12,0.709422,111258.037687,0.373007,1822.0,1880.0,3702.0
37,A030200,KT,"27,550","261,111,808",2.346014e+13,1.473128e+13,3.218883e+13,1.745755e+13,1.592539,56417.517510,0.488324,1996.0,1704.0,3700.0
1298,A058850,KTcs,"1,980","42,685,000",1.016085e+12,1.617186e+11,3.502797e+11,1.885610e+11,6.283044,3788.652267,0.522613,2025.0,1657.0,3682.0
58,A023530,롯데쇼핑,"139,500","28,288,755",7.507670e+12,1.242737e+13,2.625931e+13,1.383194e+13,0.604124,439304.340718,0.317548,1748.0,1929.0,3677.0
945,A035080,인터파크홀딩스,"2,150","58,500,000",3.551659e+11,7.144811e+11,1.809664e+12,1.095183e+12,0.497096,12213.352103,0.176037,1648.0,2028.0,3676.0
986,A115160,휴맥스,"5,030","23,911,798",2.181178e+11,4.010581e+11,1.057084e+12,6.560256e+11,0.543856,16772.395827,0.299898,1708.0,1947.0,3655.0
468,A016450,한세예스24홀딩스,"7,600","40,000,000",6.379932e+11,6.177373e+11,1.678316e+12,1.060579e+12,1.032791,15443.432350,0.492119,1934.0,1698.0,3632.0
1860,A085810,알티캐스트,"2,050","21,223,160",7.620016e+10,9.088899e+10,1.644744e+11,7.358541e+10,0.838387,4282.538180,0.478688,1888.0,1715.0,3603.0
713,A004960,한신공영,"15,700","11,570,702",2.761534e+11,4.460368e+11,1.778426e+12,1.332390e+12,0.619127,38548.809225,0.407276,1755.0,1840.0,3595.0
1001,A013520,화승알앤에이,"1,830","64,561,210",2.653218e+11,2.184843e+11,1.211765e+12,9.932804e+11,1.214375,3384.142351,0.540757,1959.0,1628.0,3587.0
111,A000150,두산,"103,000","18,238,102",3.323509e+12,7.145046e+12,2.888028e+13,2.173524e+13,0.465149,391764.789505,0.262913,1594.0,1984.0,3578.0
1061,A027390,한화갤러리아타임월드,"18,400","6,000,131",1.852218e+11,2.199042e+11,4.518031e+11,2.318989e+11,0.842284,36649.894311,0.502048,1889.0,1685.0,3574.0
1968,A004100,태양금속,"1,025","36,700,000",5.185176e+10,9.781551e+10,3.963263e+11,2.985108e+11,0.530098,2665.272752,0.384576,1699.0,1869.0,3568.0
2005,A024910,경창산업,990,"35,819,005",7.250979e+10,1.634435e+11,6.381576e+11,4.747141e+11,0.443638,4563.038337,0.216961,1555.0,2012.0,3567.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2220,A106080,지투하이소닉,798,"20,645,684",-1.411760e+09,2.786211e+09,3.406171e+10,3.127550e+10,-0.506695,134.953678,5.913140,6.0,109.0,115.0
491,A228760,지노믹트리,"14,600","19,986,215",-4.976700e+07,1.108510e+10,1.395361e+10,2.868506e+09,-0.004490,554.637484,26.323500,63.0,27.0,90.0
2114,A054340,피앤텔,"6,680","4,031,039",-1.128160e+08,2.092697e+09,2.715882e+10,2.506613e+10,-0.053909,519.145808,12.867291,41.0,43.0,84.0
2218,A123260,파인넥스,701,"24,015,495",-1.835430e+08,1.708156e+09,4.663279e+10,4.492463e+10,-0.107451,71.127245,9.855576,26.0,56.0,82.0
593,A065620,제낙스,"10,350","22,486,744",-7.789150e+08,9.193683e+09,2.783782e+10,1.864413e+10,-0.084723,408.849009,25.314969,35.0,28.0,63.0
1563,A109070,컨버즈,"3,260","19,673,513",-1.126729e+09,5.388602e+09,7.193708e+10,6.654848e+10,-0.209095,273.901362,11.902095,14.0,47.0,61.0
2004,A195440,퓨전데이타,370,"96,003,379",-2.281464e+09,6.026210e+08,2.269987e+10,2.209725e+10,-3.785902,6.277081,58.944594,1.0,22.0,23.0
30,A316140,우리금융지주,"13,150","680,164,306",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,10.5,NaN
384,A268280,미원에스씨,"73,000","5,267,891",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,10.5,NaN
479,A016580,환인제약,"16,000","18,600,070",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,10.5,NaN
854,A299900,위지윅스튜디오,"15,500","9,213,507",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,10.5,NaN
922,A101000,상상인인더스트리,"3,125","41,739,200",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,10.5,NaN
995,A082800,루미마이크로,"1,600","74,470,875",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,10.5,NaN
1077,A069920,아이에스이커머스,"4,230","25,514,093",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,10.5,NaN
1188,A290120,대유에이피,"8,620","10,884,000",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,10.5,NaN
1320,A259630,엠플러스,"16,200","5,111,890",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,10.5,NaN
1347,A043090,팜스웰바이오,"2,790","28,986,693",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,10.5,NaN
1530,A053590,한국테크놀로지,925,"71,185,050",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,10.5,NaN
1632,A234100,세원,"2,630","22,382,985",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,10.5,NaN
1732,A253590,네오셈,"1,445","36,049,183",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,10.5,NaN
2000,A086250,화신테크,"2,630","13,566,748",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,10.5,NaN
2076,A033600,럭슬,"1,105","26,959,869",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,10.5,NaN
2136,A010640,진양폴리,"2,500","10,000,000",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,10.5,NaN
2183,A222810,한류AI센터,"1,120","17,984,118",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,10.5,NaN
2193,A058450,일야,"1,190","15,900,000",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,10.5,NaN
2205,A317320,한화에스비아이스팩,"4,100","4,360,000",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,10.5,NaN
2257,A317030,케이비17호스팩,"2,110","5,461,000",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,inf,NaN,10.5,NaN
2404,A002250,NaN,NaN,NaN,9.219373e+10,2.169061e+11,2.768905e+11,5.998438e+10,0.425040,NaN,NaN,1509.0,NaN,NaN
2404,A026180,NaN,NaN,NaN,4.455009e+09,4.352216e+10,1.772086e+11,1.336864e+11,0.102362,NaN,NaN,434.0,NaN,NaN
2404,A079660,NaN,NaN,NaN,7.692682e+10,1.553774e+11,4.001202e+11,2.447428e+11,0.495097,NaN,NaN,1643.0,NaN,NaN

In [22]:
corp_total.sort_values(by=['Total Rank'], ascending=False)[:20]

,종목코드,종목명,현재가,상장주식수,매출총이익,자본총계,자산총계,부채총계,GP/A,BPS,PBR,GP/A Rank,PBR Rank,Total Rank
2389,A149940,모다,155,"21,160,409",7.766928e+10,6.091668e+10,2.299720e+11,1.690554e+11,1.275008,2878.804611,0.053842,1969.0,2043.0,4012.0
574,A084690,대상홀딩스,"6,700","36,212,538",8.912242e+11,1.094780e+12,2.629589e+12,1.534809e+12,0.814067,30232.062608,0.221619,1876.0,2009.0,3885.0
788,A005990,매일홀딩스,"11,700","13,718,304",4.548671e+11,5.160672e+11,8.489405e+11,3.328733e+11,0.881411,37618.876721,0.311014,1900.0,1935.0,3835.0
633,A095570,AJ네트웍스,"4,660","46,822,295",1.056691e+12,5.082648e+11,2.575139e+12,2.066875e+12,2.079017,10855.188559,0.429288,2009.0,1801.0,3810.0
2245,A194510,파티게임즈,536,"24,488,350",4.225842e+10,6.304665e+10,1.779223e+11,1.148757e+11,0.670272,2574.556799,0.208191,1794.0,2014.0,3808.0