In [58]:
import pandas as pd
corp_info = pd.read_csv('corp.csv', header=0)
corp_info

,순위,종목코드,종목명,현재가,대비,등락률,거래량,거래대금,시가,고가,저가,시가총액,시가총액비중(%),상장주식수,외국인 보유주식수,외국인 지분율(%),총카운트
0,1,005930,삼성전자,"46,100","-1,050",-2.20,"6,854,965","317,650,411,250","46,800","47,050","46,000","275,206,975,555,000",17.49,"5,969,782,550",nan,nan,2405.00
1,2,000660,SK하이닉스,"77,000","-2,800",-3.50,"2,616,455","203,392,849,900","79,000","79,400","76,500","56,056,182,105,000",3.56,"728,002,365",nan,nan,nan
2,3,005935,삼성전자우,"38,100",-500,-1.30,"823,913","31,399,459,992","38,600","38,600","37,900","31,351,983,270,000",1.99,"822,886,700",nan,nan,nan
3,4,005380,현대차,"128,000","-2,500",-1.90,"464,277","59,477,099,500","130,000","131,000","126,500","27,349,527,936,000",1.74,"213,668,187",nan,nan,nan
4,5,051910,LG화학,"333,000",0,0.00,"168,074","55,303,005,500","333,500","333,500","325,000","23,507,250,219,000",1.49,"70,592,343",nan,nan,nan
5,6,012330,현대모비스,"242,500","-3,000",-1.20,"169,686","40,865,947,500","245,500","245,500","237,500","23,111,873,295,000",1.47,"95,306,694",nan,nan,nan
6,7,068270,셀트리온,"179,000","-6,000",-3.20,"433,127","78,396,577,000","183,500","184,500","179,000","22,970,903,530,000",1.46,"128,329,070",nan,nan,nan
7,8,035420,NAVER,"138,500","-2,500",-1.80,"583,604","80,883,355,500","139,500","141,000","137,000","22,826,655,207,500",1.45,"164,813,395",nan,nan,nan
8,9,055550,신한지주,"43,900",250,0.60,"871,054","38,233,388,300","43,800","44,150","43,600","20,817,361,869,300",1.32,"474,199,587",nan,nan,nan
9,10,005490,POSCO,"228,500","-4,000",-1.70,"194,010","44,631,084,000","233,000","233,000","228,500","19,922,191,797,500",1.27,"87,186,835",nan,nan,nan
10,11,017670,SK텔레콤,"246,000",500,0.20,"121,033","29,804,367,500","247,500","249,000","244,000","19,863,444,906,000",1.26,"80,745,711",nan,nan,nan
11,12,051900,LG생활건강,"1,240,000","16,000",1.30,"31,789","39,285,922,000","1,230,000","1,248,000","1,226,000","19,366,564,280,000",1.23,"15,618,197",nan,nan,nan
12,13,105560,KB금융,"43,600",-200,-0.50,"630,292","27,480,484,000","43,950","44,100","43,400","18,229,663,013,200",1.16,"418,111,537",nan,nan,nan
13,14,207940,삼성바이오로직스,"273,000","-2,500",-0.90,"83,126","22,733,567,000","273,000","278,000","271,000","18,063,045,000,000",1.15,"66,165,000",nan,nan,nan
14,15,015760,한국전력,"27,950",350,1.30,"1,840,989","51,060,219,550","27,600","27,950","27,300","17,942,895,952,150",1.14,"641,964,077",nan,nan,nan
15,16,028260,삼성물산,"92,300","-2,200",-2.30,"213,772","19,794,618,700","94,000","94,100","91,800","17,508,390,968,900",1.11,"189,690,043",nan,nan,nan
16,17,000270,기아차,"42,850",-750,-1.70,"782,422","33,611,610,600","43,800","43,900","42,500","17,369,819,418,950",1.10,"405,363,347",nan,nan,nan
17,18,018260,삼성에스디에스,"212,000","-3,500",-1.60,"66,628","14,254,540,000","215,500","219,000","212,000","16,404,093,600,000",1.04,"77,377,800",nan,nan,nan
18,19,006400,삼성SDI,"229,000","-3,000",-1.30,"180,305","41,102,882,000","231,500","232,500","225,500","15,747,077,370,000",1.00,"68,764,530",nan,nan,nan
19,20,096770,SK이노베이션,"169,000","-4,000",-2.30,"282,740","47,497,441,561","174,000","174,000","164,500","15,626,680,316,000",0.99,"92,465,564",nan,nan,nan
20,21,034730,SK,"221,500","-3,000",-1.30,"71,878","15,921,621,000","224,500","224,500","219,500","15,584,805,785,500",0.99,"70,360,297",nan,nan,nan
21,22,032830,삼성생명,"77,000",-800,-1.00,"221,890","17,015,807,000","77,700","78,200","76,000","15,400,000,000,000",0.98,"200,000,000",nan,nan,nan
22,23,033780,KT&G,"96,800",0,0.00,"205,333","19,950,938,000","97,100","97,900","96,800","13,289,913,709,600",0.84,"137,292,497",nan,nan,nan
23,24,003550,LG,"73,300",-800,-1.10,"138,814","10,159,491,100","73,700","74,300","72,200","12,648,437,702,300",0.80,"172,557,131",nan,nan,nan
24,25,000810,삼성화재,"262,500",-500,-0.20,"64,363","16,805,742,750","262,500","263,500","258,000","12,435,894,712,500",0.79,"47,374,837",nan,nan,nan
25,26,066570,LG전자,"68,600",0,0.00,"377,472","25,967,194,700","68,300","69,700","68,000","11,226,240,040,400",0.71,"163,647,814",nan,nan,nan
26,27,035720,카카오,"129,000","-2,000",-1.50,"368,365","47,659,535,500","130,000","132,000","128,000","10,768,353,690,000",0.68,"83,475,610",nan,nan,nan
27,28,036570,엔씨소프트,"485,000","-7,000",-1.40,"53,965","26,253,350,000","490,000","495,000","481,000","10,644,063,170,000",0.68,"21,946,522",nan,nan,nan
28,29,086790,하나금융지주,"35,100",-250,-0.70,"926,666","32,582,323,800","35,350","35,500","34,900","10,538,496,376,200",0.67,"300,242,062",nan,nan,nan
29,30,010950,S-Oil,"91,700","-1,300",-1.40,"276,318","25,198,697,800","92,900","92,900","90,300","10,323,842,026,400",0.66,"112,582,792",nan,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2375,2376,002785,진흥기업우B,"5,190",-240,-4.40,"23,393","121,733,250","5,400","5,470","5,020","4,448,961,420",0.00,"857,218",nan,nan,nan
2376,2377,005965,동부건설우,"19,250",350,1.80,"2,337","43,569,150","18,900","19,500","18,200","4,345,341,000",0.00,"225,732",nan,nan,nan
2377,2378,099350,하나니켈2호,"1,305",-135,-9.40,"68,876","93,513,190","1,415","1,450","1,300","4,285,620,000",0.00,"3,284,000",nan,nan,nan
2378,2379,001755,한양증권우,"8,090",-260,-3.10,"3,313","26,739,700","8,360","8,360","7,910","4,247,250,000",0.00,"525,000",nan,nan,nan
2379,2380,245450,씨앤에스링크,"2,640",-460,-14.80,472,"1,252,540","3,100","3,100","2,640","4,171,094,400",0.00,"1,579,960",nan,nan,nan
2380,2381,001065,JW중외제약우,"24,800",-950,-3.70,"1,199","29,888,500","25,300","26,000","24,650","4,150,900,000",0.00,"167,375",nan,nan,nan
2381,2382,271850,다이오진,"1,375",-80,-5.50,"4,621","5,795,605","1,515","1,515","1,250","4,125,000,000",0.00,"3,000,000",nan,nan,nan
2382,2383,000995,DB하이텍1우,"36,050","-1,250",-3.40,979,"34,877,750","37,000","37,000","34,600","4,048,991,800",0.00,"112,316",nan,nan,nan
2383,2384,002787,진흥기업2우B,"13,500",-400,-2.90,"5,760","77,446,750","13,900","13,900","13,250","3,979,908,000",0.00,"294,808",nan,nan,nan
2384,2385,084440,유비온,"1,300",0,0.00,10,"13,000","1,300","1,300","1,300","3,896,239,100",0.00,"2,997,107",nan,nan,nan
2385,2386,000545,흥국화재우,"4,975",-95,-1.90,"2,249","11,100,205","5,230","5,230","4,800","3,820,800,000",0.00,"768,000",nan,nan,nan
2386,2387,092590,럭스피아,517,-61,-10.60,15,"9,653",664,664,517,"3,769,497,666",0.00,"7,291,098",nan,nan,nan
2387,2388,001067,JW중외제약2우B,"39,350",-600,-1.50,590,"23,487,150","39,950","41,400","39,250","3,454,536,500",0.00,"87,790",nan,nan,nan
2388,2389,189350,코셋,835,-80,-8.70,"1,026","1,073,961","1,050","1,050",788,"3,340,000,000",0.00,"4,000,000",nan,nan,nan
2389,2390,149940,모다,155,0,0.00,0,0,0,0,0,"3,279,863,395",0.00,"21,160,409",nan,nan,nan
2390,2391,00781K,코리아써키트2우B,"4,100",-210,-4.90,439,"1,785,855","4,065","4,140","4,065","3,213,165,900",0.00,"783,699",nan,nan,nan
2391,2392,000325,노루홀딩스우,"17,200",-800,-4.40,300,"5,202,350","18,400","18,400","17,200","3,186,300,000",0.00,"185,250",nan,nan,nan
2392,2393,032685,소프트센우,"22,000",-150,-0.70,"1,417","31,284,200","22,150","23,500","21,650","3,142,854,000",0.00,"142,857",nan,nan,nan
2393,2394,227420,포레스팅블록체인,399,-31,-7.20,2,798,399,399,399,"3,027,586,464",0.00,"7,587,936",nan,nan,nan
2394,2395,001527,동양2우B,"9,810",-290,-2.90,683,"6,778,610","10,500","10,500","9,700","3,027,061,890",0.00,"308,569",nan,nan,nan
2395,2396,000547,흥국화재2우B,"19,200","-1,650",-7.90,"1,082","21,402,850","20,850","20,850","19,200","2,949,120,000",0.00,"153,600",nan,nan,nan
2396,2397,000227,유유제약2우B,"17,900",-400,-2.20,350,"6,340,400","18,000","19,050","17,900","2,937,032,000",0.00,"164,080",nan,nan,nan
2397,2398,001799,대한제당3우B,"21,500","-1,600",-6.90,"1,415","31,142,150","23,200","23,200","21,500","2,787,604,000",0.00,"129,656",nan,nan,nan
2398,2399,223220,아이피몬스터,256,0,0.00,0,0,0,0,0,"2,761,538,816",0.00,"10,787,261",nan,nan,nan
2399,2400,208890,에듀파트너,"1,310",-220,-14.40,11,"15,310","1,400","1,400","1,310","2,607,974,200",0.00,"1,990,820",nan,nan,nan
2400,2401,276240,엘리비젼,997,1,0.10,"1,123","1,120,472",854,"1,140",854,"2,579,438,400",0.00,"2,587,200",nan,nan,nan
2401,2402,001529,동양3우B,"27,600",-950,-3.30,"1,889","52,265,350","28,150","29,000","27,200","2,476,327,200",0.00,"89,722",nan,nan,nan
2402,2403,247300,인프라웨어테크놀러지,370,-36,-8.90,"2,860","1,058,200",370,370,370,"2,263,733,260",0.00,"6,118,198",nan,nan,nan
2403,2404,224020,에스케이씨에스,830,-140,-14.40,"1,151","1,004,780",873,873,830,"2,241,000,000",0.00,"2,700,000",nan,nan,nan
2404,2405,135270,세종머티리얼즈,104,0,0.00,0,0,0,0,0,"743,189,304",0.00,"7,146,051",nan,nan,nan

In [59]:
corp_info = corp_info[['종목코드','종목명','현재가','상장주식수']]
corp_info

        종목코드         종목명        현재가          상장주식수
0     005930        삼성전자     46,100  5,969,782,550
1     000660      SK하이닉스     77,000    728,002,365
2     005935       삼성전자우     38,100    822,886,700
3     005380         현대차    128,000    213,668,187
4     051910        LG화학    333,000     70,592,343
5     012330       현대모비스    242,500     95,306,694
6     068270        셀트리온    179,000    128,329,070
7     035420       NAVER    138,500    164,813,395
8     055550        신한지주     43,900    474,199,587
9     005490       POSCO    228,500     87,186,835
10    017670       SK텔레콤    246,000     80,745,711
11    051900      LG생활건강  1,240,000     15,618,197
12    105560        KB금융     43,600    418,111,537
13    207940    삼성바이오로직스    273,000     66,165,000
14    015760        한국전력     27,950    641,964,077
15    028260        삼성물산     92,300    189,690,043
16    000270         기아차     42,850    405,363,347
17    018260     삼성에스디에스    212,000     77,377,800
18    006400       삼성SDI    229,000     68,764,530
19    096770     SK이노베이션    169,000     92,465,564
20    034730          SK    221,500     70,360,297
21    032830        삼성생명     77,000    200,000,000
22    033780        KT&G     96,800    137,292,497
23    003550          LG     73,300    172,557,131
24    000810        삼성화재    262,500     47,374,837
25    066570        LG전자     68,600    163,647,814
26    035720         카카오    129,000     83,475,610
27    036570       엔씨소프트    485,000     21,946,522
28    086790      하나금융지주     35,100    300,242,062
29    010950       S-Oil     91,700    112,582,792
...      ...         ...        ...            ...
2375  002785      진흥기업우B      5,190        857,218
2376  005965       동부건설우     19,250        225,732
2377  099350      하나니켈2호      1,305      3,284,000
2378  001755       한양증권우      8,090        525,000
2379  245450      씨앤에스링크      2,640      1,579,960
2380  001065     JW중외제약우     24,800        167,375
2381  271850        다이오진      1,375      3,000,000
2382  000995     DB하이텍1우     36,050        112,316
2383  002787     진흥기업2우B     13,500        294,808
2384  084440         유비온      1,300      2,997,107
2385  000545       흥국화재우      4,975        768,000
2386  092590        럭스피아        517      7,291,098
2387  001067   JW중외제약2우B     39,350         87,790
2388  189350          코셋        835      4,000,000
2389  149940          모다        155     21,160,409
2390  00781K   코리아써키트2우B      4,100        783,699
2391  000325      노루홀딩스우     17,200        185,250
2392  032685       소프트센우     22,000        142,857
2393  227420    포레스팅블록체인        399      7,587,936
2394  001527       동양2우B      9,810        308,569
2395  000547     흥국화재2우B     19,200        153,600
2396  000227     유유제약2우B     17,900        164,080
2397  001799     대한제당3우B     21,500        129,656
2398  223220      아이피몬스터        256     10,787,261
2399  208890       에듀파트너      1,310      1,990,820
2400  276240        엘리비젼        997      2,587,200
2401  001529       동양3우B     27,600         89,722
2402  247300  인프라웨어테크놀러지        370      6,118,198
2403  224020     에스케이씨에스        830      2,700,000
2404  135270     세종머티리얼즈        104      7,146,051

[2405 rows x 4 columns]

In [60]:
corp_info['종목코드'] = 'A' + corp_info['종목코드'].astype(str)
corp_info

c:\envs\stocklab\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

         종목코드         종목명        현재가          상장주식수
0     A005930        삼성전자     46,100  5,969,782,550
1     A000660      SK하이닉스     77,000    728,002,365
2     A005935       삼성전자우     38,100    822,886,700
3     A005380         현대차    128,000    213,668,187
4     A051910        LG화학    333,000     70,592,343
5     A012330       현대모비스    242,500     95,306,694
6     A068270        셀트리온    179,000    128,329,070
7     A035420       NAVER    138,500    164,813,395
8     A055550        신한지주     43,900    474,199,587
9     A005490       POSCO    228,500     87,186,835
10    A017670       SK텔레콤    246,000     80,745,711
11    A051900      LG생활건강  1,240,000     15,618,197
12    A105560        KB금융     43,600    418,111,537
13    A207940    삼성바이오로직스    273,000     66,165,000
14    A015760        한국전력     27,950    641,964,077
15    A028260        삼성물산     92,300    189,690,043
16    A000270         기아차     42,850    405,363,347
17    A018260     삼성에스디에스    212,000     77,377,800
18    A006400       삼성SDI    229,000     68,764,530
19    A096770     SK이노베이션    169,000     92,465,564
20    A034730          SK    221,500     70,360,297
21    A032830        삼성생명     77,000    200,000,000
22    A033780        KT&G     96,800    137,292,497
23    A003550          LG     73,300    172,557,131
24    A000810        삼성화재    262,500     47,374,837
25    A066570        LG전자     68,600    163,647,814
26    A035720         카카오    129,000     83,475,610
27    A036570       엔씨소프트    485,000     21,946,522
28    A086790      하나금융지주     35,100    300,242,062
29    A010950       S-Oil     91,700    112,582,792
...       ...         ...        ...            ...
2375  A002785      진흥기업우B      5,190        857,218
2376  A005965       동부건설우     19,250        225,732
2377  A099350      하나니켈2호      1,305      3,284,000
2378  A001755       한양증권우      8,090        525,000
2379  A245450      씨앤에스링크      2,640      1,579,960
2380  A001065     JW중외제약우     24,800        167,375
2381  A271850        다이오진      1,375      3,000,000
2382  A000995     DB하이텍1우     36,050        112,316
2383  A002787     진흥기업2우B     13,500        294,808
2384  A084440         유비온      1,300      2,997,107
2385  A000545       흥국화재우      4,975        768,000
2386  A092590        럭스피아        517      7,291,098
2387  A001067   JW중외제약2우B     39,350         87,790
2388  A189350          코셋        835      4,000,000
2389  A149940          모다        155     21,160,409
2390  A00781K   코리아써키트2우B      4,100        783,699
2391  A000325      노루홀딩스우     17,200        185,250
2392  A032685       소프트센우     22,000        142,857
2393  A227420    포레스팅블록체인        399      7,587,936
2394  A001527       동양2우B      9,810        308,569
2395  A000547     흥국화재2우B     19,200        153,600
2396  A000227     유유제약2우B     17,900        164,080
2397  A001799     대한제당3우B     21,500        129,656
2398  A223220      아이피몬스터        256     10,787,261
2399  A208890       에듀파트너      1,310      1,990,820
2400  A276240        엘리비젼        997      2,587,200
2401  A001529       동양3우B     27,600         89,722
2402  A247300  인프라웨어테크놀러지        370      6,118,198
2403  A224020     에스케이씨에스        830      2,700,000
2404  A135270     세종머티리얼즈        104      7,146,051

[2405 rows x 4 columns]

In [65]:
def double_data(value):
    return value*2
modified_data = corp_info.apply(double_data)
modified_data

,종목코드,종목명,현재가,상장주식수
0,A005930A005930,삼성전자삼성전자,"46,10046,100","5,969,782,5505,969,782,550"
1,A000660A000660,SK하이닉스SK하이닉스,"77,00077,000","728,002,365728,002,365"
2,A005935A005935,삼성전자우삼성전자우,"38,10038,100","822,886,700822,886,700"
3,A005380A005380,현대차현대차,"128,000128,000","213,668,187213,668,187"
4,A051910A051910,LG화학LG화학,"333,000333,000","70,592,34370,592,343"
5,A012330A012330,현대모비스현대모비스,"242,500242,500","95,306,69495,306,694"
6,A068270A068270,셀트리온셀트리온,"179,000179,000","128,329,070128,329,070"
7,A035420A035420,NAVERNAVER,"138,500138,500","164,813,395164,813,395"
8,A055550A055550,신한지주신한지주,"43,90043,900","474,199,587474,199,587"
9,A005490A005490,POSCOPOSCO,"228,500228,500","87,186,83587,186,835"
10,A017670A017670,SK텔레콤SK텔레콤,"246,000246,000","80,745,71180,745,711"
11,A051900A051900,LG생활건강LG생활건강,"1,240,0001,240,000","15,618,19715,618,197"
12,A105560A105560,KB금융KB금융,"43,60043,600","418,111,537418,111,537"
13,A207940A207940,삼성바이오로직스삼성바이오로직스,"273,000273,000","66,165,00066,165,000"
14,A015760A015760,한국전력한국전력,"27,95027,950","641,964,077641,964,077"
15,A028260A028260,삼성물산삼성물산,"92,30092,300","189,690,043189,690,043"
16,A000270A000270,기아차기아차,"42,85042,850","405,363,347405,363,347"
17,A018260A018260,삼성에스디에스삼성에스디에스,"212,000212,000","77,377,80077,377,800"
18,A006400A006400,삼성SDI삼성SDI,"229,000229,000","68,764,53068,764,530"
19,A096770A096770,SK이노베이션SK이노베이션,"169,000169,000","92,465,56492,465,564"
20,A034730A034730,SKSK,"221,500221,500","70,360,29770,360,297"
21,A032830A032830,삼성생명삼성생명,"77,00077,000","200,000,000200,000,000"
22,A033780A033780,KT&GKT&G,"96,80096,800","137,292,497137,292,497"
23,A003550A003550,LGLG,"73,30073,300","172,557,131172,557,131"
24,A000810A000810,삼성화재삼성화재,"262,500262,500","47,374,83747,374,837"
25,A066570A066570,LG전자LG전자,"68,60068,600","163,647,814163,647,814"
26,A035720A035720,카카오카카오,"129,000129,000","83,475,61083,475,610"
27,A036570A036570,엔씨소프트엔씨소프트,"485,000485,000","21,946,52221,946,522"
28,A086790A086790,하나금융지주하나금융지주,"35,10035,100","300,242,062300,242,062"
29,A010950A010950,S-OilS-Oil,"91,70091,700","112,582,792112,582,792"
...,...,...,...,...
2375,A002785A002785,진흥기업우B진흥기업우B,"5,1905,190","857,218857,218"
2376,A005965A005965,동부건설우동부건설우,"19,25019,250","225,732225,732"
2377,A099350A099350,하나니켈2호하나니켈2호,"1,3051,305","3,284,0003,284,000"
2378,A001755A001755,한양증권우한양증권우,"8,0908,090","525,000525,000"
2379,A245450A245450,씨앤에스링크씨앤에스링크,"2,6402,640","1,579,9601,579,960"
2380,A001065A001065,JW중외제약우JW중외제약우,"24,80024,800","167,375167,375"
2381,A271850A271850,다이오진다이오진,"1,3751,375","3,000,0003,000,000"
2382,A000995A000995,DB하이텍1우DB하이텍1우,"36,05036,050","112,316112,316"
2383,A002787A002787,진흥기업2우B진흥기업2우B,"13,50013,500","294,808294,808"
2384,A084440A084440,유비온유비온,"1,3001,300","2,997,1072,997,107"
2385,A000545A000545,흥국화재우흥국화재우,"4,9754,975","768,000768,000"
2386,A092590A092590,럭스피아럭스피아,517517,"7,291,0987,291,098"
2387,A001067A001067,JW중외제약2우BJW중외제약2우B,"39,35039,350","87,79087,790"
2388,A189350A189350,코셋코셋,835835,"4,000,0004,000,000"
2389,A149940A149940,모다모다,155155,"21,160,40921,160,409"
2390,A00781KA00781K,코리아써키트2우B코리아써키트2우B,"4,1004,100","783,699783,699"
2391,A000325A000325,노루홀딩스우노루홀딩스우,"17,20017,200","185,250185,250"
2392,A032685A032685,소프트센우소프트센우,"22,00022,000","142,857142,857"
2393,A227420A227420,포레스팅블록체인포레스팅블록체인,399399,"7,587,9367,587,936"
2394,A001527A001527,동양2우B동양2우B,"9,8109,810","308,569308,569"
2395,A000547A000547,흥국화재2우B흥국화재2우B,"19,20019,200","153,600153,600"
2396,A000227A000227,유유제약2우B유유제약2우B,"17,90017,900","164,080164,080"
2397,A001799A001799,대한제당3우B대한제당3우B,"21,50021,500","129,656129,656"
2398,A223220A223220,아이피몬스터아이피몬스터,256256,"10,787,26110,787,261"
2399,A208890A208890,에듀파트너에듀파트너,"1,3101,310","1,990,8201,990,820"
2400,A276240A276240,엘리비젼엘리비젼,997997,"2,587,2002,587,200"
2401,A001529A001529,동양3우B동양3우B,"27,60027,600","89,72289,722"
2402,A247300A247300,인프라웨어테크놀러지인프라웨어테크놀러지,370370,"6,118,1986,118,198"
2403,A224020A224020,에스케이씨에스에스케이씨에스,830830,"2,700,0002,700,000"
2404,A135270A135270,세종머티리얼즈세종머티리얼즈,104104,"7,146,0517,146,051"

In [66]:
corp_result = pd.read_excel('201903(한글).xlsx', header=[1,2])
corp_result

                     시장               종목코드                회사명  \
     Unnamed: 0_level_1 Unnamed: 1_level_1 Unnamed: 2_level_1
0                    KS            A010400            우진아이엔에스
1                    KS            A016580               환인제약
2                    KS            A034590             인천도시가스
3                    KQ            A007680                 대원
4                    KQ            A026150               특수건설
5                    KQ            A053950               경남제약
6                    KQ            A060900             퍼시픽바이오
7                    KQ            A061970              엘비세미콘
8                    KQ            A064510             에코마이스터
9                    KQ            A078150            HB테크놀러지
10                   KQ            A078590               두올산업
11                   KQ            A100790           미래에셋벤처투자
12                   KQ            A119830                아이텍
13                   KQ            A148140               비디아이
14                   KQ            A180400                캔서롭
15                   KQ            A183490            엔지켐생명과학
16                   KQ            A218150             미래생명자원
17                   KQ            A219420             링크제니시스
18                   KQ            A222810             한류AI센터
19                   KQ            A224110              에이텍티앤
20                   KQ            A226340                 본느
21                   KQ            A226950                올릭스
22                   KQ            A227950              마이크로텍
23                   KQ            A230980               솔트웍스
24                   KQ            A234100                 세원
25                   KQ            A234920                자이글
26                   KQ            A238090               앤디포스
27                   KQ            A255220                 SG
28                   KQ            A258830              세종메디칼
29                   KQ            A263020              디케이앤디
...                 ...                ...                ...
2017                 KQ            A297570          IBKS제9호스팩
2018                 KS            A298000               효성화학
2019                 KS            A298020              효성티앤씨
2020                 KS            A298040              효성중공업
2021                 KS            A298050             효성첨단소재
2022                 KQ            A298380            에이비엘바이오
2023                 KS            A298690               에어부산
2024                 KQ            A299170         IBKS제10호스팩
2025                 KQ            A299660                셀리드
2026                 KS            A300720              한일시멘트
2027                 KQ            A302430              이노메트리
2028                 KQ            A303030         대신밸런스제5호스팩
2029                 KS            A306200               세아제강
2030                 KQ            A306620           DB금융스팩6호
2031                 KQ            A307070             SK4호스팩
2032                 KQ            A307160         하나머스트제6호스팩
2033                 KQ            A307180             신영스팩4호
2034                 KQ            A307280             교보8호스팩
2035                 KQ            A307750         대신밸런스제6호스팩
2036                 KQ            A307870          골든브릿지이안5호
2037                 KS            A307950             현대오토에버
2038                 KQ            A309930          삼성머스트스팩3호
2039                 KQ            A310200         미래에셋대우스팩2호
2040                 KQ            A310840          엔에이치스팩13호
2041                 KQ            A310870            한국제8호스팩
2042                 KQ            A311270            키움제5호스팩
2043                 KQ            A313750           유안타제4호스팩
2044                 KS            A316140             우리금융지주
2045                 KQ            A317030           케이비17호스팩
2046                 KQ            A317320          한화에스비아이스팩

                   회계기준               산업코드                           산업명  \
     Unnamed: 3_level_1 Unnamed: 4_level_1            Unnamed: 5_level_1
0                    연결              64200                      전문직별 공사업
1                    연결              32100              의료용 물질 및 의약품 제조업
2                    연결              43500         전기, 가스, 증기 및 공기조절 공급업
3                    연결              64100                        종합 건설업
4                    연결              64100                        종합 건설업
5                    연결              32100              의료용 물질 및 의약품 제조업
6                    연결              31900           코크스, 연탄 및 석유정제품 제조업
7                    연결              32600  전자부품, 컴퓨터, 영상, 음향 및 통신장비 제조업
8                    연결              32900                기타 기계 및 장비 제조업
9                    연결              32900                기타 기계 및 장비 제조업
10                   연결              33000                자동차 및 트레일러 제조업
11                   연결             117201                         기타금융업
12                   연결             137300           기타 전문, 과학 및 기술 서비스업
13                   연결              32900                기타 기계 및 장비 제조업
14                   연결             137200    건축기술, 엔지니어링 및 기타 과학기술 서비스업
15                   연결              32100              의료용 물질 및 의약품 제조업
16                   연결              31000                       식료품 제조업
17                   연결             105800                           출판업
18                   연결             105800                           출판업
19                   연결              32600  전자부품, 컴퓨터, 영상, 음향 및 통신장비 제조업
20                   연결              32000       화학물질 및 화학제품 제조업; 의약품 제외
21                   연결             137000                         연구개발업
22                   연결              32900                기타 기계 및 장비 제조업
23                   연결             105800                           출판업
24                   연결              33000                자동차 및 트레일러 제조업
25                   연결              32800                      전기장비 제조업
26                   연결              32200               고무 및 플라스틱제품 제조업
27                   연결              32300                  비금속 광물제품 제조업
28                   연결              32700         의료, 정밀, 광학기기 및 시계 제조업
29                   연결              32200               고무 및 플라스틱제품 제조업
...                 ...                ...                           ...
2017                 개별             117201                         기타금융업
2018                 연결              32000       화학물질 및 화학제품 제조업; 의약품 제외
2019                 연결              32000       화학물질 및 화학제품 제조업; 의약품 제외
2020                 연결              32800                      전기장비 제조업
2021                 연결              32000       화학물질 및 화학제품 제조업; 의약품 제외
2022                 개별              32100              의료용 물질 및 의약품 제조업
2023                 개별              85100                        항공 운송업
2024                 개별             117201                         기타금융업
2025                 개별             137000                         연구개발업
2026                 개별              32300                  비금속 광물제품 제조업
2027                 연결              32900                기타 기계 및 장비 제조업
2028                 개별             117201                         기타금융업
2029                 개별              32400                     1차 금속 제조업
2030                 개별             117201                         기타금융업
2031                 개별             117201                         기타금융업
2032                 개별             117201                         기타금융업
2033                 개별             117201                         기타금융업
2034                 개별             117201                         기타금융업
2035                 개별             117201                         기타금융업
2036                 개별             117201                         기타금융업
2037                 연결             105800                           출판업
2038                 개별             117201                         기타금융업
2039                 개별             117201                         기타금융업
2040                 개별             117201                         기타금융업
2041                 개별             117201                         기타금융업
2042                 개별             117201                         기타금융업
2043                 개별             117201                         기타금융업
2044                 연결             116502                         금융지주업
2045                 개별             117201                         기타금융업
2046                 개별             117201                         기타금융업

                     단위          자산총계                              ...  \
     Unnamed: 6_level_1        201903    201812(비교)        201812  ...
0                    천원     122739921  122226689.00  122226689.00  ...
1                    천원     300272097  287687354.00           nan  ...
2                    천원     407062046  347800979.00  347800979.00  ...
3                    천원     469921572  444525540.00  444525540.00  ...
4                    천원     162364350  147908766.00  147908766.00  ...
5                    천원      53580364   53157002.00   53157002.00  ...
6                    천원      40489256   38145477.00   38145477.00  ...
7                    천원     418626361  388960521.00  379402418.00  ...
8                    천원      81544373   83116774.00   83116774.00  ...
9                    천원     256596801  246035426.00  246035426.00  ...
10                   천원      69130399   70085034.00   70085034.00  ...
11                   천원     398490951  325853635.00  325853635.00  ...
12                   천원     122582790  119484193.00  119484193.00  ...
13                   천원     145222840  148068120.00  148068120.00  ...
14                   천원      58782509   67542860.00   67542860.00  ...
15                   천원      69930620   67045474.00   67045474.00  ...
16                   천원      35620834   34085140.00   34085140.00  ...
17                   천원      35706825   36098619.00   36098619.00  ...
18                   천원      45893626   49385746.00           nan  ...
19                   천원     107423329  104147602.00  104147602.00  ...
20                   천원      33727591   34336249.00   34336249.00  ...
21                   천원      56060571   55636946.00   55636946.00  ...
22                   천원      40703508   28652327.00   28652327.00  ...
23                   천원      45305674   50671211.00   50671211.00  ...
24                   천원      72784381   58995821.00           nan  ...
25                   천원      87632559   94296332.00   94296332.00  ...
26                   천원     157539621  130369260.00  130369260.00  ...
27                   천원     205446629  200180759.00  200180759.00  ...
28                   천원      46994773   46378114.00   46378114.00  ...
29                   천원      58726625   59022016.00   59022016.00  ...
...                 ...           ...           ...           ...  ...
2017                 천원       6205982    6207699.00    6207699.00  ...
2018                 천원    1702078469 1653249379.00 1653249379.00  ...
2019                 천원    3277454879 3138844259.00 3138844259.00  ...
2020                 천원    4139724802 3432511553.00 3432511553.00  ...
2021                 천원    2598807841 2534697811.00 2534697811.00  ...
2022                 천원     166010984  168869115.00  168869115.00  ...
2023                 천원     590970768  302699757.00  302699757.00  ...
2024                 천원       9862370    9832536.00    9832536.00  ...
2025                 천원      54554581   14216133.00   14216133.00  ...
2026                 천원    1326039801 1368001171.00 1368001171.00  ...
2027                 천원      58024027   59657395.00   59657395.00  ...
2028                 천원       8434871    8410382.00    8410382.00  ...
2029                 천원    1079990499 1054118541.00 1054118541.00  ...
2030                 천원       9887462    9853248.00    9853248.00  ...
2031                 천원       9907100    9855456.00    9855456.00  ...
2032                 천원       8961877    8933159.00    8933159.00  ...
2033                 천원       9837901    9841878.00    9841878.00  ...
2034                 천원       7856369    7836408.00    7836408.00  ...
2035                 천원      10328656   10324178.00   10324178.00  ...
2036                 천원       9769261    9737214.00    9737214.00  ...
2037                 천원     937906227  829071191.00  829071191.00  ...
2038                 천원       9007156    8969194.00    8969194.00  ...
2039                 천원       6896545    6968101.00    6968101.00  ...
2040                 천원       7904639    7883704.00    7883704.00  ...
2041                 천원       6894022    6879631.00    6879631.00  ...
2042                 천원       7903672           nan    7873138.00  ...
2043                 천원       9822388    1788497.00    1788497.00  ...
2044                 천원  345148958000           nan           nan  ...
2045                 천원      11786815           nan           nan  ...
2046                 천원       1488609           nan           nan  ...

      투자활동으로인한현금흐름                                          재무활동으로인한현금흐름  \
            201812       201809       201806        201803        201903
0     -16393083.00   6181838.00          nan    2783986.00    -266098.50
1              nan          nan          nan           nan      -1706.00
2      -3117444.00  -2960981.00  -1862983.00           nan   -5337489.74
3     -14742404.00 -15954917.00 -16308079.00  -29330811.00   -8072296.00
4     -16808462.00  -4162667.00  -8417518.00    1744641.00   10897575.00
5       -795067.00   -473052.00   -281188.00    -208015.00    -150000.00
6      -6486632.00  -6613646.00  -6959073.00   -1029891.00    1560200.00
7    -127191590.00 -93216348.00 -80268284.00 -102693318.00    3795992.41
8      -1629320.00  -1500698.00  -1040486.00   -2733475.00    1236847.54
9      27608129.00  12905495.00  16587731.00           nan    1598998.00
10     -6911812.00          nan          nan           nan   -2609797.91
11     -1170234.00  -1086579.00    -65332.00           nan   52477999.29
12    -64347420.00 -14626466.00          nan           nan   -1887829.95
13     -2848489.00  -4133451.00  -9541977.00   -4952862.00    5939464.62
14    -34592250.00 -31913680.00 -13658463.00           nan   -9208155.00
15    -36038238.00 -35840789.00 -28007183.00           nan    2827440.50
16    -13626166.00 -14078228.00 -11835728.00   -9640625.00     895411.64
17    -16466738.00 -10367003.00 -10011624.00   -8835240.00     -33400.10
18             nan          nan          nan           nan     127940.09
19     -5329722.00  -5943932.00  -5647398.00   -1948286.00     206960.70
20      -406097.00          nan          nan           nan   -1507921.71
21    -31742488.00          nan          nan           nan      16815.00
22      3337522.00          nan          nan           nan   12811413.00
23    -12048451.00  -5077164.00  -6161467.00   -2462751.00   -7279415.74
24             nan -16467725.00  -9740871.00           nan      69239.69
25    -11573885.00 -15171234.00 -16391659.00   -2447478.00           nan
26    -15311791.00          nan          nan           nan   23537806.20
27    -20786183.00 -13431013.00 -11890593.00   -7451888.00    9697357.50
28    -19543281.00 -21031174.00 -19107012.00           nan     -21114.80
29     -1783057.00          nan          nan           nan    -456078.00
...            ...          ...          ...           ...           ...
2017   -5000000.00  -5000000.00          nan           nan           nan
2018 -145179345.00 -77140271.00 -25339261.00           nan   60663186.60
2019 -149998549.00 -83404153.00  -3898430.00           nan    1034903.49
2020  -41514298.00 -15755934.00 -11596048.00           nan  364648389.64
2021 -104288893.00 -58529635.00 -37978570.00           nan   -7641002.90
2022  -22775481.00          nan          nan           nan     508564.10
2023  -14242756.00          nan          nan           nan           nan
2024   -8000000.00  -8000000.00          nan           nan           nan
2025  -10809361.00  -9085188.00  -7078513.00           nan   39795655.82
2026  -14328309.00  -3466388.00          nan           nan  -30731956.62
2027   -9587471.00          nan          nan           nan    -919050.00
2028   -7000000.00  -7000000.00          nan           nan           nan
2029   -2648619.00  30600062.00          nan           nan  -13853990.74
2030   -8000000.00          nan          nan           nan           nan
2031   -8000000.00          nan          nan           nan           nan
2032   -7500000.00          nan          nan           nan           nan
2033   -8500000.00          nan          nan           nan           nan
2034   -6200000.00          nan          nan           nan           nan
2035   -9000000.00          nan          nan           nan           nan
2036   -9700000.00          nan          nan           nan           nan
2037  -26604467.00 -32803270.00 -25938664.00           nan   11227904.79
2038   -8800000.00          nan          nan           nan           nan
2039   -5500000.00          nan          nan           nan           nan
2040   -7700000.00          nan          nan           nan           nan
2041   -6000000.00          nan          nan           nan           nan
2042   -7000000.00          nan          nan           nan           nan
2043           nan          nan          nan           nan    8194096.00
2044           nan          nan          nan           nan -318508000.00
2045           nan          nan          nan           nan   11988421.16
2046           nan          nan          nan           nan    1496651.60


         201803(비교)        201812        201809        201806      201803
0       -2488800.00   18171861.00   18511200.00           nan -2488800.00
1               nan           nan           nan           nan         nan
2       -5317398.75   -6176303.00   -6287429.00   -6039589.00         nan
3        -103952.00   21592798.00    3661141.00    3664907.00  -103952.00
4       -1445988.00   22912315.00    4400684.00    3115022.00 -1445988.00
5       -2540000.00    4924999.00   -4940000.00   -4780000.00 -2540000.00
6         959747.60    3475696.00    6654796.00    4266757.00   959748.00
7       50673703.78   46781785.00   38324628.00   47795464.00 50673704.00
8        4625543.40   11669650.00   11247627.00   11141513.00  4625543.00
9        7549367.00    6765626.00    8751191.00    5139882.00         nan
10              nan   28989998.00           nan           nan         nan
11       5100000.00   11256195.00   18127896.00   26624800.00         nan
12       9227631.00   70492745.00   61463605.00           nan         nan
13      13560000.00   14868357.00   26761370.00   28283599.00 13560000.00
14        256605.00   10549685.00   10517273.00   10448973.00         nan
15      43494267.00   47235677.00   45319099.00   46074699.00         nan
16       1626930.40     970771.00    2245903.00    2078731.00  1626930.00
17       9238750.00   18391294.00   19226588.00    9257839.00  9238750.00
18       9999995.98           nan           nan           nan         nan
19        929268.07   -3519499.00    -398039.00    -628039.00   929268.00
20       -444781.26    1177339.00           nan           nan         nan
21              nan   42255121.00           nan           nan         nan
22       -493312.00    1529768.00           nan           nan         nan
23       2934242.61    5816942.00   -2197138.00    -267797.00  2934243.00
24              nan           nan   23014222.00   23999999.00         nan
25         50000.00   13908386.00   13908386.00   13908386.00    50000.00
26        351770.00   36280609.00           nan           nan         nan
27      25534557.31   55561024.00   49357753.00   28068323.00 25534557.00
28        -18524.92   18139190.00   18722711.00   18681263.00         nan
29      -1073859.00    3750465.00           nan           nan         nan
...             ...           ...           ...           ...         ...

In [5]:
corp_result.columns

MultiIndex(levels=[['(당기순이익 귀속)\n비지배주주지분', '(당기순이익 귀속)\n지배기업주주지분', '(총포괄이익 귀속)\n비지배주주지분', '(총포괄이익 귀속)\n지배기업주주지분', '계속사업이익', '금융비용', '금융수익', '기타금융업부채', '기타금융업자산', '기타영업비용', '기타영업수익', '기타영업외비용', '기타영업외수익', '기타포괄이익', '단위', '당기순이익', '매출액', '매출원가', '매출총이익', '법인세비용', '법인세비용차감전이익', '부채총계', '비유동부채', '비유동자산', '비지배주주지분', '산업명', '산업코드', '시장', '영업이익(계산수치)', '영업이익(보고서기재)', '영업활동으로인한현금흐름', '유동부채', '유동자산', '자본총계', '자산총계', '재무활동으로인한현금흐름', '종목코드', '종속기업등관련이익', '종속회사 매수일전 순손익', '중단사업이익', '지배기업주주지분', '처분된 종속회사 순손익', '총포괄이익', '투자활동으로인한현금흐름', '판관비', '회계기준', '회사명'], [201803, 201806, 201809, 201812, 201903, '201803(비교)', '201812(비교)', 'Unnamed: 0_level_1', 'Unnamed: 1_level_1', 'Unnamed: 2_level_1', 'Unnamed: 3_level_1', 'Unnamed: 4_level_1', 'Unnamed: 5_level_1', 'Unnamed: 6_level_1']],
           codes=[[27, 36, 46, 45, 26, 25, 14, 34, 34, 34, 34, 34, 34, 32, 32, 32, 32, 32, 32, 23, 23, 23, 23, 23, 23, 8, 8, 8, 8, 8, 8, 21, 21, 21, 21, 21, 21, 31, 31, 31, 31, 31, 31, 22, 22, 22, 22, 22, 22, 7, 7, 7, 7, 7, 7, 33, 33, 33, 33, 33, 33, 40, 40, 40, 40, 40, 40, 24, 24, 24, 24, 24, 24, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 10, 10, 10, 10, 10, 10, 44, 44, 44, 44, 44, 44, 9, 9, 9, 9, 9, 9, 29, 29, 29, 29, 29, 29, 28, 28, 28, 28, 28, 28, 12, 12, 12, 12, 12, 12, 11, 11, 11, 11, 11, 11, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 37, 37, 37, 37, 37, 37, 20, 20, 20, 20, 20, 20, 19, 19, 19, 19, 19, 19, 38, 38, 38, 38, 38, 38, 41, 41, 41, 41, 41, 41, 4, 4, 4, 4, 4, 4, 39, 39, 39, 39, 39, 39, 15, 15, 15, 15, 15, 15, 13, 13, 13, 13, 13, 13, 42, 42, 42, 42, 42, 42, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 30, 30, 30, 30, 30, 30, 43, 43, 43, 43, 43, 43, 35, 35, 35, 35, 35, 35], [7, 8, 9, 10, 11, 12, 13, 4, 6, 3, 2, 1, 0, 4, 6, 3, 2, 1, 0, 4, 6, 3, 2, 1, 0, 4, 6, 3, 2, 1, 0, 4, 6, 3, 2, 1, 0, 4, 6, 3, 2, 1, 0, 4, 6, 3, 2, 1, 0, 4, 6, 3, 2, 1, 0, 4, 6, 3, 2, 1, 0, 4, 6, 3, 2, 1, 0, 4, 6, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0, 4, 5, 3, 2, 1, 0]])

In [88]:
corp_data = corp_result[[('종목코드','Unnamed: 1_level_1'),('당기순이익', 201812)]]
corp_data

                   종목코드         당기순이익
     Unnamed: 1_level_1        201812
0               A010400   14446830.00
1               A016580           nan
2               A034590   16123899.00
3               A007680   30710353.00
4               A026150     709871.00
5               A053950    3720205.00
6               A060900  -13331758.00
7               A061970   18780424.00
8               A064510  -43381849.00
9               A078150    8114959.00
10              A078590   -6626223.00
11              A100790   18576257.00
12              A119830    1576623.00
13              A148140     366136.00
14              A180400   -5365781.00
15              A183490  -14420231.00
16              A218150    1776467.00
17              A219420    2196294.00
18              A222810           nan
19              A224110    5831984.00
20              A226340     313437.00
21              A226950   -7742007.00
22              A227950   -4753661.00
23              A230980     257845.00
24              A234100           nan
25              A234920   -6237553.00
26              A238090  -13601715.00
27              A255220    9619134.00
28              A258830    3597545.00
29              A263020    3731735.00
...                 ...           ...
2017            A297570       -756.00
2018            A298000   20394861.00
2019            A298020   31498303.00
2020            A298040    1908746.00
2021            A298050  -23744728.00
2022            A298380 -117234140.00
2023            A298690   20294184.00
2024            A299170     -25108.00
2025            A299660  -11286321.00
2026            A300720   53726823.00
2027            A302430    5247720.00
2028            A303030      -4049.00
2029            A306200    7030156.00
2030            A306620         33.00
2031            A307070     -24500.00
2032            A307160      -9884.00
2033            A307180    -131025.00
2034            A307280     -28370.00
2035            A307750     -26859.00
2036            A307870      -2987.00
2037            A307950   55228435.00
2038            A309930      -7758.00
2039            A310200     -11654.00
2040            A310840     -10869.00
2041            A310870      -7076.00
2042            A311270    -130749.00
2043            A313750     -13122.00
2044            A316140           nan
2045            A317030           nan
2046            A317320           nan

[2047 rows x 2 columns]

In [91]:
corp_data.columns = corp_data.columns.get_level_values(0)
#corp_data.columns = corp_data.columns.to_flat_index()
corp_data

         종목코드         당기순이익
0     A010400   14446830.00
1     A016580           nan
2     A034590   16123899.00
3     A007680   30710353.00
4     A026150     709871.00
5     A053950    3720205.00
6     A060900  -13331758.00
7     A061970   18780424.00
8     A064510  -43381849.00
9     A078150    8114959.00
10    A078590   -6626223.00
11    A100790   18576257.00
12    A119830    1576623.00
13    A148140     366136.00
14    A180400   -5365781.00
15    A183490  -14420231.00
16    A218150    1776467.00
17    A219420    2196294.00
18    A222810           nan
19    A224110    5831984.00
20    A226340     313437.00
21    A226950   -7742007.00
22    A227950   -4753661.00
23    A230980     257845.00
24    A234100           nan
25    A234920   -6237553.00
26    A238090  -13601715.00
27    A255220    9619134.00
28    A258830    3597545.00
29    A263020    3731735.00
...       ...           ...
2017  A297570       -756.00
2018  A298000   20394861.00
2019  A298020   31498303.00
2020  A298040    1908746.00
2021  A298050  -23744728.00
2022  A298380 -117234140.00
2023  A298690   20294184.00
2024  A299170     -25108.00
2025  A299660  -11286321.00
2026  A300720   53726823.00
2027  A302430    5247720.00
2028  A303030      -4049.00
2029  A306200    7030156.00
2030  A306620         33.00
2031  A307070     -24500.00
2032  A307160      -9884.00
2033  A307180    -131025.00
2034  A307280     -28370.00
2035  A307750     -26859.00
2036  A307870      -2987.00
2037  A307950   55228435.00
2038  A309930      -7758.00
2039  A310200     -11654.00
2040  A310840     -10869.00
2041  A310870      -7076.00
2042  A311270    -130749.00
2043  A313750     -13122.00
2044  A316140           nan
2045  A317030           nan
2046  A317320           nan

[2047 rows x 2 columns]

In [98]:
corp_total = pd.merge(corp_info, corp_data, how='left', on='종목코드')
corp_total

         종목코드         종목명        현재가          상장주식수          당기순이익
0     A005930        삼성전자     46,100  5,969,782,550 44344857000.00
1     A000660      SK하이닉스     77,000    728,002,365 15539984000.00
2     A005935       삼성전자우     38,100    822,886,700            nan
3     A005380         현대차    128,000    213,668,187  1645019000.00
4     A051910        LG화학    333,000     70,592,343  1519312000.00
5     A012330       현대모비스    242,500     95,306,694  1888206000.00
6     A068270        셀트리온    179,000    128,329,070   253563111.00
7     A035420       NAVER    138,500    164,813,395   627901873.00
8     A055550        신한지주     43,900    474,199,587  3198265000.00
9     A005490       POSCO    228,500     87,186,835  1892064406.00
10    A017670       SK텔레콤    246,000     80,745,711  3131988000.00
11    A051900      LG생활건강  1,240,000     15,618,197   692278706.00
12    A105560        KB금융     43,600    418,111,537  3061946000.00
13    A207940    삼성바이오로직스    273,000     66,165,000   224109195.00
14    A015760        한국전력     27,950    641,964,077 -1174498000.00
15    A028260        삼성물산     92,300    189,690,043  1748243543.00
16    A000270         기아차     42,850    405,363,347  1155943000.00
17    A018260     삼성에스디에스    212,000     77,377,800   638792258.00
18    A006400       삼성SDI    229,000     68,764,530   745049185.00
19    A096770     SK이노베이션    169,000     92,465,564  1709984041.00
20    A034730          SK    221,500     70,360,297  6151141000.00
21    A032830        삼성생명     77,000    200,000,000  1733710000.00
22    A033780        KT&G     96,800    137,292,497   898659340.00
23    A003550          LG     73,300    172,557,131  1882897000.00
24    A000810        삼성화재    262,500     47,374,837  1073301208.00
25    A066570        LG전자     68,600    163,647,814  1472814000.00
26    A035720         카카오    129,000     83,475,610    15888859.00
27    A036570       엔씨소프트    485,000     21,946,522   421467651.00
28    A086790      하나금융지주     35,100    300,242,062  2275152000.00
29    A010950       S-Oil     91,700    112,582,792   258035000.00
...       ...         ...        ...            ...            ...
2375  A002785      진흥기업우B      5,190        857,218            nan
2376  A005965       동부건설우     19,250        225,732            nan
2377  A099350      하나니켈2호      1,305      3,284,000            nan
2378  A001755       한양증권우      8,090        525,000            nan
2379  A245450      씨앤에스링크      2,640      1,579,960            nan
2380  A001065     JW중외제약우     24,800        167,375            nan
2381  A271850        다이오진      1,375      3,000,000            nan
2382  A000995     DB하이텍1우     36,050        112,316            nan
2383  A002787     진흥기업2우B     13,500        294,808            nan
2384  A084440         유비온      1,300      2,997,107            nan
2385  A000545       흥국화재우      4,975        768,000            nan
2386  A092590        럭스피아        517      7,291,098            nan
2387  A001067   JW중외제약2우B     39,350         87,790            nan
2388  A189350          코셋        835      4,000,000            nan
2389  A149940          모다        155     21,160,409    -5819454.00
2390  A00781K   코리아써키트2우B      4,100        783,699            nan
2391  A000325      노루홀딩스우     17,200        185,250            nan
2392  A032685       소프트센우     22,000        142,857            nan
2393  A227420    포레스팅블록체인        399      7,587,936            nan
2394  A001527       동양2우B      9,810        308,569            nan
2395  A000547     흥국화재2우B     19,200        153,600            nan
2396  A000227     유유제약2우B     17,900        164,080            nan
2397  A001799     대한제당3우B     21,500        129,656            nan
2398  A223220      아이피몬스터        256     10,787,261            nan
2399  A208890       에듀파트너      1,310      1,990,820            nan
2400  A276240        엘리비젼        997      2,587,200            nan
2401  A001529       동양3우B     27,600         89,722            nan
2402  A247300  인프라웨어테크놀러지        370      6,118,198            nan
2403  A224020     에스케이씨에스        830      2,700,000            nan
2404  A135270     세종머티리얼즈        104      7,146,051            nan

[2405 rows x 5 columns]

In [100]:
corp_total = corp_info.join(corp_data.set_index('종목코드'), how='outer', on='종목코드')
corp_total

         종목코드         종목명        현재가          상장주식수          당기순이익
0     A005930        삼성전자     46,100  5,969,782,550 44344857000.00
1     A000660      SK하이닉스     77,000    728,002,365 15539984000.00
2     A005935       삼성전자우     38,100    822,886,700            nan
3     A005380         현대차    128,000    213,668,187  1645019000.00
4     A051910        LG화학    333,000     70,592,343  1519312000.00
5     A012330       현대모비스    242,500     95,306,694  1888206000.00
6     A068270        셀트리온    179,000    128,329,070   253563111.00
7     A035420       NAVER    138,500    164,813,395   627901873.00
8     A055550        신한지주     43,900    474,199,587  3198265000.00
9     A005490       POSCO    228,500     87,186,835  1892064406.00
10    A017670       SK텔레콤    246,000     80,745,711  3131988000.00
11    A051900      LG생활건강  1,240,000     15,618,197   692278706.00
12    A105560        KB금융     43,600    418,111,537  3061946000.00
13    A207940    삼성바이오로직스    273,000     66,165,000   224109195.00
14    A015760        한국전력     27,950    641,964,077 -1174498000.00
15    A028260        삼성물산     92,300    189,690,043  1748243543.00
16    A000270         기아차     42,850    405,363,347  1155943000.00
17    A018260     삼성에스디에스    212,000     77,377,800   638792258.00
18    A006400       삼성SDI    229,000     68,764,530   745049185.00
19    A096770     SK이노베이션    169,000     92,465,564  1709984041.00
20    A034730          SK    221,500     70,360,297  6151141000.00
21    A032830        삼성생명     77,000    200,000,000  1733710000.00
22    A033780        KT&G     96,800    137,292,497   898659340.00
23    A003550          LG     73,300    172,557,131  1882897000.00
24    A000810        삼성화재    262,500     47,374,837  1073301208.00
25    A066570        LG전자     68,600    163,647,814  1472814000.00
26    A035720         카카오    129,000     83,475,610    15888859.00
27    A036570       엔씨소프트    485,000     21,946,522   421467651.00
28    A086790      하나금융지주     35,100    300,242,062  2275152000.00
29    A010950       S-Oil     91,700    112,582,792   258035000.00
...       ...         ...        ...            ...            ...
2378  A001755       한양증권우      8,090        525,000            nan
2379  A245450      씨앤에스링크      2,640      1,579,960            nan
2380  A001065     JW중외제약우     24,800        167,375            nan
2381  A271850        다이오진      1,375      3,000,000            nan
2382  A000995     DB하이텍1우     36,050        112,316            nan
2383  A002787     진흥기업2우B     13,500        294,808            nan
2384  A084440         유비온      1,300      2,997,107            nan
2385  A000545       흥국화재우      4,975        768,000            nan
2386  A092590        럭스피아        517      7,291,098            nan
2387  A001067   JW중외제약2우B     39,350         87,790            nan
2388  A189350          코셋        835      4,000,000            nan
2389  A149940          모다        155     21,160,409    -5819454.00
2390  A00781K   코리아써키트2우B      4,100        783,699            nan
2391  A000325      노루홀딩스우     17,200        185,250            nan
2392  A032685       소프트센우     22,000        142,857            nan
2393  A227420    포레스팅블록체인        399      7,587,936            nan
2394  A001527       동양2우B      9,810        308,569            nan
2395  A000547     흥국화재2우B     19,200        153,600            nan
2396  A000227     유유제약2우B     17,900        164,080            nan
2397  A001799     대한제당3우B     21,500        129,656            nan
2398  A223220      아이피몬스터        256     10,787,261            nan
2399  A208890       에듀파트너      1,310      1,990,820            nan
2400  A276240        엘리비젼        997      2,587,200            nan
2401  A001529       동양3우B     27,600         89,722            nan
2402  A247300  인프라웨어테크놀러지        370      6,118,198            nan
2403  A224020     에스케이씨에스        830      2,700,000            nan
2404  A135270     세종머티리얼즈        104      7,146,051            nan
2404  A002250         NaN        NaN            NaN    10614871.00
2404  A026180         NaN        NaN            NaN    -6188688.00
2404  A079660         NaN        NaN            NaN     7882205.00

[2408 rows x 5 columns]

In [106]:
corp_total['당기순이익']=corp_total['당기순이익'].astype('float')*1000
corp_total

         종목코드         종목명        현재가          상장주식수             당기순이익   EPS
0     A005930        삼성전자     46,100  5,969,782,550 44344857000000.00  7.43
1     A000660      SK하이닉스     77,000    728,002,365 15539984000000.00 21.35
2     A005935       삼성전자우     38,100    822,886,700               nan   nan
3     A005380         현대차    128,000    213,668,187  1645019000000.00  7.70
4     A051910        LG화학    333,000     70,592,343  1519312000000.00 21.52
5     A012330       현대모비스    242,500     95,306,694  1888206000000.00 19.81
6     A068270        셀트리온    179,000    128,329,070   253563111000.00  1.98
7     A035420       NAVER    138,500    164,813,395   627901873000.00  3.81
8     A055550        신한지주     43,900    474,199,587  3198265000000.00  6.74
9     A005490       POSCO    228,500     87,186,835  1892064406000.00 21.70
10    A017670       SK텔레콤    246,000     80,745,711  3131988000000.00 38.79
11    A051900      LG생활건강  1,240,000     15,618,197   692278706000.00 44.33
12    A105560        KB금융     43,600    418,111,537  3061946000000.00  7.32
13    A207940    삼성바이오로직스    273,000     66,165,000   224109195000.00  3.39
14    A015760        한국전력     27,950    641,964,077 -1174498000000.00 -1.83
15    A028260        삼성물산     92,300    189,690,043  1748243543000.00  9.22
16    A000270         기아차     42,850    405,363,347  1155943000000.00  2.85
17    A018260     삼성에스디에스    212,000     77,377,800   638792258000.00  8.26
18    A006400       삼성SDI    229,000     68,764,530   745049185000.00 10.83
19    A096770     SK이노베이션    169,000     92,465,564  1709984041000.00 18.49
20    A034730          SK    221,500     70,360,297  6151141000000.00 87.42
21    A032830        삼성생명     77,000    200,000,000  1733710000000.00  8.67
22    A033780        KT&G     96,800    137,292,497   898659340000.00  6.55
23    A003550          LG     73,300    172,557,131  1882897000000.00 10.91
24    A000810        삼성화재    262,500     47,374,837  1073301208000.00 22.66
25    A066570        LG전자     68,600    163,647,814  1472814000000.00  9.00
26    A035720         카카오    129,000     83,475,610    15888859000.00  0.19
27    A036570       엔씨소프트    485,000     21,946,522   421467651000.00 19.20
28    A086790      하나금융지주     35,100    300,242,062  2275152000000.00  7.58
29    A010950       S-Oil     91,700    112,582,792   258035000000.00  2.29
...       ...         ...        ...            ...               ...   ...
2378  A001755       한양증권우      8,090        525,000               nan   nan
2379  A245450      씨앤에스링크      2,640      1,579,960               nan   nan
2380  A001065     JW중외제약우     24,800        167,375               nan   nan
2381  A271850        다이오진      1,375      3,000,000               nan   nan
2382  A000995     DB하이텍1우     36,050        112,316               nan   nan
2383  A002787     진흥기업2우B     13,500        294,808               nan   nan
2384  A084440         유비온      1,300      2,997,107               nan   nan
2385  A000545       흥국화재우      4,975        768,000               nan   nan
2386  A092590        럭스피아        517      7,291,098               nan   nan
2387  A001067   JW중외제약2우B     39,350         87,790               nan   nan
2388  A189350          코셋        835      4,000,000               nan   nan
2389  A149940          모다        155     21,160,409    -5819454000.00 -0.28
2390  A00781K   코리아써키트2우B      4,100        783,699               nan   nan
2391  A000325      노루홀딩스우     17,200        185,250               nan   nan
2392  A032685       소프트센우     22,000        142,857               nan   nan
2393  A227420    포레스팅블록체인        399      7,587,936               nan   nan
2394  A001527       동양2우B      9,810        308,569               nan   nan
2395  A000547     흥국화재2우B     19,200        153,600               nan   nan
2396  A000227     유유제약2우B     17,900        164,080               nan   nan
2397  A001799     대한제당3우B     21,500        129,656               nan   nan
2398  A223220      아이피몬스터        256     10,787,261               nan   nan
2399  A208890       에듀파트너      1,310      1,990,820               nan   nan
2400  A276240        엘리비젼        997      2,587,200               nan   nan
2401  A001529       동양3우B     27,600         89,722               nan   nan
2402  A247300  인프라웨어테크놀러지        370      6,118,198               nan   nan
2403  A224020     에스케이씨에스        830      2,700,000               nan   nan
2404  A135270     세종머티리얼즈        104      7,146,051               nan   nan
2404  A002250         NaN        NaN            NaN    10614871000.00   nan
2404  A026180         NaN        NaN            NaN    -6188688000.00   nan
2404  A079660         NaN        NaN            NaN     7882205000.00   nan

[2408 rows x 6 columns]

In [107]:
corp_total["EPS"] = corp_total['당기순이익'].astype('float')/corp_total['상장주식수'].str.replace(',','').astype('float')
corp_total

         종목코드         종목명        현재가          상장주식수             당기순이익      EPS
0     A005930        삼성전자     46,100  5,969,782,550 44344857000000.00  7428.22
1     A000660      SK하이닉스     77,000    728,002,365 15539984000000.00 21346.06
2     A005935       삼성전자우     38,100    822,886,700               nan      nan
3     A005380         현대차    128,000    213,668,187  1645019000000.00  7698.94
4     A051910        LG화학    333,000     70,592,343  1519312000000.00 21522.33
5     A012330       현대모비스    242,500     95,306,694  1888206000000.00 19811.89
6     A068270        셀트리온    179,000    128,329,070   253563111000.00  1975.88
7     A035420       NAVER    138,500    164,813,395   627901873000.00  3809.77
8     A055550        신한지주     43,900    474,199,587  3198265000000.00  6744.55
9     A005490       POSCO    228,500     87,186,835  1892064406000.00 21701.26
10    A017670       SK텔레콤    246,000     80,745,711  3131988000000.00 38788.29
11    A051900      LG생활건강  1,240,000     15,618,197   692278706000.00 44325.14
12    A105560        KB금융     43,600    418,111,537  3061946000000.00  7323.28
13    A207940    삼성바이오로직스    273,000     66,165,000   224109195000.00  3387.13
14    A015760        한국전력     27,950    641,964,077 -1174498000000.00 -1829.54
15    A028260        삼성물산     92,300    189,690,043  1748243543000.00  9216.32
16    A000270         기아차     42,850    405,363,347  1155943000000.00  2851.62
17    A018260     삼성에스디에스    212,000     77,377,800   638792258000.00  8255.50
18    A006400       삼성SDI    229,000     68,764,530   745049185000.00 10834.79
19    A096770     SK이노베이션    169,000     92,465,564  1709984041000.00 18493.20
20    A034730          SK    221,500     70,360,297  6151141000000.00 87423.47
21    A032830        삼성생명     77,000    200,000,000  1733710000000.00  8668.55
22    A033780        KT&G     96,800    137,292,497   898659340000.00  6545.58
23    A003550          LG     73,300    172,557,131  1882897000000.00 10911.73
24    A000810        삼성화재    262,500     47,374,837  1073301208000.00 22655.51
25    A066570        LG전자     68,600    163,647,814  1472814000000.00  8999.90
26    A035720         카카오    129,000     83,475,610    15888859000.00   190.34
27    A036570       엔씨소프트    485,000     21,946,522   421467651000.00 19204.30
28    A086790      하나금융지주     35,100    300,242,062  2275152000000.00  7577.73
29    A010950       S-Oil     91,700    112,582,792   258035000000.00  2291.96
...       ...         ...        ...            ...               ...      ...
2378  A001755       한양증권우      8,090        525,000               nan      nan
2379  A245450      씨앤에스링크      2,640      1,579,960               nan      nan
2380  A001065     JW중외제약우     24,800        167,375               nan      nan
2381  A271850        다이오진      1,375      3,000,000               nan      nan
2382  A000995     DB하이텍1우     36,050        112,316               nan      nan
2383  A002787     진흥기업2우B     13,500        294,808               nan      nan
2384  A084440         유비온      1,300      2,997,107               nan      nan
2385  A000545       흥국화재우      4,975        768,000               nan      nan
2386  A092590        럭스피아        517      7,291,098               nan      nan
2387  A001067   JW중외제약2우B     39,350         87,790               nan      nan
2388  A189350          코셋        835      4,000,000               nan      nan
2389  A149940          모다        155     21,160,409    -5819454000.00  -275.02
2390  A00781K   코리아써키트2우B      4,100        783,699               nan      nan
2391  A000325      노루홀딩스우     17,200        185,250               nan      nan
2392  A032685       소프트센우     22,000        142,857               nan      nan
2393  A227420    포레스팅블록체인        399      7,587,936               nan      nan
2394  A001527       동양2우B      9,810        308,569               nan      nan
2395  A000547     흥국화재2우B     19,200        153,600               nan      nan
2396  A000227     유유제약2우B     17,900        164,080               nan      nan
2397  A001799     대한제당3우B     21,500        129,656               nan      nan
2398  A223220      아이피몬스터        256     10,787,261               nan      nan
2399  A208890       에듀파트너      1,310      1,990,820               nan      nan
2400  A276240        엘리비젼        997      2,587,200               nan      nan
2401  A001529       동양3우B     27,600         89,722               nan      nan
2402  A247300  인프라웨어테크놀러지        370      6,118,198               nan      nan
2403  A224020     에스케이씨에스        830      2,700,000               nan      nan
2404  A135270     세종머티리얼즈        104      7,146,051               nan      nan
2404  A002250         NaN        NaN            NaN    10614871000.00      nan
2404  A026180         NaN        NaN            NaN    -6188688000.00      nan
2404  A079660         NaN        NaN            NaN     7882205000.00      nan

[2408 rows x 6 columns]

In [111]:
corp_total = corp_total[pd.notnull(corp_total['EPS'])]
corp_total = corp_total[pd.notnull(corp_total['현재가'])]
corp_total

         종목코드         종목명        현재가          상장주식수             당기순이익      EPS
0     A005930        삼성전자     46,100  5,969,782,550 44344857000000.00  7428.22
1     A000660      SK하이닉스     77,000    728,002,365 15539984000000.00 21346.06
3     A005380         현대차    128,000    213,668,187  1645019000000.00  7698.94
4     A051910        LG화학    333,000     70,592,343  1519312000000.00 21522.33
5     A012330       현대모비스    242,500     95,306,694  1888206000000.00 19811.89
6     A068270        셀트리온    179,000    128,329,070   253563111000.00  1975.88
7     A035420       NAVER    138,500    164,813,395   627901873000.00  3809.77
8     A055550        신한지주     43,900    474,199,587  3198265000000.00  6744.55
9     A005490       POSCO    228,500     87,186,835  1892064406000.00 21701.26
10    A017670       SK텔레콤    246,000     80,745,711  3131988000000.00 38788.29
11    A051900      LG생활건강  1,240,000     15,618,197   692278706000.00 44325.14
12    A105560        KB금융     43,600    418,111,537  3061946000000.00  7323.28
13    A207940    삼성바이오로직스    273,000     66,165,000   224109195000.00  3387.13
14    A015760        한국전력     27,950    641,964,077 -1174498000000.00 -1829.54
15    A028260        삼성물산     92,300    189,690,043  1748243543000.00  9216.32
16    A000270         기아차     42,850    405,363,347  1155943000000.00  2851.62
17    A018260     삼성에스디에스    212,000     77,377,800   638792258000.00  8255.50
18    A006400       삼성SDI    229,000     68,764,530   745049185000.00 10834.79
19    A096770     SK이노베이션    169,000     92,465,564  1709984041000.00 18493.20
20    A034730          SK    221,500     70,360,297  6151141000000.00 87423.47
21    A032830        삼성생명     77,000    200,000,000  1733710000000.00  8668.55
22    A033780        KT&G     96,800    137,292,497   898659340000.00  6545.58
23    A003550          LG     73,300    172,557,131  1882897000000.00 10911.73
24    A000810        삼성화재    262,500     47,374,837  1073301208000.00 22655.51
25    A066570        LG전자     68,600    163,647,814  1472814000000.00  8999.90
26    A035720         카카오    129,000     83,475,610    15888859000.00   190.34
27    A036570       엔씨소프트    485,000     21,946,522   421467651000.00 19204.30
28    A086790      하나금융지주     35,100    300,242,062  2275152000000.00  7577.73
29    A010950       S-Oil     91,700    112,582,792   258035000000.00  2291.96
31    A090430      아모레퍼시픽    151,000     58,458,490   334844564000.00  5727.90
...       ...         ...        ...            ...               ...      ...
2277  A297570   IBKS제9호스팩      3,755      2,760,000        -756000.00    -0.27
2278  A306620    DB금융스팩6호      2,130      4,840,000          33000.00     0.01
2279  A307160  하나머스트제6호스팩      2,220      4,590,000       -9884000.00    -2.15
2282  A192410         감마누        408     24,435,800    -4702885000.00  -192.46
2283  A307870   상상인이안1호스팩      2,090      4,750,000       -2987000.00    -0.63
2285  A270520   하나금융10호스팩      2,150      4,602,000       47120000.00    10.24
2286  A299170  IBKS제10호스팩      2,285      4,330,000      -25108000.00    -5.80
2288  A309930   삼성머스트스팩3호      2,150      4,590,000       -7758000.00    -1.69
2289  A281410     한국제6호스팩      2,175      4,510,000       79631000.00    17.66
2290  A313750    유안타제4호스팩      2,095      4,650,000      -13122000.00    -2.82
2291  A267320      교보7호스팩      2,420      4,020,000       18335000.00     4.56
2292  A083470       KJ프리텍        387     24,704,729   -34709813000.00 -1404.99
2296  A265920      한화수성스팩      2,120      4,440,000       84416000.00    19.01
2297  A307180      신영스팩4호      2,150      4,355,000     -131025000.00   -30.09
2299  A261200    하나금융9호스팩      2,160      4,260,000       75990000.00    17.84
2302  A287410    유안타제3호스팩      2,145      4,235,000       -3864000.00    -0.91
2306  A271740     한국제5호스팩      2,200      4,000,000       33170000.00     8.29
2310  A276920   IBKS제7호스팩      2,285      3,650,000       52462000.00    14.37
2314  A307280      교보8호스팩      2,180      3,720,000      -28370000.00    -7.63
2320  A257730     신한제3호스팩      2,260      3,505,000       42475000.00    12.12
2322  A311270     키움제5호스팩      2,175      3,600,000     -130749000.00   -36.32
2326  A030270        에스마크        998      7,562,701   -34495693000.00 -4561.29
2330  A310200  미래에셋대우스팩2호      2,465      3,050,000      -11654000.00    -3.82
2331  A279410   한화에이스스팩4호      2,135      3,495,000       22372000.00     6.40
2332  A258790   케이비제11호스팩      2,315      3,210,000       19814000.00     6.17
2333  A232330      SK3호스팩      2,060      3,600,000       64396000.00    17.89
2336  A310840   엔에이치스팩13호      2,150      3,420,000      -10869000.00    -3.18
2338  A310870     한국제8호스팩      2,135      3,420,000       -7076000.00    -2.07
2342  A264290   한화에이스스팩3호      2,295      3,080,000       16457000.00     5.34
2389  A149940          모다        155     21,160,409    -5819454000.00  -275.02

[2024 rows x 6 columns]

In [112]:
corp_total["PER"] = corp_total["현재가"].str.replace(",","").astype('int')/corp_total["EPS"]
corp_total

,종목코드,종목명,현재가,상장주식수,당기순이익,EPS,PER
0,A005930,삼성전자,"46,100","5,969,782,550",44344857000000.00,7428.22,6.21
1,A000660,SK하이닉스,"77,000","728,002,365",15539984000000.00,21346.06,3.61
3,A005380,현대차,"128,000","213,668,187",1645019000000.00,7698.94,16.63
4,A051910,LG화학,"333,000","70,592,343",1519312000000.00,21522.33,15.47
5,A012330,현대모비스,"242,500","95,306,694",1888206000000.00,19811.89,12.24
6,A068270,셀트리온,"179,000","128,329,070",253563111000.00,1975.88,90.59
7,A035420,NAVER,"138,500","164,813,395",627901873000.00,3809.77,36.35
8,A055550,신한지주,"43,900","474,199,587",3198265000000.00,6744.55,6.51
9,A005490,POSCO,"228,500","87,186,835",1892064406000.00,21701.26,10.53
10,A017670,SK텔레콤,"246,000","80,745,711",3131988000000.00,38788.29,6.34
11,A051900,LG생활건강,"1,240,000","15,618,197",692278706000.00,44325.14,27.98
12,A105560,KB금융,"43,600","418,111,537",3061946000000.00,7323.28,5.95
13,A207940,삼성바이오로직스,"273,000","66,165,000",224109195000.00,3387.13,80.60
14,A015760,한국전력,"27,950","641,964,077",-1174498000000.00,-1829.54,-15.28
15,A028260,삼성물산,"92,300","189,690,043",1748243543000.00,9216.32,10.01
16,A000270,기아차,"42,850","405,363,347",1155943000000.00,2851.62,15.03
17,A018260,삼성에스디에스,"212,000","77,377,800",638792258000.00,8255.50,25.68
18,A006400,삼성SDI,"229,000","68,764,530",745049185000.00,10834.79,21.14
19,A096770,SK이노베이션,"169,000","92,465,564",1709984041000.00,18493.20,9.14
20,A034730,SK,"221,500","70,360,297",6151141000000.00,87423.47,2.53
21,A032830,삼성생명,"77,000","200,000,000",1733710000000.00,8668.55,8.88
22,A033780,KT&G,"96,800","137,292,497",898659340000.00,6545.58,14.79
23,A003550,LG,"73,300","172,557,131",1882897000000.00,10911.73,6.72
24,A000810,삼성화재,"262,500","47,374,837",1073301208000.00,22655.51,11.59
25,A066570,LG전자,"68,600","163,647,814",1472814000000.00,8999.90,7.62
26,A035720,카카오,"129,000","83,475,610",15888859000.00,190.34,677.73
27,A036570,엔씨소프트,"485,000","21,946,522",421467651000.00,19204.30,25.25
28,A086790,하나금융지주,"35,100","300,242,062",2275152000000.00,7577.73,4.63
29,A010950,S-Oil,"91,700","112,582,792",258035000000.00,2291.96,40.01
31,A090430,아모레퍼시픽,"151,000","58,458,490",334844564000.00,5727.90,26.36
...,...,...,...,...,...,...,...
2277,A297570,IBKS제9호스팩,"3,755","2,760,000",-756000.00,-0.27,-13708.73
2278,A306620,DB금융스팩6호,"2,130","4,840,000",33000.00,0.01,312400.00
2279,A307160,하나머스트제6호스팩,"2,220","4,590,000",-9884000.00,-2.15,-1030.94
2282,A192410,감마누,408,"24,435,800",-4702885000.00,-192.46,-2.12
2283,A307870,상상인이안1호스팩,"2,090","4,750,000",-2987000.00,-0.63,-3323.57
2285,A270520,하나금융10호스팩,"2,150","4,602,000",47120000.00,10.24,209.98
2286,A299170,IBKS제10호스팩,"2,285","4,330,000",-25108000.00,-5.80,-394.06
2288,A309930,삼성머스트스팩3호,"2,150","4,590,000",-7758000.00,-1.69,-1272.04
2289,A281410,한국제6호스팩,"2,175","4,510,000",79631000.00,17.66,123.18
2290,A313750,유안타제4호스팩,"2,095","4,650,000",-13122000.00,-2.82,-742.40
2291,A267320,교보7호스팩,"2,420","4,020,000",18335000.00,4.56,530.59
2292,A083470,KJ프리텍,387,"24,704,729",-34709813000.00,-1404.99,-0.28
2296,A265920,한화수성스팩,"2,120","4,440,000",84416000.00,19.01,111.50
2297,A307180,신영스팩4호,"2,150","4,355,000",-131025000.00,-30.09,-71.46
2299,A261200,하나금융9호스팩,"2,160","4,260,000",75990000.00,17.84,121.09
2302,A287410,유안타제3호스팩,"2,145","4,235,000",-3864000.00,-0.91,-2350.95
2306,A271740,한국제5호스팩,"2,200","4,000,000",33170000.00,8.29,265.30
2310,A276920,IBKS제7호스팩,"2,285","3,650,000",52462000.00,14.37,158.98
2314,A307280,교보8호스팩,"2,180","3,720,000",-28370000.00,-7.63,-285.85
2320,A257730,신한제3호스팩,"2,260","3,505,000",42475000.00,12.12,186.49
2322,A311270,키움제5호스팩,"2,175","3,600,000",-130749000.00,-36.32,-59.89
2326,A030270,에스마크,998,"7,562,701",-34495693000.00,-4561.29,-0.22
2330,A310200,미래에셋대우스팩2호,"2,465","3,050,000",-11654000.00,-3.82,-645.12
2331,A279410,한화에이스스팩4호,"2,135","3,495,000",22372000.00,6.40,333.53
2332,A258790,케이비제11호스팩,"2,315","3,210,000",19814000.00,6.17,375.05
2333,A232330,SK3호스팩,"2,060","3,600,000",64396000.00,17.89,115.16
2336,A310840,엔에이치스팩13호,"2,150","3,420,000",-10869000.00,-3.18,-676.51
2338,A310870,한국제8호스팩,"2,135","3,420,000",-7076000.00,-2.07,-1031.90
2342,A264290,한화에이스스팩3호,"2,295","3,080,000",16457000.00,5.34,429.52
2389,A149940,모다,155,"21,160,409",-5819454000.00,-275.02,-0.56

In [127]:
corp_filter = corp_total[(corp_total["PER"]>=12) & (corp_total["PER"]<=15)]
corp_filter

         종목코드      종목명      현재가        상장주식수            당기순이익      EPS   PER
5     A012330    현대모비스  242,500   95,306,694 1888206000000.00 19811.89 12.24
22    A033780     KT&G   96,800  137,292,497  898659340000.00  6545.58 14.79
43    A086280   현대글로비스  154,000   37,500,000  437373374000.00 11663.29 13.20
47    A004020     현대제철   38,900  133,445,785  407959435000.00  3057.12 12.72
49    A002790     아모레G   58,300   82,458,180  376271212000.00  4563.18 12.78
66    A241560     두산밥캣   35,900  100,249,166  264497169000.00  2638.40 13.61
100   A007310      오뚜기  649,000    3,605,237  160829137000.00 44609.87 14.55
105   A263750     펄어비스  165,400   13,021,400  146446177000.00 11246.58 14.71
115   A026960       동서   17,600   99,700,000  120396957000.00  1207.59 14.57
119   A010620   현대미포조선   42,600   39,942,149  120655434000.00  3020.75 14.10
128   A204320       만도   33,400   46,957,120  112927633000.00  2404.91 13.89
132   A111770     영원무역   33,850   44,311,468  111285166000.00  2511.43 13.48
142   A009240       한샘   57,000   23,533,928   89957037000.00  3822.44 14.91
147   A214320      이노션   65,300   20,000,000   92381768000.00  4619.09 14.14
164   A240810    원익IPS   23,200   49,083,901   86860389000.00  1769.63 13.11
169   A114090      GKL   18,050   61,855,670   77740630000.00  1256.81 14.36
195   A046890    서울반도체   15,800   58,305,400   62601339000.00  1073.68 14.72
199   A014680    한솔케미칼   80,000   11,295,195   67755735000.00  5998.63 13.34
206   A018250     애경산업   32,400   26,346,535   60789196000.00  2307.29 14.04
216   A001680       대상   23,500   34,648,025   65398472000.00  1887.51 12.45
238   A200130  콜마비앤에이치   24,100   29,543,558   49322397000.00  1669.48 14.44
245   A064960   S&T모티브   47,400   14,623,136   57225145000.00  3913.33 12.11
248   A018670     SK가스   75,300    9,141,781   55438443000.00  6064.29 12.42
256   A064760     티씨케이   56,400   11,675,000   46856952000.00  4013.44 14.05
263   A108320    실리콘웍스   38,650   16,264,300   48960453000.00  3010.30 12.84
271   A027410      BGF    6,310   95,716,791   47204821000.00   493.17 12.79
272   A086450     동국제약   67,800    8,892,000   49433167000.00  5559.29 12.20
287   A002270     롯데푸드  497,500    1,131,870   42540086000.00 37583.90 13.24
320   A003230     삼양식품   63,500    7,533,015   35304531000.00  4686.64 13.55
322   A010050     우리종금      703  674,203,406   33364010000.00    49.49 14.21
...       ...      ...      ...          ...              ...      ...   ...
1528  A114810     아이원스    4,925   13,415,919    5339651000.00   398.01 12.37
1538  A083550      케이엠    6,460   10,142,170    4578031000.00   451.39 14.31
1546  A033310  디케이디앤아이    2,965   21,972,411    4406555000.00   200.55 14.78
1564  A123570      이엠넷    2,870   22,276,078    4500362000.00   202.03 14.21
1569  A000220     유유제약    9,970    6,368,587    4312110000.00   677.09 14.72
1595  A101240      씨큐브    7,680    8,050,441    4504161000.00   559.49 13.73
1611  A048430     유라테크    5,260   11,520,000    4479801000.00   388.87 13.53
1660  A037440       희림    4,040   13,922,475    3957145000.00   284.23 14.21
1681  A024840    KBI메탈    1,675   32,950,848    4400083000.00   133.53 12.54
1705  A048770      TPC    4,150   12,900,000    4147039000.00   321.48 12.91
1707  A065770       CS    2,840   18,835,150    4097741000.00   217.56 13.05
1731  A051490    나라엠앤디    3,670   14,200,000    3744173000.00   263.67 13.92
1753  A064820      케이프    1,975   25,528,573    4176501000.00   163.60 12.07
1759  A092870      엑시콘    5,650    8,883,500    3711680000.00   417.82 13.52
1772  A123700      SJM    3,155   15,604,898    3726141000.00   238.78 13.21
1790  A265560     영화테크    9,020    5,345,090    3898865000.00   729.43 12.37
1809  A263020    디케이앤디    6,040    7,763,202    3731735000.00   480.70 12.57
1846  A008470      부스타    5,310    8,404,800    2987173000.00   355.41 14.94
1866  A050960   수산아이앤티    6,410    6,751,000    3120145000.00   462.18 13.87
1868  A085910     네오티스    3,910   11,013,678    3178419000.00   288.59 13.55
1877  A083500  에프엔에스테크    5,700    7,425,062    3207393000.00   431.97 13.20
1897  A007770     한일화학   11,800    3,510,000    2843593000.00   810.14 14.57
1898  A005320       국동    1,500   27,596,156    2956053000.00   107.12 14.00
1929  A104040    대성파인텍    1,270   31,301,281    2982309000.00    95.28 13.33
1935  A079000   와토스코리아    5,440    7,200,000    2902873000.00   403.18 13.49
1973  A131220     대한과학    5,010    7,454,490    2516975000.00   337.65 14.84
2002  A109080     옵티시스    6,330    5,636,000    2771172000.00   491.69 12.87
2026  A053160     프리엠스    5,660    6,000,000    2306497000.00   384.42 14.72
2028  A032280       삼일    2,090   16,213,590    2573956000.00   158.75 13.17
2069  A173130     오파스넷    7,570    4,025,902    2289021000.00   568.57 13.31

[144 rows x 7 columns]

In [125]:
corp_total.query('PER >=12 & PER <=15')

         종목코드      종목명      현재가        상장주식수            당기순이익      EPS   PER
5     A012330    현대모비스  242,500   95,306,694 1888206000000.00 19811.89 12.24
22    A033780     KT&G   96,800  137,292,497  898659340000.00  6545.58 14.79
43    A086280   현대글로비스  154,000   37,500,000  437373374000.00 11663.29 13.20
47    A004020     현대제철   38,900  133,445,785  407959435000.00  3057.12 12.72
49    A002790     아모레G   58,300   82,458,180  376271212000.00  4563.18 12.78
66    A241560     두산밥캣   35,900  100,249,166  264497169000.00  2638.40 13.61
100   A007310      오뚜기  649,000    3,605,237  160829137000.00 44609.87 14.55
105   A263750     펄어비스  165,400   13,021,400  146446177000.00 11246.58 14.71
115   A026960       동서   17,600   99,700,000  120396957000.00  1207.59 14.57
119   A010620   현대미포조선   42,600   39,942,149  120655434000.00  3020.75 14.10
128   A204320       만도   33,400   46,957,120  112927633000.00  2404.91 13.89
132   A111770     영원무역   33,850   44,311,468  111285166000.00  2511.43 13.48
142   A009240       한샘   57,000   23,533,928   89957037000.00  3822.44 14.91
147   A214320      이노션   65,300   20,000,000   92381768000.00  4619.09 14.14
164   A240810    원익IPS   23,200   49,083,901   86860389000.00  1769.63 13.11
169   A114090      GKL   18,050   61,855,670   77740630000.00  1256.81 14.36
195   A046890    서울반도체   15,800   58,305,400   62601339000.00  1073.68 14.72
199   A014680    한솔케미칼   80,000   11,295,195   67755735000.00  5998.63 13.34
206   A018250     애경산업   32,400   26,346,535   60789196000.00  2307.29 14.04
216   A001680       대상   23,500   34,648,025   65398472000.00  1887.51 12.45
238   A200130  콜마비앤에이치   24,100   29,543,558   49322397000.00  1669.48 14.44
245   A064960   S&T모티브   47,400   14,623,136   57225145000.00  3913.33 12.11
248   A018670     SK가스   75,300    9,141,781   55438443000.00  6064.29 12.42
256   A064760     티씨케이   56,400   11,675,000   46856952000.00  4013.44 14.05
263   A108320    실리콘웍스   38,650   16,264,300   48960453000.00  3010.30 12.84
271   A027410      BGF    6,310   95,716,791   47204821000.00   493.17 12.79
272   A086450     동국제약   67,800    8,892,000   49433167000.00  5559.29 12.20
287   A002270     롯데푸드  497,500    1,131,870   42540086000.00 37583.90 13.24
320   A003230     삼양식품   63,500    7,533,015   35304531000.00  4686.64 13.55
322   A010050     우리종금      703  674,203,406   33364010000.00    49.49 14.21
...       ...      ...      ...          ...              ...      ...   ...
1528  A114810     아이원스    4,925   13,415,919    5339651000.00   398.01 12.37
1538  A083550      케이엠    6,460   10,142,170    4578031000.00   451.39 14.31
1546  A033310  디케이디앤아이    2,965   21,972,411    4406555000.00   200.55 14.78
1564  A123570      이엠넷    2,870   22,276,078    4500362000.00   202.03 14.21
1569  A000220     유유제약    9,970    6,368,587    4312110000.00   677.09 14.72
1595  A101240      씨큐브    7,680    8,050,441    4504161000.00   559.49 13.73
1611  A048430     유라테크    5,260   11,520,000    4479801000.00   388.87 13.53
1660  A037440       희림    4,040   13,922,475    3957145000.00   284.23 14.21
1681  A024840    KBI메탈    1,675   32,950,848    4400083000.00   133.53 12.54
1705  A048770      TPC    4,150   12,900,000    4147039000.00   321.48 12.91
1707  A065770       CS    2,840   18,835,150    4097741000.00   217.56 13.05
1731  A051490    나라엠앤디    3,670   14,200,000    3744173000.00   263.67 13.92
1753  A064820      케이프    1,975   25,528,573    4176501000.00   163.60 12.07
1759  A092870      엑시콘    5,650    8,883,500    3711680000.00   417.82 13.52
1772  A123700      SJM    3,155   15,604,898    3726141000.00   238.78 13.21
1790  A265560     영화테크    9,020    5,345,090    3898865000.00   729.43 12.37
1809  A263020    디케이앤디    6,040    7,763,202    3731735000.00   480.70 12.57
1846  A008470      부스타    5,310    8,404,800    2987173000.00   355.41 14.94
1866  A050960   수산아이앤티    6,410    6,751,000    3120145000.00   462.18 13.87
1868  A085910     네오티스    3,910   11,013,678    3178419000.00   288.59 13.55
1877  A083500  에프엔에스테크    5,700    7,425,062    3207393000.00   431.97 13.20
1897  A007770     한일화학   11,800    3,510,000    2843593000.00   810.14 14.57
1898  A005320       국동    1,500   27,596,156    2956053000.00   107.12 14.00
1929  A104040    대성파인텍    1,270   31,301,281    2982309000.00    95.28 13.33
1935  A079000   와토스코리아    5,440    7,200,000    2902873000.00   403.18 13.49
1973  A131220     대한과학    5,010    7,454,490    2516975000.00   337.65 14.84
2002  A109080     옵티시스    6,330    5,636,000    2771172000.00   491.69 12.87
2026  A053160     프리엠스    5,660    6,000,000    2306497000.00   384.42 14.72
2028  A032280       삼일    2,090   16,213,590    2573956000.00   158.75 13.17
2069  A173130     오파스넷    7,570    4,025,902    2289021000.00   568.57 13.31

[144 rows x 7 columns]

In [131]:
corp_filter.sort_values(by='PER')

         종목코드      종목명      현재가        상장주식수            당기순이익      EPS   PER
412   A008490       서흥   30,600   11,569,113   29384182000.00  2539.88 12.05
408   A097520     엠씨넥스   20,250   17,745,456   29818006000.00  1680.32 12.05
1753  A064820      케이프    1,975   25,528,573    4176501000.00   163.60 12.07
245   A064960   S&T모티브   47,400   14,623,136   57225145000.00  3913.33 12.11
420   A003800    에이스침대   31,350   11,090,000   28688839000.00  2586.91 12.12
272   A086450     동국제약   67,800    8,892,000   49433167000.00  5559.29 12.20
1360  A008250     이건산업    7,250   10,952,635    6510008000.00   594.38 12.20
553   A084370     유진테크   11,050   22,916,042   20688886000.00   902.81 12.24
5     A012330    현대모비스  242,500   95,306,694 1888206000000.00 19811.89 12.24
463   A008350    남선알미늄    2,810  110,179,090   25220519000.00   228.90 12.28
911   A003650     미창석유   76,000    1,739,672   10722193000.00  6163.34 12.33
407   A043150       바텍   24,250   14,854,256   29152011000.00  1962.54 12.36
1790  A265560     영화테크    9,020    5,345,090    3898865000.00   729.43 12.37
498   A003220     대원제약   14,650   19,662,677   23286287000.00  1184.29 12.37
1528  A114810     아이원스    4,925   13,415,919    5339651000.00   398.01 12.37
1343  A031820    콤텍시스템    1,695   47,851,466    6553668000.00   136.96 12.38
248   A018670     SK가스   75,300    9,141,781   55438443000.00  6064.29 12.42
536   A010170    대한광통신    3,585   73,741,625   21282037000.00   288.60 12.42
1376  A006660     삼성공조    9,700    8,126,314    6332359000.00   779.24 12.45
216   A001680       대상   23,500   34,648,025   65398472000.00  1887.51 12.45
988   A255220       SG    9,600   12,506,024    9619134000.00   769.16 12.48
344   A029530     신도리코   43,550   10,080,029   35034112000.00  3475.60 12.53
585   A079980      휴비스    6,900   34,500,000   18991820000.00   550.49 12.53
1681  A024840    KBI메탈    1,675   32,950,848    4400083000.00   133.53 12.54
1809  A263020    디케이앤디    6,040    7,763,202    3731735000.00   480.70 12.57
447   A080420    모다이노칩    4,070   79,721,622   25660025000.00   321.87 12.64
733   A001530     DI동일   72,500    2,421,420   13824872000.00  5709.41 12.70
451   A265520    AP시스템   22,750   14,099,511   25227012000.00  1789.21 12.72
47    A004020     현대제철   38,900  133,445,785  407959435000.00  3057.12 12.72
1460  A014440     영보화학    3,600   20,000,000    5657471000.00   282.87 12.73
...       ...      ...      ...          ...              ...      ...   ...
388   A023410     유진기업    4,950   77,310,863   26581654000.00   343.83 14.40
238   A200130  콜마비앤에이치   24,100   29,543,558   49322397000.00  1669.48 14.44
363   A011280     태림포장    5,860   70,805,940   28676653000.00   405.00 14.47
647   A003070   코오롱글로벌    8,300   25,210,438   14451160000.00   573.22 14.48
732   A046440  KG모빌리언스    5,880   29,906,957   12119266000.00   405.23 14.51
919   A067900     와이엔텍    7,210   18,199,659    9033205000.00   496.34 14.53
422   A047310    파워로직스   10,100   34,420,982   23928373000.00   695.17 14.53
100   A007310      오뚜기  649,000    3,605,237  160829137000.00 44609.87 14.55
1897  A007770     한일화학   11,800    3,510,000    2843593000.00   810.14 14.57
115   A026960       동서   17,600   99,700,000  120396957000.00  1207.59 14.57
1214  A205100       엑셈    2,700   33,882,273    6275021000.00   185.20 14.58
1425  A002920     유성기업    2,865   25,947,500    5092468000.00   196.26 14.60
383   A293480     하나제약   23,750   16,200,000   26169074000.00  1615.37 14.70
105   A263750     펄어비스  165,400   13,021,400  146446177000.00 11246.58 14.71
610   A082920     비츠로셀   10,500   21,539,152   15371863000.00   713.67 14.71
195   A046890    서울반도체   15,800   58,305,400   62601339000.00  1073.68 14.72
548   A067280    멀티캠퍼스   43,600    5,926,779   17552175000.00  2961.50 14.72
2026  A053160     프리엠스    5,660    6,000,000    2306497000.00   384.42 14.72
1569  A000220     유유제약    9,970    6,368,587    4312110000.00   677.09 14.72
1546  A033310  디케이디앤아이    2,965   21,972,411    4406555000.00   200.55 14.78
22    A033780     KT&G   96,800  137,292,497  898659340000.00  6545.58 14.79
1973  A131220     대한과학    5,010    7,454,490    2516975000.00   337.65 14.84
848   A214430  아이쓰리시스템   20,450    7,106,760    9784710000.00  1376.82 14.85
826   A100700    세운메디칼    3,420   43,800,000   10075163000.00   230.03 14.87
1213  A007590    동방아그로    6,720   13,617,577    6154336000.00   451.94 14.87
142   A009240       한샘   57,000   23,533,928   89957037000.00  3822.44 14.91
1094  A063170     서울옥션    6,250   16,917,500    7084634000.00   418.78 14.92
1846  A008470      부스타    5,310    8,404,800    2987173000.00   355.41 14.94
1453  A126600      코프라    3,430   21,115,634    4842683000.00   229.34 14.96
952   A204620  글로벌텍스프리    3,360   37,254,218    8365701000.00   224.56 14.96

[144 rows x 7 columns]

In [133]:
corp_filter.sort_values(by='PER', ascending=False)

         종목코드      종목명      현재가        상장주식수            당기순이익      EPS   PER
952   A204620  글로벌텍스프리    3,360   37,254,218    8365701000.00   224.56 14.96
1453  A126600      코프라    3,430   21,115,634    4842683000.00   229.34 14.96
1846  A008470      부스타    5,310    8,404,800    2987173000.00   355.41 14.94
1094  A063170     서울옥션    6,250   16,917,500    7084634000.00   418.78 14.92
142   A009240       한샘   57,000   23,533,928   89957037000.00  3822.44 14.91
1213  A007590    동방아그로    6,720   13,617,577    6154336000.00   451.94 14.87
826   A100700    세운메디칼    3,420   43,800,000   10075163000.00   230.03 14.87
848   A214430  아이쓰리시스템   20,450    7,106,760    9784710000.00  1376.82 14.85
1973  A131220     대한과학    5,010    7,454,490    2516975000.00   337.65 14.84
22    A033780     KT&G   96,800  137,292,497  898659340000.00  6545.58 14.79
1546  A033310  디케이디앤아이    2,965   21,972,411    4406555000.00   200.55 14.78
1569  A000220     유유제약    9,970    6,368,587    4312110000.00   677.09 14.72
2026  A053160     프리엠스    5,660    6,000,000    2306497000.00   384.42 14.72
548   A067280    멀티캠퍼스   43,600    5,926,779   17552175000.00  2961.50 14.72
195   A046890    서울반도체   15,800   58,305,400   62601339000.00  1073.68 14.72
610   A082920     비츠로셀   10,500   21,539,152   15371863000.00   713.67 14.71
105   A263750     펄어비스  165,400   13,021,400  146446177000.00 11246.58 14.71
383   A293480     하나제약   23,750   16,200,000   26169074000.00  1615.37 14.70
1425  A002920     유성기업    2,865   25,947,500    5092468000.00   196.26 14.60
1214  A205100       엑셈    2,700   33,882,273    6275021000.00   185.20 14.58
115   A026960       동서   17,600   99,700,000  120396957000.00  1207.59 14.57
1897  A007770     한일화학   11,800    3,510,000    2843593000.00   810.14 14.57
100   A007310      오뚜기  649,000    3,605,237  160829137000.00 44609.87 14.55
422   A047310    파워로직스   10,100   34,420,982   23928373000.00   695.17 14.53
919   A067900     와이엔텍    7,210   18,199,659    9033205000.00   496.34 14.53
732   A046440  KG모빌리언스    5,880   29,906,957   12119266000.00   405.23 14.51
647   A003070   코오롱글로벌    8,300   25,210,438   14451160000.00   573.22 14.48
363   A011280     태림포장    5,860   70,805,940   28676653000.00   405.00 14.47
238   A200130  콜마비앤에이치   24,100   29,543,558   49322397000.00  1669.48 14.44
388   A023410     유진기업    4,950   77,310,863   26581654000.00   343.83 14.40
...       ...      ...      ...          ...              ...      ...   ...
1460  A014440     영보화학    3,600   20,000,000    5657471000.00   282.87 12.73
47    A004020     현대제철   38,900  133,445,785  407959435000.00  3057.12 12.72
451   A265520    AP시스템   22,750   14,099,511   25227012000.00  1789.21 12.72
733   A001530     DI동일   72,500    2,421,420   13824872000.00  5709.41 12.70
447   A080420    모다이노칩    4,070   79,721,622   25660025000.00   321.87 12.64
1809  A263020    디케이앤디    6,040    7,763,202    3731735000.00   480.70 12.57
1681  A024840    KBI메탈    1,675   32,950,848    4400083000.00   133.53 12.54
585   A079980      휴비스    6,900   34,500,000   18991820000.00   550.49 12.53
344   A029530     신도리코   43,550   10,080,029   35034112000.00  3475.60 12.53
988   A255220       SG    9,600   12,506,024    9619134000.00   769.16 12.48
216   A001680       대상   23,500   34,648,025   65398472000.00  1887.51 12.45
1376  A006660     삼성공조    9,700    8,126,314    6332359000.00   779.24 12.45
536   A010170    대한광통신    3,585   73,741,625   21282037000.00   288.60 12.42
248   A018670     SK가스   75,300    9,141,781   55438443000.00  6064.29 12.42
1343  A031820    콤텍시스템    1,695   47,851,466    6553668000.00   136.96 12.38
1528  A114810     아이원스    4,925   13,415,919    5339651000.00   398.01 12.37
498   A003220     대원제약   14,650   19,662,677   23286287000.00  1184.29 12.37
1790  A265560     영화테크    9,020    5,345,090    3898865000.00   729.43 12.37
407   A043150       바텍   24,250   14,854,256   29152011000.00  1962.54 12.36
911   A003650     미창석유   76,000    1,739,672   10722193000.00  6163.34 12.33
463   A008350    남선알미늄    2,810  110,179,090   25220519000.00   228.90 12.28
5     A012330    현대모비스  242,500   95,306,694 1888206000000.00 19811.89 12.24
553   A084370     유진테크   11,050   22,916,042   20688886000.00   902.81 12.24
1360  A008250     이건산업    7,250   10,952,635    6510008000.00   594.38 12.20
272   A086450     동국제약   67,800    8,892,000   49433167000.00  5559.29 12.20
420   A003800    에이스침대   31,350   11,090,000   28688839000.00  2586.91 12.12
245   A064960   S&T모티브   47,400   14,623,136   57225145000.00  3913.33 12.11
1753  A064820      케이프    1,975   25,528,573    4176501000.00   163.60 12.07
408   A097520     엠씨넥스   20,250   17,745,456   29818006000.00  1680.32 12.05
412   A008490       서흥   30,600   11,569,113   29384182000.00  2539.88 12.05

[144 rows x 7 columns]

In [134]:
corp_filter.sort_values(by=['PER','EPS'], ascending=False)

         종목코드      종목명      현재가        상장주식수            당기순이익      EPS   PER
952   A204620  글로벌텍스프리    3,360   37,254,218    8365701000.00   224.56 14.96
1453  A126600      코프라    3,430   21,115,634    4842683000.00   229.34 14.96
1846  A008470      부스타    5,310    8,404,800    2987173000.00   355.41 14.94
1094  A063170     서울옥션    6,250   16,917,500    7084634000.00   418.78 14.92
142   A009240       한샘   57,000   23,533,928   89957037000.00  3822.44 14.91
1213  A007590    동방아그로    6,720   13,617,577    6154336000.00   451.94 14.87
826   A100700    세운메디칼    3,420   43,800,000   10075163000.00   230.03 14.87
848   A214430  아이쓰리시스템   20,450    7,106,760    9784710000.00  1376.82 14.85
1973  A131220     대한과학    5,010    7,454,490    2516975000.00   337.65 14.84
22    A033780     KT&G   96,800  137,292,497  898659340000.00  6545.58 14.79
1546  A033310  디케이디앤아이    2,965   21,972,411    4406555000.00   200.55 14.78
1569  A000220     유유제약    9,970    6,368,587    4312110000.00   677.09 14.72
2026  A053160     프리엠스    5,660    6,000,000    2306497000.00   384.42 14.72
548   A067280    멀티캠퍼스   43,600    5,926,779   17552175000.00  2961.50 14.72
195   A046890    서울반도체   15,800   58,305,400   62601339000.00  1073.68 14.72
610   A082920     비츠로셀   10,500   21,539,152   15371863000.00   713.67 14.71
105   A263750     펄어비스  165,400   13,021,400  146446177000.00 11246.58 14.71
383   A293480     하나제약   23,750   16,200,000   26169074000.00  1615.37 14.70
1425  A002920     유성기업    2,865   25,947,500    5092468000.00   196.26 14.60
1214  A205100       엑셈    2,700   33,882,273    6275021000.00   185.20 14.58
115   A026960       동서   17,600   99,700,000  120396957000.00  1207.59 14.57
1897  A007770     한일화학   11,800    3,510,000    2843593000.00   810.14 14.57
100   A007310      오뚜기  649,000    3,605,237  160829137000.00 44609.87 14.55
422   A047310    파워로직스   10,100   34,420,982   23928373000.00   695.17 14.53
919   A067900     와이엔텍    7,210   18,199,659    9033205000.00   496.34 14.53
732   A046440  KG모빌리언스    5,880   29,906,957   12119266000.00   405.23 14.51
647   A003070   코오롱글로벌    8,300   25,210,438   14451160000.00   573.22 14.48
363   A011280     태림포장    5,860   70,805,940   28676653000.00   405.00 14.47
238   A200130  콜마비앤에이치   24,100   29,543,558   49322397000.00  1669.48 14.44
388   A023410     유진기업    4,950   77,310,863   26581654000.00   343.83 14.40
...       ...      ...      ...          ...              ...      ...   ...
1460  A014440     영보화학    3,600   20,000,000    5657471000.00   282.87 12.73
47    A004020     현대제철   38,900  133,445,785  407959435000.00  3057.12 12.72
451   A265520    AP시스템   22,750   14,099,511   25227012000.00  1789.21 12.72
733   A001530     DI동일   72,500    2,421,420   13824872000.00  5709.41 12.70
447   A080420    모다이노칩    4,070   79,721,622   25660025000.00   321.87 12.64
1809  A263020    디케이앤디    6,040    7,763,202    3731735000.00   480.70 12.57
1681  A024840    KBI메탈    1,675   32,950,848    4400083000.00   133.53 12.54
585   A079980      휴비스    6,900   34,500,000   18991820000.00   550.49 12.53
344   A029530     신도리코   43,550   10,080,029   35034112000.00  3475.60 12.53
988   A255220       SG    9,600   12,506,024    9619134000.00   769.16 12.48
216   A001680       대상   23,500   34,648,025   65398472000.00  1887.51 12.45
1376  A006660     삼성공조    9,700    8,126,314    6332359000.00   779.24 12.45
536   A010170    대한광통신    3,585   73,741,625   21282037000.00   288.60 12.42
248   A018670     SK가스   75,300    9,141,781   55438443000.00  6064.29 12.42
1343  A031820    콤텍시스템    1,695   47,851,466    6553668000.00   136.96 12.38
1528  A114810     아이원스    4,925   13,415,919    5339651000.00   398.01 12.37
498   A003220     대원제약   14,650   19,662,677   23286287000.00  1184.29 12.37
1790  A265560     영화테크    9,020    5,345,090    3898865000.00   729.43 12.37
407   A043150       바텍   24,250   14,854,256   29152011000.00  1962.54 12.36
911   A003650     미창석유   76,000    1,739,672   10722193000.00  6163.34 12.33
463   A008350    남선알미늄    2,810  110,179,090   25220519000.00   228.90 12.28
5     A012330    현대모비스  242,500   95,306,694 1888206000000.00 19811.89 12.24
553   A084370     유진테크   11,050   22,916,042   20688886000.00   902.81 12.24
1360  A008250     이건산업    7,250   10,952,635    6510008000.00   594.38 12.20
272   A086450     동국제약   67,800    8,892,000   49433167000.00  5559.29 12.20
420   A003800    에이스침대   31,350   11,090,000   28688839000.00  2586.91 12.12
245   A064960   S&T모티브   47,400   14,623,136   57225145000.00  3913.33 12.11
1753  A064820      케이프    1,975   25,528,573    4176501000.00   163.60 12.07
408   A097520     엠씨넥스   20,250   17,745,456   29818006000.00  1680.32 12.05
412   A008490       서흥   30,600   11,569,113   29384182000.00  2539.88 12.05

[144 rows x 7 columns]